
/* Program generated by Cadvanced 3.0.0.0.2032 */
#define XSCT_CADVANCED

/* "auto_cfg.h" file generated for system System_CCUH */

#ifndef XUSE_GENERIC_FUNC
#define XUSE_GENERIC_FUNC
#endif
#define XNOUSE_OPFUNCS

#ifndef XNOUSE_AUTOMATIC_OPERATOR_CFG
/* Predefined operator configuration */
#define XNOUSE_ANY
#define XNOUSE_OWN_GENERATOR
#define XNOUSE_OREF_GENERATOR
#define XNOUSE_STRING_GENERATOR
#define XNOUSE_LSTRING_GENERATOR
#define XNOUSE_ARRAY_GENERATOR
#define XNOUSE_GARRAY_GENERATOR
#define XNOUSE_POWERSET_GENERATOR
#define XNOUSE_GPOWERSET_GENERATOR
#define XNOUSE_BAG_GENERATOR
#define XNOUSE_CHOICE
#define XNOUSE_UNION
#define XNOUSE_MOD_INTEGER
#define XNOUSE_MKSTRING_CHARSTRING
#define XNOUSE_LENGTH_CHARSTRING
#define XNOUSE_FIRST_CHARSTRING
#define XNOUSE_LAST_CHARSTRING
#define XNOUSE_CONCAT_CHARSTRING
#define XNOUSE_SUBSTRING_CHARSTRING
#define XNOUSE_EXTRACT_CHARSTRING
#define XNOUSE_MODIFY_CHARSTRING
#define XNOUSE_EQ_CHARSTRING
#define XNOUSE_ASSIGN_CHARSTRING
#define XNOUSE_FREE_CHARSTRING
#define XNOUSE_BITSTR_OCTET
#define XNOUSE_HEXSTR_OCTET
#define XNOUSE_EXTRACT_OCTET
#define XNOUSE_MODIFY_OCTET
#define XNOUSE_MKSTRING_BIT_STRING
#define XNOUSE_LENGTH_BIT_STRING
#define XNOUSE_FIRST_BIT_STRING
#define XNOUSE_LAST_BIT_STRING
#define XNOUSE_CONCAT_BIT_STRING
#define XNOUSE_SUBSTRING_BIT_STRING
#define XNOUSE_BITSTR_BIT_STRING
#define XNOUSE_HEXSTR_BIT_STRING
#define XNOUSE_NOT_BIT_STRING
#define XNOUSE_AND_BIT_STRING
#define XNOUSE_OR_BIT_STRING
#define XNOUSE_XOR_BIT_STRING
#define XNOUSE_IMPL_BIT_STRING
#define XNOUSE_EXTRACT_BIT_STRING
#define XNOUSE_MODIFY_BIT_STRING
#define XNOUSE_EQ_BIT_STRING
#define XNOUSE_ASSIGN_BIT_STRING
#define XNOUSE_FREE_BIT_STRING
#define XNOUSE_BITSTR_OCTET_STRING
#define XNOUSE_HEXSTR_OCTET_STRING
#define XNOUSE_BIT_STRING_OCTET_STRING
#define XNOUSE_OCTET_STRING_OCTET_STRING
#define XNOUSE_MULT_DURATION
#define XNOUSE_DIV_DURATION
#define XNOUSE_EQ_DURATION
#define XNOUSE_MKSTRING_OBJECT_IDENTIFIER
#define XNOUSE_LENGTH_OBJECT_IDENTIFIER
#define XNOUSE_FIRST_OBJECT_IDENTIFIER
#define XNOUSE_LAST_OBJECT_IDENTIFIER
#define XNOUSE_CONCAT_OBJECT_IDENTIFIER
#define XNOUSE_SUBSTRING_OBJECT_IDENTIFIER
#define XNOUSE_EMPTYSTRING_OBJECT_IDENTIFIER
#define XNOUSE_EXTRACT_OBJECT_IDENTIFIER
#define XNOUSE_MODIFY_OBJECT_IDENTIFIER
#define XNOUSE_EQ_OBJECT_IDENTIFIER
#define XNOUSE_ASSIGN_OBJECT_IDENTIFIER
#define XNOUSE_FREE_OBJECT_IDENTIFIER
#endif

#ifdef XUSE_TYPEINFONODE_CFG
/* Type info node configuration */
#define XTNOUSE_Boolean
/* NOT #define XTNOUSE_Character*/
/* NOT #define XTNOUSE_Charstring*/
/* NOT #define XTNOUSE_Integer*/
#define XTNOUSE_Real
#define XTNOUSE_Pid
#define XTNOUSE_Duration
#define XTNOUSE_Time
#define XTNOUSE_Bit
#define XTNOUSE_Bit_string
#define XTNOUSE_Octet
#define XTNOUSE_Octet_string
#define XTNOUSE_NULL
#define XTNOUSE_Object_identifier
#define XTNOUSE_Any_type
#define XTNOUSE_IA5String
#define XTNOUSE_NumericString
#define XTNOUSE_PrintableString
#define XTNOUSE_VisibleString
#define XTNOUSE_Natural
#define XTNOUSE_ptr_void
#define XTNOUSE_ptr_char
/* NOT #define XTNOUSE_int*/
/* NOT #define XTNOUSE_unsigned_int*/
#define XTNOUSE_long_int
#define XTNOUSE_unsigned_long_int
/* NOT #define XTNOUSE_short_int*/
/* NOT #define XTNOUSE_unsigned_short_int*/
/* NOT #define XTNOUSE_char*/
#define XTNOUSE_signed_char
/* NOT #define XTNOUSE_unsigned_char*/
#define XTNOUSE_float
#define XTNOUSE_double
#define XTNOUSE_ProcessInst
#define XTNOUSE_ptr_I_PPVoid
#define XTNOUSE_ptr_I_PU8
/* NOT #define XTNOUSE_SysAddr*/
/* NOT #define XTNOUSE_SysHdr*/
/* NOT #define XTNOUSE_ApplHdr*/
/* NOT #define XTNOUSE_DummyMsg*/
/* NOT #define XTNOUSE_InstCounterTbl*/
/* NOT #define XTNOUSE_InstMapTbl*/
/* NOT #define XTNOUSE_InstLclPidMapTbl*/
/* NOT #define XTNOUSE_Key1*/
/* NOT #define XTNOUSE_Key2*/
/* NOT #define XTNOUSE_Key3*/
/* NOT #define XTNOUSE_SearchKeyForAlocInst*/
/* NOT #define XTNOUSE_Query00001IdKey*/
/* NOT #define XTNOUSE_Query00010IdKey*/
/* NOT #define XTNOUSE_Query00011IdKey*/
/* NOT #define XTNOUSE_Query00100IdKey*/
/* NOT #define XTNOUSE_Query00101IdKey*/
/* NOT #define XTNOUSE_Query00110IdKey*/
/* NOT #define XTNOUSE_Query00111IdKey*/
/* NOT #define XTNOUSE_Query01000IdKey*/
/* NOT #define XTNOUSE_Query01001IdKey*/
/* NOT #define XTNOUSE_Query01010IdKey*/
/* NOT #define XTNOUSE_Query01011IdKey*/
/* NOT #define XTNOUSE_Query01100IdKey*/
/* NOT #define XTNOUSE_Query01101IdKey*/
/* NOT #define XTNOUSE_Query01110IdKey*/
/* NOT #define XTNOUSE_Query01111IdKey*/
/* NOT #define XTNOUSE_Query10000IdKey*/
/* NOT #define XTNOUSE_Query10001IdKey*/
/* NOT #define XTNOUSE_Query10010IdKey*/
/* NOT #define XTNOUSE_Query10011IdKey*/
/* NOT #define XTNOUSE_Query10100IdKey*/
/* NOT #define XTNOUSE_Query10101IdKey*/
/* NOT #define XTNOUSE_Query10110IdKey*/
/* NOT #define XTNOUSE_Query10111IdKey*/
/* NOT #define XTNOUSE_Query11000IdKey*/
/* NOT #define XTNOUSE_Query11001IdKey*/
/* NOT #define XTNOUSE_Query11010IdKey*/
/* NOT #define XTNOUSE_Query11011IdKey*/
/* NOT #define XTNOUSE_Query11100IdKey*/
/* NOT #define XTNOUSE_Query11101IdKey*/
/* NOT #define XTNOUSE_Query11110IdKey*/
/* NOT #define XTNOUSE_Query11111IdKey*/
/* NOT #define XTNOUSE_InstCounterKey*/
/* NOT #define XTNOUSE_InstGetUpdateKey*/
/* NOT #define XTNOUSE_InstGetUpdateKeyUpd*/
#define XTNOUSE_ptr_CPtr_CpIU8V
#define XTNOUSE_ptr_CPtr_CpIS8V
#define XTNOUSE_ptr_CPtr_CpIS32V
/* NOT #define XTNOUSE_ptr_CPtr_CpIU32V*/
#define XTNOUSE_ptr_CPtr_CpIU16V
/* NOT #define XTNOUSE_TmplInst_CArr1IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr5IU32V*/
#define XTNOUSE_ptr_SysAddr
#define XTNOUSE_ptr_SysHdr
#define XTNOUSE_ptr_ApplHdr
#define XTNOUSE_ptr_DummyMsg
#define XTNOUSE_ptr_InstCounterTbl
#define XTNOUSE_ptr_InstMapTbl
#define XTNOUSE_ptr_InstLclPidMapTbl
#define XTNOUSE_ptr_Key1
#define XTNOUSE_ptr_Key2
#define XTNOUSE_ptr_Key3
#define XTNOUSE_ptr_SearchKeyForAlocInst
#define XTNOUSE_ptr_Query00001IdKey
#define XTNOUSE_ptr_Query00010IdKey
#define XTNOUSE_ptr_Query00011IdKey
#define XTNOUSE_ptr_Query00100IdKey
#define XTNOUSE_ptr_Query00101IdKey
#define XTNOUSE_ptr_Query00110IdKey
#define XTNOUSE_ptr_Query00111IdKey
#define XTNOUSE_ptr_Query01000IdKey
#define XTNOUSE_ptr_Query01001IdKey
#define XTNOUSE_ptr_Query01010IdKey
#define XTNOUSE_ptr_Query01011IdKey
#define XTNOUSE_ptr_Query01100IdKey
#define XTNOUSE_ptr_Query01101IdKey
#define XTNOUSE_ptr_Query01110IdKey
#define XTNOUSE_ptr_Query01111IdKey
#define XTNOUSE_ptr_Query10000IdKey
#define XTNOUSE_ptr_Query10001IdKey
#define XTNOUSE_ptr_Query10010IdKey
#define XTNOUSE_ptr_Query10011IdKey
#define XTNOUSE_ptr_Query10100IdKey
#define XTNOUSE_ptr_Query10101IdKey
#define XTNOUSE_ptr_Query10110IdKey
#define XTNOUSE_ptr_Query10111IdKey
#define XTNOUSE_ptr_Query11000IdKey
#define XTNOUSE_ptr_Query11001IdKey
#define XTNOUSE_ptr_Query11010IdKey
#define XTNOUSE_ptr_Query11011IdKey
#define XTNOUSE_ptr_Query11100IdKey
#define XTNOUSE_ptr_Query11101IdKey
#define XTNOUSE_ptr_Query11110IdKey
#define XTNOUSE_ptr_Query11111IdKey
#define XTNOUSE_ptr_InstCounterKey
#define XTNOUSE_ptr_InstGetUpdateKey
#define XTNOUSE_ptr_InstGetUpdateKeyUpd
#define XTNOUSE_I_CHAR
/* NOT #define XTNOUSE_I_U8*/
/* NOT #define XTNOUSE_I_S8*/
/* NOT #define XTNOUSE_I_U16*/
/* NOT #define XTNOUSE_I_S16*/
/* NOT #define XTNOUSE_I_U32*/
/* NOT #define XTNOUSE_I_S32*/
#define XTNOUSE_I_UL32
#define XTNOUSE_I_SL32
/* NOT #define XTNOUSE_I_Bool*/
#define XTNOUSE_I_Octet
#define XTNOUSE_I_PVoid
#define XTNOUSE_I_PPVoid
#define XTNOUSE_I_PU8
#define XTNOUSE_CPtr_CpIU8V_SYSInclude
#define XTNOUSE_CPtr_CpIS8V_SYSInclude
#define XTNOUSE_CPtr_CpIS32V
#define XTNOUSE_CPtr_CpIU32V_SYSInclude
#define XTNOUSE_CPtr_CpIU16V_SYSInclude
#define XTNOUSE_CPtr_CpInstMapTblV
/* NOT #define XTNOUSE_BssTableIndices*/
/* NOT #define XTNOUSE_BssTableApi*/
/* NOT #define XTNOUSE_CellPerTableIndices*/
/* NOT #define XTNOUSE_CellPerTableSecIndices*/
/* NOT #define XTNOUSE_CellPerTableTerIndices*/
/* NOT #define XTNOUSE_CellPerTableApi*/
/* NOT #define XTNOUSE_CellNonPerTableIndices*/
/* NOT #define XTNOUSE_CellNonPerTableSecIndices*/
/* NOT #define XTNOUSE_CellNonPerTableTerIndices*/
/* NOT #define XTNOUSE_CellNonPerTableApi*/
/* NOT #define XTNOUSE_PsCellTableIndices*/
/* NOT #define XTNOUSE_PsCellTableApi*/
/* NOT #define XTNOUSE_CsExternalCellTableIndices*/
/* NOT #define XTNOUSE_CsExternalCellTableApi*/
/* NOT #define XTNOUSE_PsExternalCellTableIndices*/
/* NOT #define XTNOUSE_PsExternalCellTableApi*/
/* NOT #define XTNOUSE_LaTableIndices*/
/* NOT #define XTNOUSE_LaTableApi*/
/* NOT #define XTNOUSE_RaTableIndices*/
/* NOT #define XTNOUSE_RaTableApi*/
/* NOT #define XTNOUSE_ChnGrpTableIndices*/
/* NOT #define XTNOUSE_ChnGrpTableSecIndices*/
/* NOT #define XTNOUSE_ChnGrpTableApi*/
/* NOT #define XTNOUSE_PtrxTableIndices*/
/* NOT #define XTNOUSE_PtrxTableApi*/
/* NOT #define XTNOUSE_E1PerTableIndices*/
/* NOT #define XTNOUSE_E1PerTableSecIndices*/
/* NOT #define XTNOUSE_E1PerTableTerIndices*/
/* NOT #define XTNOUSE_E1PerTableApi*/
/* NOT #define XTNOUSE_E1NonPerTableIndices*/
/* NOT #define XTNOUSE_E1NonPerTableApi*/
/* NOT #define XTNOUSE_AbisTimeSlotPerTableIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotPerTableSecIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotPerTableTerIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotPerTableApi*/
/* NOT #define XTNOUSE_AbisTimeSlotNonPerTableIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotNonPerTableSecIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotNonPerTableTerIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotNonPerTableApi*/
/* NOT #define XTNOUSE_CsNeighCellsTableIndices*/
/* NOT #define XTNOUSE_CsNeighCellsTableSecIndices*/
/* NOT #define XTNOUSE_CsNeighCellsTableTerIndices*/
/* NOT #define XTNOUSE_CsNeighCellsTableApi*/
/* NOT #define XTNOUSE_PsNeighCellsTableIndices*/
/* NOT #define XTNOUSE_PsNeighCellsTableSecIndices*/
/* NOT #define XTNOUSE_PsNeighCellsTableTerIndices*/
/* NOT #define XTNOUSE_PsNeighCellsTableApi*/
/* NOT #define XTNOUSE_ArfcnListTableIndices*/
/* NOT #define XTNOUSE_ArfcnListTableApi*/
/* NOT #define XTNOUSE_AInterfaceTableIndices*/
/* NOT #define XTNOUSE_AInterfaceTableApi*/
/* NOT #define XTNOUSE_SksGenConfigTableIndices*/
/* NOT #define XTNOUSE_SksGenConfigTableApi*/
/* NOT #define XTNOUSE_LinksetTableIndices*/
/* NOT #define XTNOUSE_LinksetTableApi*/
/* NOT #define XTNOUSE_LinksetStatusTableIndices*/
/* NOT #define XTNOUSE_LinksetStatusTableApi*/
/* NOT #define XTNOUSE_Ss7RouteTableIndices*/
/* NOT #define XTNOUSE_Ss7RouteTableApi*/
/* NOT #define XTNOUSE_LinkTableIndices*/
/* NOT #define XTNOUSE_LinkTableSecIndices*/
/* NOT #define XTNOUSE_LinkTableTerIndices*/
/* NOT #define XTNOUSE_LinkTableApi*/
/* NOT #define XTNOUSE_LinkStatusTableIndices*/
/* NOT #define XTNOUSE_LinkStatusTableApi*/
/* NOT #define XTNOUSE_LapdOperationalStatusTableIndices*/
/* NOT #define XTNOUSE_LapdOperationalStatusTableApi*/
/* NOT #define XTNOUSE_PcuTableIndices*/
/* NOT #define XTNOUSE_PcuTableApi*/
/* NOT #define XTNOUSE_GbInterfaceTableIndices*/
/* NOT #define XTNOUSE_GbInterfaceTableApi*/
/* NOT #define XTNOUSE_NsvcTableIndices*/
/* NOT #define XTNOUSE_NsvcTableSecIndices*/
/* NOT #define XTNOUSE_NsvcTableApi*/
/* NOT #define XTNOUSE_FrLinkTableIndices*/
/* NOT #define XTNOUSE_FrLinkTableApi*/
/* NOT #define XTNOUSE_LepInfoTableIndices*/
/* NOT #define XTNOUSE_LepInfoTableApi*/
/* NOT #define XTNOUSE_RepInfoTableIndices*/
/* NOT #define XTNOUSE_RepInfoTableApi*/
/* NOT #define XTNOUSE_RlcMacConfigTableIndices*/
/* NOT #define XTNOUSE_RlcMacConfigTableApi*/
/* NOT #define XTNOUSE_CardStateChangeTableIndices*/
/* NOT #define XTNOUSE_CardStateChangeTableApi*/
/* NOT #define XTNOUSE_SystemTypeTableIndices*/
/* NOT #define XTNOUSE_SystemTypeTableApi*/
/* NOT #define XTNOUSE_ChasisFrameIdTableIndices*/
/* NOT #define XTNOUSE_ChasisFrameIdTableApi*/
/* NOT #define XTNOUSE_IccCardInfoTableIndices*/
/* NOT #define XTNOUSE_IccCardInfoTableSecIndices*/
/* NOT #define XTNOUSE_IccCardInfoTableApi*/
/* NOT #define XTNOUSE_PowerSupplyInfoTableIndices*/
/* NOT #define XTNOUSE_PowerSupplyInfoTableApi*/
/* NOT #define XTNOUSE_EicCardInfoTableIndices*/
/* NOT #define XTNOUSE_EicCardInfoTableApi*/
/* NOT #define XTNOUSE_DspInfoTableIndices*/
/* NOT #define XTNOUSE_DspInfoTableApi*/
/* NOT #define XTNOUSE_ClkSourceConfigTableIndices*/
/* NOT #define XTNOUSE_ClkSourceConfigTableApi*/
/* NOT #define XTNOUSE_SystemClkInfoTableIndices*/
/* NOT #define XTNOUSE_SystemClkInfoTableApi*/
/* NOT #define XTNOUSE_TrunkPortTableIndices*/
/* NOT #define XTNOUSE_TrunkPortTableSecIndices*/
/* NOT #define XTNOUSE_TrunkPortTableTerIndices*/
/* NOT #define XTNOUSE_TrunkPortTableApi*/
/* NOT #define XTNOUSE_SysOmcRegisterTableIndices*/
/* NOT #define XTNOUSE_SysOmcRegisterTableApi*/
/* NOT #define XTNOUSE_SysOmcConfigTableIndices*/
/* NOT #define XTNOUSE_SysOmcConfigTableApi*/
/* NOT #define XTNOUSE_ActiveAlarmListTableIndices*/
/* NOT #define XTNOUSE_ActiveAlarmListTableApi*/
/* NOT #define XTNOUSE_PtdcConfigTableIndices*/
/* NOT #define XTNOUSE_PtdcConfigTableApi*/
/* NOT #define XTNOUSE_TrauOprStsTableIndices*/
/* NOT #define XTNOUSE_TrauOprStsTableApi*/
/* NOT #define XTNOUSE_CsPwrCtrlTableIndices*/
/* NOT #define XTNOUSE_CsPwrCtrlTableApi*/
/* NOT #define XTNOUSE_HoCtrlTableIndices*/
/* NOT #define XTNOUSE_HoCtrlTableApi*/
/* NOT #define XTNOUSE_BicTableIndices*/
/* NOT #define XTNOUSE_BicTableSecIndices*/
/* NOT #define XTNOUSE_BicTableApi*/
/* NOT #define XTNOUSE_TrxTableIndices*/
/* NOT #define XTNOUSE_TrxTableSecIndices*/
/* NOT #define XTNOUSE_TrxTableTerIndices*/
/* NOT #define XTNOUSE_TrxTableApi*/
/* NOT #define XTNOUSE_SwMTableIndices*/
/* NOT #define XTNOUSE_SwMTableSecIndices*/
/* NOT #define XTNOUSE_SwMTableApi*/
/* NOT #define XTNOUSE_SwMOfferTableIndices*/
/* NOT #define XTNOUSE_SwMOfferTableApi*/
/* NOT #define XTNOUSE_SwMNodeTableIndices*/
/* NOT #define XTNOUSE_SwMNodeTableSecIndices*/
/* NOT #define XTNOUSE_SwMNodeTableTerIndices*/
/* NOT #define XTNOUSE_SwMNodeTableApi*/
/* NOT #define XTNOUSE_BicStatusTableIndices*/
/* NOT #define XTNOUSE_BicStatusTableApi*/
/* NOT #define XTNOUSE_BicTrxTimeslotUsageTableIndices*/
/* NOT #define XTNOUSE_BicTrxTimeslotUsageTableSecIndices*/
/* NOT #define XTNOUSE_BicTrxTimeslotUsageTableTerIndices*/
/* NOT #define XTNOUSE_BicTrxTimeslotUsageTableApi*/
/* NOT #define XTNOUSE_TrauUlFrameStatusTableIndices*/
/* NOT #define XTNOUSE_TrauUlFrameStatusTableApi*/
/* NOT #define XTNOUSE_RadioTimeslotTableIndices*/
/* NOT #define XTNOUSE_RadioTimeslotTableSecIndices*/
/* NOT #define XTNOUSE_RadioTimeslotTableApi*/
/* NOT #define XTNOUSE_LtrxTableIndices*/
/* NOT #define XTNOUSE_LtrxTableSecIndices*/
/* NOT #define XTNOUSE_LtrxTableTerIndices*/
/* NOT #define XTNOUSE_LtrxTableApi*/
/* NOT #define XTNOUSE_TrxTsTeiTableIndices*/
/* NOT #define XTNOUSE_TrxTsTeiTableSecIndices*/
/* NOT #define XTNOUSE_TrxTsTeiTableTerIndices*/
/* NOT #define XTNOUSE_TrxTsTeiTableApi*/
/* NOT #define XTNOUSE_BicE1TeiMapTableIndices*/
/* NOT #define XTNOUSE_BicE1TeiMapTableSecIndices*/
/* NOT #define XTNOUSE_BicE1TeiMapTableTerIndices*/
/* NOT #define XTNOUSE_BicE1TeiMapTableApi*/
/* NOT #define XTNOUSE_CsAppBssPmTableIndices*/
/* NOT #define XTNOUSE_CsAppBssPmTableApi*/
/* NOT #define XTNOUSE_CsAppCellPmTableIndices*/
/* NOT #define XTNOUSE_CsAppCellPmTableApi*/
/* NOT #define XTNOUSE_PsAppBssPmTableIndices*/
/* NOT #define XTNOUSE_PsAppBssPmTableApi*/
/* NOT #define XTNOUSE_PsAppCellPmTableIndices*/
/* NOT #define XTNOUSE_PsAppCellPmTableApi*/
/* NOT #define XTNOUSE_GbNsStackPmTableIndices*/
/* NOT #define XTNOUSE_GbNsStackPmTableApi*/
/* NOT #define XTNOUSE_GbBssGpStackPmTableIndices*/
/* NOT #define XTNOUSE_GbBssGpStackPmTableApi*/
/* NOT #define XTNOUSE_GbBssGpStackCellPmTableIndices*/
/* NOT #define XTNOUSE_GbBssGpStackCellPmTableApi*/
/* NOT #define XTNOUSE_RlcMacStackGenPmTableIndices*/
/* NOT #define XTNOUSE_RlcMacStackGenPmTableApi*/
/* NOT #define XTNOUSE_RlcMacStackCellPmTableIndices*/
/* NOT #define XTNOUSE_RlcMacStackCellPmTableApi*/
/* NOT #define XTNOUSE_LapdCsStackPmTableIndices*/
/* NOT #define XTNOUSE_LapdCsStackPmTableApi*/
/* NOT #define XTNOUSE_BssapGenPegsTableIndices*/
/* NOT #define XTNOUSE_BssapGenPegsTableApi*/
/* NOT #define XTNOUSE_Mtp3LinkPegsTableIndices*/
/* NOT #define XTNOUSE_Mtp3LinkPegsTableApi*/
/* NOT #define XTNOUSE_Mtp3RoutePegsTableIndices*/
/* NOT #define XTNOUSE_Mtp3RoutePegsTableApi*/
/* NOT #define XTNOUSE_Mtp3GenPegsTableIndices*/
/* NOT #define XTNOUSE_Mtp3GenPegsTableApi*/
/* NOT #define XTNOUSE_SccpGenPegsTableIndices*/
/* NOT #define XTNOUSE_SccpGenPegsTableApi*/
/* NOT #define XTNOUSE_TrauStatusTableIndices*/
/* NOT #define XTNOUSE_TrauStatusTableApi*/
/* NOT #define XTNOUSE_TrauChannelStatusTableIndices*/
/* NOT #define XTNOUSE_TrauChannelStatusTableApi*/
/* NOT #define XTNOUSE_CsAppCellHoPmTableIndices*/
/* NOT #define XTNOUSE_CsAppCellHoPmTableApi*/
/* NOT #define XTNOUSE_CsAlgoHoPmTableIndices*/
/* NOT #define XTNOUSE_CsAlgoHoPmTableApi*/
/* NOT #define XTNOUSE_SysDspTableIndices*/
/* NOT #define XTNOUSE_SysDspTableApi*/
/* NOT #define XTNOUSE_SysI2cTableIndices*/
/* NOT #define XTNOUSE_SysI2cTableApi*/
/* NOT #define XTNOUSE_SysPpEthTableIndices*/
/* NOT #define XTNOUSE_SysPpEthTableApi*/
/* NOT #define XTNOUSE_SysCpEthTableIndices*/
/* NOT #define XTNOUSE_SysCpEthTableApi*/
/* NOT #define XTNOUSE_SysFramerTrunkTableIndices*/
/* NOT #define XTNOUSE_SysFramerTrunkTableApi*/
/* NOT #define XTNOUSE_SysOsCpTableIndices*/
/* NOT #define XTNOUSE_SysOsCpTableApi*/
/* NOT #define XTNOUSE_SysOsPpTableIndices*/
/* NOT #define XTNOUSE_SysOsPpTableApi*/
/* NOT #define XTNOUSE_SysApplProcTableIndices*/
/* NOT #define XTNOUSE_SysApplProcTableApi*/
/* NOT #define XTNOUSE_SysProtoProcTableIndices*/
/* NOT #define XTNOUSE_SysProtoProcTableApi*/
/* NOT #define XTNOUSE_DspTrauResourcePreconfiguredTableIndices*/
/* NOT #define XTNOUSE_DspTrauResourcePreconfiguredTableSecIndices*/
/* NOT #define XTNOUSE_DspTrauResourcePreconfiguredTableTerIndices*/
/* NOT #define XTNOUSE_DspTrauResourcePreconfiguredTableApi*/
/* NOT #define XTNOUSE_TrauConfigTableIndices*/
/* NOT #define XTNOUSE_TrauConfigTableApi*/
/* NOT #define XTNOUSE_E1StreamMapTableIndices*/
/* NOT #define XTNOUSE_E1StreamMapTableApi*/
/* NOT #define XTNOUSE_SiPreconfigTableIndices*/
/* NOT #define XTNOUSE_SiPreconfigTableApi*/
/* NOT #define XTNOUSE_SccpTimerTableIndices*/
/* NOT #define XTNOUSE_SccpTimerTableApi*/
/* NOT #define XTNOUSE_Mtp3TimerTableIndices*/
/* NOT #define XTNOUSE_Mtp3TimerTableApi*/
/* NOT #define XTNOUSE_BssgpTimerTableIndices*/
/* NOT #define XTNOUSE_BssgpTimerTableApi*/
/* NOT #define XTNOUSE_NsTimerTableIndices*/
/* NOT #define XTNOUSE_NsTimerTableApi*/
/* NOT #define XTNOUSE_RlcMacPreConfigTableIndices*/
/* NOT #define XTNOUSE_RlcMacPreConfigTableApi*/
/* NOT #define XTNOUSE_LapdTimerTableIndices*/
/* NOT #define XTNOUSE_LapdTimerTableApi*/
/* NOT #define XTNOUSE_LapdSAPIConfigTableIndices*/
/* NOT #define XTNOUSE_LapdSAPIConfigTableApi*/
/* NOT #define XTNOUSE_LapdTSConfigTableIndices*/
/* NOT #define XTNOUSE_LapdTSConfigTableApi*/
/* NOT #define XTNOUSE_LapdTEIConfigTableIndices*/
/* NOT #define XTNOUSE_LapdTEIConfigTableApi*/
/* NOT #define XTNOUSE_SccpBehaviorConfigTableIndices*/
/* NOT #define XTNOUSE_SccpBehaviorConfigTableApi*/
/* NOT #define XTNOUSE_BssapTimerTableIndices*/
/* NOT #define XTNOUSE_BssapTimerTableApi*/
/* NOT #define XTNOUSE_StaticalarmconfigurationTableIndices*/
/* NOT #define XTNOUSE_StaticalarmconfigurationTableApi*/
/* NOT #define XTNOUSE_FrConfigurationTableIndices*/
/* NOT #define XTNOUSE_FrConfigurationTableApi*/
/* NOT #define XTNOUSE_PsMaximumConfigurationTableIndices*/
/* NOT #define XTNOUSE_PsMaximumConfigurationTableApi*/
/* NOT #define XTNOUSE_BssCsPreConfigTableIndices*/
/* NOT #define XTNOUSE_BssCsPreConfigTableApi*/
/* NOT #define XTNOUSE_BssPsPreConfigTableIndices*/
/* NOT #define XTNOUSE_BssPsPreConfigTableApi*/
/* NOT #define XTNOUSE_CsPwrCtrlPreconfigTableIndices*/
/* NOT #define XTNOUSE_CsPwrCtrlPreconfigTableApi*/
/* NOT #define XTNOUSE_HoCtrlPreconfigTableIndices*/
/* NOT #define XTNOUSE_HoCtrlPreconfigTableApi*/
/* NOT #define XTNOUSE_BicTrxTsTableIndices*/
/* NOT #define XTNOUSE_BicTrxTsTableApi*/
/* NOT #define XTNOUSE_InFrameTrxE1TsTableIndices*/
/* NOT #define XTNOUSE_InFrameTrxE1TsTableApi*/
/* NOT #define XTNOUSE_AbisE1TsMccE1TsMapTableIndices*/
/* NOT #define XTNOUSE_AbisE1TsMccE1TsMapTableApi*/
/* NOT #define XTNOUSE_SwMPreconfigTableIndices*/
/* NOT #define XTNOUSE_SwMPreconfigTableApi*/
/* NOT #define XTNOUSE_MsContextTableIndices*/
/* NOT #define XTNOUSE_MsContextTableApi*/
/* NOT #define XTNOUSE_RmContextTableIndices*/
/* NOT #define XTNOUSE_RmContextTableSecIndices*/
/* NOT #define XTNOUSE_RmContextTableApi*/
/* NOT #define XTNOUSE_BscPerformanceCounterTableIndices*/
/* NOT #define XTNOUSE_BscPerformanceCounterTableApi*/
/* NOT #define XTNOUSE_TimerValueTableIndices*/
/* NOT #define XTNOUSE_TimerValueTableApi*/
/* NOT #define XTNOUSE_MessageQTableIndices*/
/* NOT #define XTNOUSE_MessageQTableSecIndices*/
/* NOT #define XTNOUSE_MessageQTableApi*/
/* NOT #define XTNOUSE_CellPerfCounterTableIndices*/
/* NOT #define XTNOUSE_CellPerfCounterTableApi*/
/* NOT #define XTNOUSE_ChannelParamsTableIndices*/
/* NOT #define XTNOUSE_ChannelParamsTableSecIndices*/
/* NOT #define XTNOUSE_ChannelParamsTableApi*/
/* NOT #define XTNOUSE_ChannelUsageTableIndices*/
/* NOT #define XTNOUSE_ChannelUsageTableSecIndices*/
/* NOT #define XTNOUSE_ChannelUsageTableTerIndices*/
/* NOT #define XTNOUSE_ChannelUsageTableApi*/
/* NOT #define XTNOUSE_AllocationAllowedTableIndices*/
/* NOT #define XTNOUSE_AllocationAllowedTableSecIndices*/
/* NOT #define XTNOUSE_AllocationAllowedTableTerIndices*/
/* NOT #define XTNOUSE_AllocationAllowedTableApi*/
/* NOT #define XTNOUSE_ObjectStateTableIndices*/
/* NOT #define XTNOUSE_ObjectStateTableSecIndices*/
/* NOT #define XTNOUSE_ObjectStateTableApi*/
/* NOT #define XTNOUSE_TrauChannelUsageTableIndices*/
/* NOT #define XTNOUSE_TrauChannelUsageTableSecIndices*/
/* NOT #define XTNOUSE_TrauChannelUsageTableTerIndices*/
/* NOT #define XTNOUSE_TrauChannelUsageTableApi*/
/* NOT #define XTNOUSE_MccTsUsageTableIndices*/
/* NOT #define XTNOUSE_MccTsUsageTableSecIndices*/
/* NOT #define XTNOUSE_MccTsUsageTableApi*/
/* NOT #define XTNOUSE_TrxHCreatedChnTableIndices*/
/* NOT #define XTNOUSE_TrxHCreatedChnTableSecIndices*/
/* NOT #define XTNOUSE_TrxHCreatedChnTableApi*/
/* NOT #define XTNOUSE_CerContextTableIndices*/
/* NOT #define XTNOUSE_CerContextTableSecIndices*/
/* NOT #define XTNOUSE_CerContextTableApi*/
/* NOT #define XTNOUSE_BcchFreqNCellTableIndices*/
/* NOT #define XTNOUSE_BcchFreqNCellTableSecIndices*/
/* NOT #define XTNOUSE_BcchFreqNCellTableApi*/
/* NOT #define XTNOUSE_BaIndCellTableIndices*/
/* NOT #define XTNOUSE_BaIndCellTableApi*/
/* NOT #define XTNOUSE_E1StatusTableIndices*/
/* NOT #define XTNOUSE_E1StatusTableApi*/
/* NOT #define XTNOUSE_Ss7RouteStatusTableIndices*/
/* NOT #define XTNOUSE_Ss7RouteStatusTableApi*/
/* NOT #define XTNOUSE_Ss7StackConfigTableIndices*/
/* NOT #define XTNOUSE_Ss7StackConfigTableApi*/
/* NOT #define XTNOUSE_MccLinkResourceTableIndices*/
/* NOT #define XTNOUSE_MccLinkResourceTableSecIndices*/
/* NOT #define XTNOUSE_MccLinkResourceTableTerIndices*/
/* NOT #define XTNOUSE_MccLinkResourceTableApi*/
/* NOT #define XTNOUSE_AifInterfaceTableIndices*/
/* NOT #define XTNOUSE_AifInterfaceTableApi*/
/* NOT #define XTNOUSE_TrunkTableIndices*/
/* NOT #define XTNOUSE_TrunkTableApi*/
/* NOT #define XTNOUSE_TrunkGroupTableIndices*/
/* NOT #define XTNOUSE_TrunkGroupTableSecIndices*/
/* NOT #define XTNOUSE_TrunkGroupTableApi*/
/* NOT #define XTNOUSE_CicTableIndices*/
/* NOT #define XTNOUSE_CicTableSecIndices*/
/* NOT #define XTNOUSE_CicTableTerIndices*/
/* NOT #define XTNOUSE_CicTableApi*/
/* NOT #define XTNOUSE_BicCcInfoTableIndices*/
/* NOT #define XTNOUSE_BicCcInfoTableApi*/
/* NOT #define XTNOUSE_CcConfigTableIndices*/
/* NOT #define XTNOUSE_CcConfigTableApi*/
/* NOT #define XTNOUSE_CcDataReqTableIndices*/
/* NOT #define XTNOUSE_CcDataReqTableApi*/
/* NOT #define XTNOUSE_BicPowerOrderTableIndices*/
/* NOT #define XTNOUSE_BicPowerOrderTableApi*/
/* NOT #define XTNOUSE_CcPowerOrderTableIndices*/
/* NOT #define XTNOUSE_CcPowerOrderTableApi*/
/* NOT #define XTNOUSE_BicCcChargingDataTableIndices*/
/* NOT #define XTNOUSE_BicCcChargingDataTableApi*/
/* NOT #define XTNOUSE_MccPeerLinkSwitchTableIndices*/
/* NOT #define XTNOUSE_MccPeerLinkSwitchTableApi*/
/* NOT #define XTNOUSE_SetNeIpAddressTableIndices*/
/* NOT #define XTNOUSE_SetNeIpAddressTableApi*/
/* NOT #define XTNOUSE_SetOmcIpAddressTableIndices*/
/* NOT #define XTNOUSE_SetOmcIpAddressTableApi*/
/* NOT #define XTNOUSE_EventListTableIndices*/
/* NOT #define XTNOUSE_EventListTableApi*/
/* NOT #define XTNOUSE_AbisTimeSlotTableIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotTableSecIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotTableTerIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotTableApi*/
/* NOT #define XTNOUSE_CellTableIndices*/
/* NOT #define XTNOUSE_CellTableSecIndices*/
/* NOT #define XTNOUSE_CellTableTerIndices*/
/* NOT #define XTNOUSE_CellTableApi*/
/* NOT #define XTNOUSE_E1TableIndices*/
/* NOT #define XTNOUSE_E1TableApi*/
/* NOT #define XTNOUSE_PlmnInfoCphm*/
/* NOT #define XTNOUSE_ResetCsAppCellPmTable*/
/* NOT #define XTNOUSE_TrxTableQuatIndices*/
/* NOT #define XTNOUSE_AbisTimeSlotPerTableSeptIndices*/
#define XTNOUSE_ptr_CPtr_CpshiV
#define XTNOUSE_ptr_CPtr_CpintV
#define XTNOUSE_ptr_CPtr_CpCpVBssTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCellPerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCellNonPerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPsCellTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsExternalCellTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPsExternalCellTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLaTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRaTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVChnGrpTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPtrxTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVE1PerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVE1NonPerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVAbisTimeSlotPerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVAbisTimeSlotNonPerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsNeighCellsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPsNeighCellsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVArfcnListTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVAInterfaceTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSksGenConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLinksetTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLinksetStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSs7RouteTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLinkTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLinkStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLapdOperationalStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPcuTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVGbInterfaceTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVNsvcTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVFrLinkTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLepInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRepInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRlcMacConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCardStateChangeTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSystemTypeTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVChasisFrameIdTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVIccCardInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPowerSupplyInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVEicCardInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVDspInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVClkSourceConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSystemClkInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrunkPortTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysOmcRegisterTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysOmcConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVActiveAlarmListTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPtdcConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrauOprStsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsPwrCtrlTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVHoCtrlTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrxTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSwMTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSwMOfferTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSwMNodeTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicTrxTimeslotUsageTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrauUlFrameStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRadioTimeslotTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLtrxTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrxTsTeiTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicE1TeiMapTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsAppBssPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsAppCellPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPsAppBssPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPsAppCellPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVGbNsStackPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVGbBssGpStackPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVGbBssGpStackCellPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRlcMacStackGenPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRlcMacStackCellPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLapdCsStackPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBssapGenPegsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMtp3LinkPegsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMtp3RoutePegsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMtp3GenPegsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSccpGenPegsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrauStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrauChannelStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsAppCellHoPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsAlgoHoPmTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysDspTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysI2cTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysPpEthTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysCpEthTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysFramerTrunkTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysOsCpTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysOsPpTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysApplProcTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSysProtoProcTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVDspTrauResourcePreconfiguredTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrauConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVE1StreamMapTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSiPreconfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSccpTimerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMtp3TimerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBssgpTimerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVNsTimerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRlcMacPreConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLapdTimerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLapdSAPIConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLapdTSConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVLapdTEIConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSccpBehaviorConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBssapTimerTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVStaticalarmconfigurationTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVFrConfigurationTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVPsMaximumConfigurationTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBssCsPreConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBssPsPreConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCsPwrCtrlPreconfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVHoCtrlPreconfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicTrxTsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVInFrameTrxE1TsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVAbisE1TsMccE1TsMapTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSwMPreconfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMsContextTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVRmContextTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBscPerformanceCounterTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTimerValueTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMessageQTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCellPerfCounterTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVChannelParamsTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVChannelUsageTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVAllocationAllowedTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVObjectStateTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrauChannelUsageTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMccTsUsageTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrxHCreatedChnTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCerContextTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBcchFreqNCellTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBaIndCellTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVE1StatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSs7RouteStatusTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSs7StackConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMccLinkResourceTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVAifInterfaceTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrunkTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVTrunkGroupTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCicTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicCcInfoTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCcConfigTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCcDataReqTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicPowerOrderTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCcPowerOrderTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVBicCcChargingDataTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVMccPeerLinkSwitchTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSetNeIpAddressTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVSetOmcIpAddressTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVEventListTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVAbisTimeSlotTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVCellTableApiV
#define XTNOUSE_ptr_CPtr_CpCpVE1TableApiV
#define XTNOUSE_ptr_CPtr_CpCpVIU32V
#define XTNOUSE_ptr_CPtr_CpCpVIU8V
#define XTNOUSE_ptr_CPtr_CpCpVCellPerTableIndicesV
/* NOT #define XTNOUSE_TmplInst_CArr20IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr150IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr25IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr128IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr32IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr64IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr40IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr8IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr11IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr14IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr3IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr3IU8V*/
#define XTNOUSE_ptr_BssTableIndices
#define XTNOUSE_ptr_BssTableApi
#define XTNOUSE_ptr_CellPerTableIndices
#define XTNOUSE_ptr_CellPerTableSecIndices
#define XTNOUSE_ptr_CellPerTableTerIndices
#define XTNOUSE_ptr_CellPerTableApi
#define XTNOUSE_ptr_CellNonPerTableIndices
#define XTNOUSE_ptr_CellNonPerTableSecIndices
#define XTNOUSE_ptr_CellNonPerTableTerIndices
#define XTNOUSE_ptr_CellNonPerTableApi
#define XTNOUSE_ptr_PsCellTableIndices
#define XTNOUSE_ptr_PsCellTableApi
#define XTNOUSE_ptr_CsExternalCellTableIndices
#define XTNOUSE_ptr_CsExternalCellTableApi
#define XTNOUSE_ptr_PsExternalCellTableIndices
#define XTNOUSE_ptr_PsExternalCellTableApi
#define XTNOUSE_ptr_LaTableIndices
#define XTNOUSE_ptr_LaTableApi
#define XTNOUSE_ptr_RaTableIndices
#define XTNOUSE_ptr_RaTableApi
#define XTNOUSE_ptr_ChnGrpTableIndices
#define XTNOUSE_ptr_ChnGrpTableSecIndices
#define XTNOUSE_ptr_ChnGrpTableApi
#define XTNOUSE_ptr_PtrxTableIndices
#define XTNOUSE_ptr_PtrxTableApi
#define XTNOUSE_ptr_E1PerTableIndices
#define XTNOUSE_ptr_E1PerTableSecIndices
#define XTNOUSE_ptr_E1PerTableTerIndices
#define XTNOUSE_ptr_E1PerTableApi
#define XTNOUSE_ptr_E1NonPerTableIndices
#define XTNOUSE_ptr_E1NonPerTableApi
#define XTNOUSE_ptr_AbisTimeSlotPerTableIndices
#define XTNOUSE_ptr_AbisTimeSlotPerTableSecIndices
#define XTNOUSE_ptr_AbisTimeSlotPerTableTerIndices
#define XTNOUSE_ptr_AbisTimeSlotPerTableApi
#define XTNOUSE_ptr_AbisTimeSlotNonPerTableIndices
#define XTNOUSE_ptr_AbisTimeSlotNonPerTableSecIndices
#define XTNOUSE_ptr_AbisTimeSlotNonPerTableTerIndices
#define XTNOUSE_ptr_AbisTimeSlotNonPerTableApi
#define XTNOUSE_ptr_CsNeighCellsTableIndices
#define XTNOUSE_ptr_CsNeighCellsTableSecIndices
#define XTNOUSE_ptr_CsNeighCellsTableTerIndices
#define XTNOUSE_ptr_CsNeighCellsTableApi
#define XTNOUSE_ptr_PsNeighCellsTableIndices
#define XTNOUSE_ptr_PsNeighCellsTableSecIndices
#define XTNOUSE_ptr_PsNeighCellsTableTerIndices
#define XTNOUSE_ptr_PsNeighCellsTableApi
#define XTNOUSE_ptr_ArfcnListTableIndices
#define XTNOUSE_ptr_ArfcnListTableApi
#define XTNOUSE_ptr_AInterfaceTableIndices
#define XTNOUSE_ptr_AInterfaceTableApi
#define XTNOUSE_ptr_SksGenConfigTableIndices
#define XTNOUSE_ptr_SksGenConfigTableApi
#define XTNOUSE_ptr_LinksetTableIndices
#define XTNOUSE_ptr_LinksetTableApi
#define XTNOUSE_ptr_LinksetStatusTableIndices
#define XTNOUSE_ptr_LinksetStatusTableApi
#define XTNOUSE_ptr_Ss7RouteTableIndices
#define XTNOUSE_ptr_Ss7RouteTableApi
#define XTNOUSE_ptr_LinkTableIndices
#define XTNOUSE_ptr_LinkTableSecIndices
#define XTNOUSE_ptr_LinkTableTerIndices
#define XTNOUSE_ptr_LinkTableApi
#define XTNOUSE_ptr_LinkStatusTableIndices
#define XTNOUSE_ptr_LinkStatusTableApi
#define XTNOUSE_ptr_LapdOperationalStatusTableIndices
#define XTNOUSE_ptr_LapdOperationalStatusTableApi
#define XTNOUSE_ptr_PcuTableIndices
#define XTNOUSE_ptr_PcuTableApi
#define XTNOUSE_ptr_GbInterfaceTableIndices
#define XTNOUSE_ptr_GbInterfaceTableApi
#define XTNOUSE_ptr_NsvcTableIndices
#define XTNOUSE_ptr_NsvcTableSecIndices
#define XTNOUSE_ptr_NsvcTableApi
#define XTNOUSE_ptr_FrLinkTableIndices
#define XTNOUSE_ptr_FrLinkTableApi
#define XTNOUSE_ptr_LepInfoTableIndices
#define XTNOUSE_ptr_LepInfoTableApi
#define XTNOUSE_ptr_RepInfoTableIndices
#define XTNOUSE_ptr_RepInfoTableApi
#define XTNOUSE_ptr_RlcMacConfigTableIndices
#define XTNOUSE_ptr_RlcMacConfigTableApi
#define XTNOUSE_ptr_CardStateChangeTableIndices
#define XTNOUSE_ptr_CardStateChangeTableApi
#define XTNOUSE_ptr_SystemTypeTableIndices
#define XTNOUSE_ptr_SystemTypeTableApi
#define XTNOUSE_ptr_ChasisFrameIdTableIndices
#define XTNOUSE_ptr_ChasisFrameIdTableApi
#define XTNOUSE_ptr_IccCardInfoTableIndices
#define XTNOUSE_ptr_IccCardInfoTableSecIndices
#define XTNOUSE_ptr_IccCardInfoTableApi
#define XTNOUSE_ptr_PowerSupplyInfoTableIndices
#define XTNOUSE_ptr_PowerSupplyInfoTableApi
#define XTNOUSE_ptr_EicCardInfoTableIndices
#define XTNOUSE_ptr_EicCardInfoTableApi
#define XTNOUSE_ptr_DspInfoTableIndices
#define XTNOUSE_ptr_DspInfoTableApi
#define XTNOUSE_ptr_ClkSourceConfigTableIndices
#define XTNOUSE_ptr_ClkSourceConfigTableApi
#define XTNOUSE_ptr_SystemClkInfoTableIndices
#define XTNOUSE_ptr_SystemClkInfoTableApi
#define XTNOUSE_ptr_TrunkPortTableIndices
#define XTNOUSE_ptr_TrunkPortTableSecIndices
#define XTNOUSE_ptr_TrunkPortTableTerIndices
#define XTNOUSE_ptr_TrunkPortTableApi
#define XTNOUSE_ptr_SysOmcRegisterTableIndices
#define XTNOUSE_ptr_SysOmcRegisterTableApi
#define XTNOUSE_ptr_SysOmcConfigTableIndices
#define XTNOUSE_ptr_SysOmcConfigTableApi
#define XTNOUSE_ptr_ActiveAlarmListTableIndices
#define XTNOUSE_ptr_ActiveAlarmListTableApi
#define XTNOUSE_ptr_PtdcConfigTableIndices
#define XTNOUSE_ptr_PtdcConfigTableApi
#define XTNOUSE_ptr_TrauOprStsTableIndices
#define XTNOUSE_ptr_TrauOprStsTableApi
#define XTNOUSE_ptr_CsPwrCtrlTableIndices
#define XTNOUSE_ptr_CsPwrCtrlTableApi
#define XTNOUSE_ptr_HoCtrlTableIndices
#define XTNOUSE_ptr_HoCtrlTableApi
#define XTNOUSE_ptr_BicTableIndices
#define XTNOUSE_ptr_BicTableSecIndices
#define XTNOUSE_ptr_BicTableApi
#define XTNOUSE_ptr_TrxTableIndices
#define XTNOUSE_ptr_TrxTableSecIndices
#define XTNOUSE_ptr_TrxTableTerIndices
#define XTNOUSE_ptr_TrxTableApi
#define XTNOUSE_ptr_SwMTableIndices
#define XTNOUSE_ptr_SwMTableSecIndices
#define XTNOUSE_ptr_SwMTableApi
#define XTNOUSE_ptr_SwMOfferTableIndices
#define XTNOUSE_ptr_SwMOfferTableApi
#define XTNOUSE_ptr_SwMNodeTableIndices
#define XTNOUSE_ptr_SwMNodeTableSecIndices
#define XTNOUSE_ptr_SwMNodeTableTerIndices
#define XTNOUSE_ptr_SwMNodeTableApi
#define XTNOUSE_ptr_BicStatusTableIndices
#define XTNOUSE_ptr_BicStatusTableApi
#define XTNOUSE_ptr_BicTrxTimeslotUsageTableIndices
#define XTNOUSE_ptr_BicTrxTimeslotUsageTableSecIndices
#define XTNOUSE_ptr_BicTrxTimeslotUsageTableTerIndices
#define XTNOUSE_ptr_BicTrxTimeslotUsageTableApi
#define XTNOUSE_ptr_TrauUlFrameStatusTableIndices
#define XTNOUSE_ptr_TrauUlFrameStatusTableApi
#define XTNOUSE_ptr_RadioTimeslotTableIndices
#define XTNOUSE_ptr_RadioTimeslotTableSecIndices
#define XTNOUSE_ptr_RadioTimeslotTableApi
#define XTNOUSE_ptr_LtrxTableIndices
#define XTNOUSE_ptr_LtrxTableSecIndices
#define XTNOUSE_ptr_LtrxTableTerIndices
#define XTNOUSE_ptr_LtrxTableApi
#define XTNOUSE_ptr_TrxTsTeiTableIndices
#define XTNOUSE_ptr_TrxTsTeiTableSecIndices
#define XTNOUSE_ptr_TrxTsTeiTableTerIndices
#define XTNOUSE_ptr_TrxTsTeiTableApi
#define XTNOUSE_ptr_BicE1TeiMapTableIndices
#define XTNOUSE_ptr_BicE1TeiMapTableSecIndices
#define XTNOUSE_ptr_BicE1TeiMapTableTerIndices
#define XTNOUSE_ptr_BicE1TeiMapTableApi
#define XTNOUSE_ptr_CsAppBssPmTableIndices
#define XTNOUSE_ptr_CsAppBssPmTableApi
#define XTNOUSE_ptr_CsAppCellPmTableIndices
#define XTNOUSE_ptr_CsAppCellPmTableApi
#define XTNOUSE_ptr_PsAppBssPmTableIndices
#define XTNOUSE_ptr_PsAppBssPmTableApi
#define XTNOUSE_ptr_PsAppCellPmTableIndices
#define XTNOUSE_ptr_PsAppCellPmTableApi
#define XTNOUSE_ptr_GbNsStackPmTableIndices
#define XTNOUSE_ptr_GbNsStackPmTableApi
#define XTNOUSE_ptr_GbBssGpStackPmTableIndices
#define XTNOUSE_ptr_GbBssGpStackPmTableApi
#define XTNOUSE_ptr_GbBssGpStackCellPmTableIndices
#define XTNOUSE_ptr_GbBssGpStackCellPmTableApi
#define XTNOUSE_ptr_RlcMacStackGenPmTableIndices
#define XTNOUSE_ptr_RlcMacStackGenPmTableApi
#define XTNOUSE_ptr_RlcMacStackCellPmTableIndices
#define XTNOUSE_ptr_RlcMacStackCellPmTableApi
#define XTNOUSE_ptr_LapdCsStackPmTableIndices
#define XTNOUSE_ptr_LapdCsStackPmTableApi
#define XTNOUSE_ptr_BssapGenPegsTableIndices
#define XTNOUSE_ptr_BssapGenPegsTableApi
#define XTNOUSE_ptr_Mtp3LinkPegsTableIndices
#define XTNOUSE_ptr_Mtp3LinkPegsTableApi
#define XTNOUSE_ptr_Mtp3RoutePegsTableIndices
#define XTNOUSE_ptr_Mtp3RoutePegsTableApi
#define XTNOUSE_ptr_Mtp3GenPegsTableIndices
#define XTNOUSE_ptr_Mtp3GenPegsTableApi
#define XTNOUSE_ptr_SccpGenPegsTableIndices
#define XTNOUSE_ptr_SccpGenPegsTableApi
#define XTNOUSE_ptr_TrauStatusTableIndices
#define XTNOUSE_ptr_TrauStatusTableApi
#define XTNOUSE_ptr_TrauChannelStatusTableIndices
#define XTNOUSE_ptr_TrauChannelStatusTableApi
#define XTNOUSE_ptr_CsAppCellHoPmTableIndices
#define XTNOUSE_ptr_CsAppCellHoPmTableApi
#define XTNOUSE_ptr_CsAlgoHoPmTableIndices
#define XTNOUSE_ptr_CsAlgoHoPmTableApi
#define XTNOUSE_ptr_SysDspTableIndices
#define XTNOUSE_ptr_SysDspTableApi
#define XTNOUSE_ptr_SysI2cTableIndices
#define XTNOUSE_ptr_SysI2cTableApi
#define XTNOUSE_ptr_SysPpEthTableIndices
#define XTNOUSE_ptr_SysPpEthTableApi
#define XTNOUSE_ptr_SysCpEthTableIndices
#define XTNOUSE_ptr_SysCpEthTableApi
#define XTNOUSE_ptr_SysFramerTrunkTableIndices
#define XTNOUSE_ptr_SysFramerTrunkTableApi
#define XTNOUSE_ptr_SysOsCpTableIndices
#define XTNOUSE_ptr_SysOsCpTableApi
#define XTNOUSE_ptr_SysOsPpTableIndices
#define XTNOUSE_ptr_SysOsPpTableApi
#define XTNOUSE_ptr_SysApplProcTableIndices
#define XTNOUSE_ptr_SysApplProcTableApi
#define XTNOUSE_ptr_SysProtoProcTableIndices
#define XTNOUSE_ptr_SysProtoProcTableApi
#define XTNOUSE_ptr_DspTrauResourcePreconfiguredTableIndices
#define XTNOUSE_ptr_DspTrauResourcePreconfiguredTableSecIndices
#define XTNOUSE_ptr_DspTrauResourcePreconfiguredTableTerIndices
#define XTNOUSE_ptr_DspTrauResourcePreconfiguredTableApi
#define XTNOUSE_ptr_TrauConfigTableIndices
#define XTNOUSE_ptr_TrauConfigTableApi
#define XTNOUSE_ptr_E1StreamMapTableIndices
#define XTNOUSE_ptr_E1StreamMapTableApi
#define XTNOUSE_ptr_SiPreconfigTableIndices
#define XTNOUSE_ptr_SiPreconfigTableApi
#define XTNOUSE_ptr_SccpTimerTableIndices
#define XTNOUSE_ptr_SccpTimerTableApi
#define XTNOUSE_ptr_Mtp3TimerTableIndices
#define XTNOUSE_ptr_Mtp3TimerTableApi
#define XTNOUSE_ptr_BssgpTimerTableIndices
#define XTNOUSE_ptr_BssgpTimerTableApi
#define XTNOUSE_ptr_NsTimerTableIndices
#define XTNOUSE_ptr_NsTimerTableApi
#define XTNOUSE_ptr_RlcMacPreConfigTableIndices
#define XTNOUSE_ptr_RlcMacPreConfigTableApi
#define XTNOUSE_ptr_LapdTimerTableIndices
#define XTNOUSE_ptr_LapdTimerTableApi
#define XTNOUSE_ptr_LapdSAPIConfigTableIndices
#define XTNOUSE_ptr_LapdSAPIConfigTableApi
#define XTNOUSE_ptr_LapdTSConfigTableIndices
#define XTNOUSE_ptr_LapdTSConfigTableApi
#define XTNOUSE_ptr_LapdTEIConfigTableIndices
#define XTNOUSE_ptr_LapdTEIConfigTableApi
#define XTNOUSE_ptr_SccpBehaviorConfigTableIndices
#define XTNOUSE_ptr_SccpBehaviorConfigTableApi
#define XTNOUSE_ptr_BssapTimerTableIndices
#define XTNOUSE_ptr_BssapTimerTableApi
#define XTNOUSE_ptr_StaticalarmconfigurationTableIndices
#define XTNOUSE_ptr_StaticalarmconfigurationTableApi
#define XTNOUSE_ptr_FrConfigurationTableIndices
#define XTNOUSE_ptr_FrConfigurationTableApi
#define XTNOUSE_ptr_PsMaximumConfigurationTableIndices
#define XTNOUSE_ptr_PsMaximumConfigurationTableApi
#define XTNOUSE_ptr_BssCsPreConfigTableIndices
#define XTNOUSE_ptr_BssCsPreConfigTableApi
#define XTNOUSE_ptr_BssPsPreConfigTableIndices
#define XTNOUSE_ptr_BssPsPreConfigTableApi
#define XTNOUSE_ptr_CsPwrCtrlPreconfigTableIndices
#define XTNOUSE_ptr_CsPwrCtrlPreconfigTableApi
#define XTNOUSE_ptr_HoCtrlPreconfigTableIndices
#define XTNOUSE_ptr_HoCtrlPreconfigTableApi
#define XTNOUSE_ptr_BicTrxTsTableIndices
#define XTNOUSE_ptr_BicTrxTsTableApi
#define XTNOUSE_ptr_InFrameTrxE1TsTableIndices
#define XTNOUSE_ptr_InFrameTrxE1TsTableApi
#define XTNOUSE_ptr_AbisE1TsMccE1TsMapTableIndices
#define XTNOUSE_ptr_AbisE1TsMccE1TsMapTableApi
#define XTNOUSE_ptr_SwMPreconfigTableIndices
#define XTNOUSE_ptr_SwMPreconfigTableApi
#define XTNOUSE_ptr_MsContextTableIndices
#define XTNOUSE_ptr_MsContextTableApi
#define XTNOUSE_ptr_RmContextTableIndices
#define XTNOUSE_ptr_RmContextTableSecIndices
#define XTNOUSE_ptr_RmContextTableApi
#define XTNOUSE_ptr_BscPerformanceCounterTableIndices
#define XTNOUSE_ptr_BscPerformanceCounterTableApi
#define XTNOUSE_ptr_TimerValueTableIndices
#define XTNOUSE_ptr_TimerValueTableApi
#define XTNOUSE_ptr_MessageQTableIndices
#define XTNOUSE_ptr_MessageQTableSecIndices
#define XTNOUSE_ptr_MessageQTableApi
#define XTNOUSE_ptr_CellPerfCounterTableIndices
#define XTNOUSE_ptr_CellPerfCounterTableApi
#define XTNOUSE_ptr_ChannelParamsTableIndices
#define XTNOUSE_ptr_ChannelParamsTableSecIndices
#define XTNOUSE_ptr_ChannelParamsTableApi
#define XTNOUSE_ptr_ChannelUsageTableIndices
#define XTNOUSE_ptr_ChannelUsageTableSecIndices
#define XTNOUSE_ptr_ChannelUsageTableTerIndices
#define XTNOUSE_ptr_ChannelUsageTableApi
#define XTNOUSE_ptr_AllocationAllowedTableIndices
#define XTNOUSE_ptr_AllocationAllowedTableSecIndices
#define XTNOUSE_ptr_AllocationAllowedTableTerIndices
#define XTNOUSE_ptr_AllocationAllowedTableApi
#define XTNOUSE_ptr_ObjectStateTableIndices
#define XTNOUSE_ptr_ObjectStateTableSecIndices
#define XTNOUSE_ptr_ObjectStateTableApi
#define XTNOUSE_ptr_TrauChannelUsageTableIndices
#define XTNOUSE_ptr_TrauChannelUsageTableSecIndices
#define XTNOUSE_ptr_TrauChannelUsageTableTerIndices
#define XTNOUSE_ptr_TrauChannelUsageTableApi
#define XTNOUSE_ptr_MccTsUsageTableIndices
#define XTNOUSE_ptr_MccTsUsageTableSecIndices
#define XTNOUSE_ptr_MccTsUsageTableApi
#define XTNOUSE_ptr_TrxHCreatedChnTableIndices
#define XTNOUSE_ptr_TrxHCreatedChnTableSecIndices
#define XTNOUSE_ptr_TrxHCreatedChnTableApi
#define XTNOUSE_ptr_CerContextTableIndices
#define XTNOUSE_ptr_CerContextTableSecIndices
#define XTNOUSE_ptr_CerContextTableApi
#define XTNOUSE_ptr_BcchFreqNCellTableIndices
#define XTNOUSE_ptr_BcchFreqNCellTableSecIndices
#define XTNOUSE_ptr_BcchFreqNCellTableApi
#define XTNOUSE_ptr_BaIndCellTableIndices
#define XTNOUSE_ptr_BaIndCellTableApi
#define XTNOUSE_ptr_E1StatusTableIndices
#define XTNOUSE_ptr_E1StatusTableApi
#define XTNOUSE_ptr_Ss7RouteStatusTableIndices
#define XTNOUSE_ptr_Ss7RouteStatusTableApi
#define XTNOUSE_ptr_Ss7StackConfigTableIndices
#define XTNOUSE_ptr_Ss7StackConfigTableApi
#define XTNOUSE_ptr_MccLinkResourceTableIndices
#define XTNOUSE_ptr_MccLinkResourceTableSecIndices
#define XTNOUSE_ptr_MccLinkResourceTableTerIndices
#define XTNOUSE_ptr_MccLinkResourceTableApi
#define XTNOUSE_ptr_AifInterfaceTableIndices
#define XTNOUSE_ptr_AifInterfaceTableApi
#define XTNOUSE_ptr_TrunkTableIndices
#define XTNOUSE_ptr_TrunkTableApi
#define XTNOUSE_ptr_TrunkGroupTableIndices
#define XTNOUSE_ptr_TrunkGroupTableSecIndices
#define XTNOUSE_ptr_TrunkGroupTableApi
#define XTNOUSE_ptr_CicTableIndices
#define XTNOUSE_ptr_CicTableSecIndices
#define XTNOUSE_ptr_CicTableTerIndices
#define XTNOUSE_ptr_CicTableApi
#define XTNOUSE_ptr_BicCcInfoTableIndices
#define XTNOUSE_ptr_BicCcInfoTableApi
#define XTNOUSE_ptr_CcConfigTableIndices
#define XTNOUSE_ptr_CcConfigTableApi
#define XTNOUSE_ptr_CcDataReqTableIndices
#define XTNOUSE_ptr_CcDataReqTableApi
#define XTNOUSE_ptr_BicPowerOrderTableIndices
#define XTNOUSE_ptr_BicPowerOrderTableApi
#define XTNOUSE_ptr_CcPowerOrderTableIndices
#define XTNOUSE_ptr_CcPowerOrderTableApi
#define XTNOUSE_ptr_BicCcChargingDataTableIndices
#define XTNOUSE_ptr_BicCcChargingDataTableApi
#define XTNOUSE_ptr_MccPeerLinkSwitchTableIndices
#define XTNOUSE_ptr_MccPeerLinkSwitchTableApi
#define XTNOUSE_ptr_SetNeIpAddressTableIndices
#define XTNOUSE_ptr_SetNeIpAddressTableApi
#define XTNOUSE_ptr_SetOmcIpAddressTableIndices
#define XTNOUSE_ptr_SetOmcIpAddressTableApi
#define XTNOUSE_ptr_EventListTableIndices
#define XTNOUSE_ptr_EventListTableApi
#define XTNOUSE_ptr_AbisTimeSlotTableIndices
#define XTNOUSE_ptr_AbisTimeSlotTableSecIndices
#define XTNOUSE_ptr_AbisTimeSlotTableTerIndices
#define XTNOUSE_ptr_AbisTimeSlotTableApi
#define XTNOUSE_ptr_CellTableIndices
#define XTNOUSE_ptr_CellTableSecIndices
#define XTNOUSE_ptr_CellTableTerIndices
#define XTNOUSE_ptr_CellTableApi
#define XTNOUSE_ptr_E1TableIndices
#define XTNOUSE_ptr_E1TableApi
#define XTNOUSE_ptr_PlmnInfoCphm
#define XTNOUSE_ptr_ResetCsAppCellPmTable
#define XTNOUSE_ptr_TrxTableQuatIndices
#define XTNOUSE_ptr_AbisTimeSlotPerTableSeptIndices
#define XTNOUSE_CPtr_CpvoidV
#define XTNOUSE_CPtr_CpshiV
#define XTNOUSE_CPtr_CpintV
#define XTNOUSE_CPtr_CpVBssTableApiV
#define XTNOUSE_CPtr_CpCpVBssTableApiV
#define XTNOUSE_CPtr_CpIU32V_DBInclude
#define XTNOUSE_CPtr_CpIU16V_DBInclude
#define XTNOUSE_CPtr_CpVCellPerTableApiV
#define XTNOUSE_CPtr_CpCpVCellPerTableApiV
#define XTNOUSE_CPtr_CpVCellNonPerTableApiV
#define XTNOUSE_CPtr_CpCpVCellNonPerTableApiV
#define XTNOUSE_CPtr_CpVPsCellTableApiV
#define XTNOUSE_CPtr_CpCpVPsCellTableApiV
#define XTNOUSE_CPtr_CpVCsExternalCellTableApiV
#define XTNOUSE_CPtr_CpCpVCsExternalCellTableApiV
#define XTNOUSE_CPtr_CpVPsExternalCellTableApiV
#define XTNOUSE_CPtr_CpCpVPsExternalCellTableApiV
#define XTNOUSE_CPtr_CpVLaTableApiV
#define XTNOUSE_CPtr_CpCpVLaTableApiV
#define XTNOUSE_CPtr_CpVRaTableApiV
#define XTNOUSE_CPtr_CpCpVRaTableApiV
#define XTNOUSE_CPtr_CpVChnGrpTableApiV
#define XTNOUSE_CPtr_CpCpVChnGrpTableApiV
#define XTNOUSE_CPtr_CpVPtrxTableApiV
#define XTNOUSE_CPtr_CpCpVPtrxTableApiV
#define XTNOUSE_CPtr_CpVE1PerTableApiV
#define XTNOUSE_CPtr_CpCpVE1PerTableApiV
#define XTNOUSE_CPtr_CpVE1NonPerTableApiV
#define XTNOUSE_CPtr_CpCpVE1NonPerTableApiV
#define XTNOUSE_CPtr_CpVAbisTimeSlotPerTableApiV
#define XTNOUSE_CPtr_CpCpVAbisTimeSlotPerTableApiV
#define XTNOUSE_CPtr_CpVAbisTimeSlotNonPerTableApiV
#define XTNOUSE_CPtr_CpCpVAbisTimeSlotNonPerTableApiV
#define XTNOUSE_CPtr_CpVCsNeighCellsTableApiV
#define XTNOUSE_CPtr_CpCpVCsNeighCellsTableApiV
#define XTNOUSE_CPtr_CpVPsNeighCellsTableApiV
#define XTNOUSE_CPtr_CpCpVPsNeighCellsTableApiV
#define XTNOUSE_CPtr_CpVArfcnListTableApiV
#define XTNOUSE_CPtr_CpCpVArfcnListTableApiV
#define XTNOUSE_CPtr_CpVAInterfaceTableApiV
#define XTNOUSE_CPtr_CpCpVAInterfaceTableApiV
#define XTNOUSE_CPtr_CpVSksGenConfigTableApiV
#define XTNOUSE_CPtr_CpCpVSksGenConfigTableApiV
#define XTNOUSE_CPtr_CpVLinksetTableApiV
#define XTNOUSE_CPtr_CpCpVLinksetTableApiV
#define XTNOUSE_CPtr_CpVLinksetStatusTableApiV
#define XTNOUSE_CPtr_CpCpVLinksetStatusTableApiV
#define XTNOUSE_CPtr_CpVSs7RouteTableApiV
#define XTNOUSE_CPtr_CpCpVSs7RouteTableApiV
#define XTNOUSE_CPtr_CpVLinkTableApiV
#define XTNOUSE_CPtr_CpCpVLinkTableApiV
#define XTNOUSE_CPtr_CpVLinkStatusTableApiV
#define XTNOUSE_CPtr_CpCpVLinkStatusTableApiV
#define XTNOUSE_CPtr_CpVLapdOperationalStatusTableApiV
#define XTNOUSE_CPtr_CpCpVLapdOperationalStatusTableApiV
#define XTNOUSE_CPtr_CpVPcuTableApiV
#define XTNOUSE_CPtr_CpCpVPcuTableApiV
#define XTNOUSE_CPtr_CpVGbInterfaceTableApiV
#define XTNOUSE_CPtr_CpCpVGbInterfaceTableApiV
#define XTNOUSE_CPtr_CpVNsvcTableApiV
#define XTNOUSE_CPtr_CpCpVNsvcTableApiV
#define XTNOUSE_CPtr_CpVFrLinkTableApiV
#define XTNOUSE_CPtr_CpCpVFrLinkTableApiV
#define XTNOUSE_CPtr_CpVLepInfoTableApiV
#define XTNOUSE_CPtr_CpCpVLepInfoTableApiV
#define XTNOUSE_CPtr_CpVRepInfoTableApiV
#define XTNOUSE_CPtr_CpCpVRepInfoTableApiV
#define XTNOUSE_CPtr_CpVRlcMacConfigTableApiV
#define XTNOUSE_CPtr_CpCpVRlcMacConfigTableApiV
#define XTNOUSE_CPtr_CpVCardStateChangeTableApiV
#define XTNOUSE_CPtr_CpCpVCardStateChangeTableApiV
#define XTNOUSE_CPtr_CpVSystemTypeTableApiV
#define XTNOUSE_CPtr_CpCpVSystemTypeTableApiV
#define XTNOUSE_CPtr_CpVChasisFrameIdTableApiV
#define XTNOUSE_CPtr_CpCpVChasisFrameIdTableApiV
#define XTNOUSE_CPtr_CpVIccCardInfoTableApiV
#define XTNOUSE_CPtr_CpCpVIccCardInfoTableApiV
#define XTNOUSE_CPtr_CpVPowerSupplyInfoTableApiV
#define XTNOUSE_CPtr_CpCpVPowerSupplyInfoTableApiV
#define XTNOUSE_CPtr_CpVEicCardInfoTableApiV
#define XTNOUSE_CPtr_CpCpVEicCardInfoTableApiV
#define XTNOUSE_CPtr_CpVDspInfoTableApiV
#define XTNOUSE_CPtr_CpCpVDspInfoTableApiV
#define XTNOUSE_CPtr_CpVClkSourceConfigTableApiV
#define XTNOUSE_CPtr_CpCpVClkSourceConfigTableApiV
#define XTNOUSE_CPtr_CpVSystemClkInfoTableApiV
#define XTNOUSE_CPtr_CpCpVSystemClkInfoTableApiV
#define XTNOUSE_CPtr_CpVTrunkPortTableApiV
#define XTNOUSE_CPtr_CpCpVTrunkPortTableApiV
#define XTNOUSE_CPtr_CpVSysOmcRegisterTableApiV
#define XTNOUSE_CPtr_CpCpVSysOmcRegisterTableApiV
#define XTNOUSE_CPtr_CpVSysOmcConfigTableApiV
#define XTNOUSE_CPtr_CpCpVSysOmcConfigTableApiV
#define XTNOUSE_CPtr_CpVActiveAlarmListTableApiV
#define XTNOUSE_CPtr_CpCpVActiveAlarmListTableApiV
#define XTNOUSE_CPtr_CpVPtdcConfigTableApiV
#define XTNOUSE_CPtr_CpCpVPtdcConfigTableApiV
#define XTNOUSE_CPtr_CpVTrauOprStsTableApiV
#define XTNOUSE_CPtr_CpCpVTrauOprStsTableApiV
#define XTNOUSE_CPtr_CpVCsPwrCtrlTableApiV
#define XTNOUSE_CPtr_CpCpVCsPwrCtrlTableApiV
#define XTNOUSE_CPtr_CpVHoCtrlTableApiV
#define XTNOUSE_CPtr_CpCpVHoCtrlTableApiV
#define XTNOUSE_CPtr_CpVBicTableApiV
#define XTNOUSE_CPtr_CpCpVBicTableApiV
#define XTNOUSE_CPtr_CpVTrxTableApiV
#define XTNOUSE_CPtr_CpCpVTrxTableApiV
#define XTNOUSE_CPtr_CpVSwMTableApiV
#define XTNOUSE_CPtr_CpCpVSwMTableApiV
#define XTNOUSE_CPtr_CpVSwMOfferTableApiV
#define XTNOUSE_CPtr_CpCpVSwMOfferTableApiV
#define XTNOUSE_CPtr_CpVSwMNodeTableApiV
#define XTNOUSE_CPtr_CpCpVSwMNodeTableApiV
#define XTNOUSE_CPtr_CpVBicStatusTableApiV
#define XTNOUSE_CPtr_CpCpVBicStatusTableApiV
#define XTNOUSE_CPtr_CpVBicTrxTimeslotUsageTableApiV
#define XTNOUSE_CPtr_CpCpVBicTrxTimeslotUsageTableApiV
#define XTNOUSE_CPtr_CpVTrauUlFrameStatusTableApiV
#define XTNOUSE_CPtr_CpCpVTrauUlFrameStatusTableApiV
#define XTNOUSE_CPtr_CpVRadioTimeslotTableApiV
#define XTNOUSE_CPtr_CpCpVRadioTimeslotTableApiV
#define XTNOUSE_CPtr_CpVLtrxTableApiV
#define XTNOUSE_CPtr_CpCpVLtrxTableApiV
#define XTNOUSE_CPtr_CpVTrxTsTeiTableApiV
#define XTNOUSE_CPtr_CpCpVTrxTsTeiTableApiV
#define XTNOUSE_CPtr_CpVBicE1TeiMapTableApiV
#define XTNOUSE_CPtr_CpCpVBicE1TeiMapTableApiV
#define XTNOUSE_CPtr_CpVCsAppBssPmTableApiV
#define XTNOUSE_CPtr_CpCpVCsAppBssPmTableApiV
#define XTNOUSE_CPtr_CpVCsAppCellPmTableApiV
#define XTNOUSE_CPtr_CpCpVCsAppCellPmTableApiV
#define XTNOUSE_CPtr_CpVPsAppBssPmTableApiV
#define XTNOUSE_CPtr_CpCpVPsAppBssPmTableApiV
#define XTNOUSE_CPtr_CpVPsAppCellPmTableApiV
#define XTNOUSE_CPtr_CpCpVPsAppCellPmTableApiV
#define XTNOUSE_CPtr_CpVGbNsStackPmTableApiV
#define XTNOUSE_CPtr_CpCpVGbNsStackPmTableApiV
#define XTNOUSE_CPtr_CpVGbBssGpStackPmTableApiV
#define XTNOUSE_CPtr_CpCpVGbBssGpStackPmTableApiV
#define XTNOUSE_CPtr_CpVGbBssGpStackCellPmTableApiV
#define XTNOUSE_CPtr_CpCpVGbBssGpStackCellPmTableApiV
#define XTNOUSE_CPtr_CpVRlcMacStackGenPmTableApiV
#define XTNOUSE_CPtr_CpCpVRlcMacStackGenPmTableApiV
#define XTNOUSE_CPtr_CpVRlcMacStackCellPmTableApiV
#define XTNOUSE_CPtr_CpCpVRlcMacStackCellPmTableApiV
#define XTNOUSE_CPtr_CpVLapdCsStackPmTableApiV
#define XTNOUSE_CPtr_CpCpVLapdCsStackPmTableApiV
#define XTNOUSE_CPtr_CpVBssapGenPegsTableApiV
#define XTNOUSE_CPtr_CpCpVBssapGenPegsTableApiV
#define XTNOUSE_CPtr_CpVMtp3LinkPegsTableApiV
#define XTNOUSE_CPtr_CpCpVMtp3LinkPegsTableApiV
#define XTNOUSE_CPtr_CpVMtp3RoutePegsTableApiV
#define XTNOUSE_CPtr_CpCpVMtp3RoutePegsTableApiV
#define XTNOUSE_CPtr_CpVMtp3GenPegsTableApiV
#define XTNOUSE_CPtr_CpCpVMtp3GenPegsTableApiV
#define XTNOUSE_CPtr_CpVSccpGenPegsTableApiV
#define XTNOUSE_CPtr_CpCpVSccpGenPegsTableApiV
#define XTNOUSE_CPtr_CpVTrauStatusTableApiV
#define XTNOUSE_CPtr_CpCpVTrauStatusTableApiV
#define XTNOUSE_CPtr_CpVTrauChannelStatusTableApiV
#define XTNOUSE_CPtr_CpCpVTrauChannelStatusTableApiV
#define XTNOUSE_CPtr_CpVCsAppCellHoPmTableApiV
#define XTNOUSE_CPtr_CpCpVCsAppCellHoPmTableApiV
#define XTNOUSE_CPtr_CpVCsAlgoHoPmTableApiV
#define XTNOUSE_CPtr_CpCpVCsAlgoHoPmTableApiV
#define XTNOUSE_CPtr_CpVSysDspTableApiV
#define XTNOUSE_CPtr_CpCpVSysDspTableApiV
#define XTNOUSE_CPtr_CpVSysI2cTableApiV
#define XTNOUSE_CPtr_CpCpVSysI2cTableApiV
#define XTNOUSE_CPtr_CpVSysPpEthTableApiV
#define XTNOUSE_CPtr_CpCpVSysPpEthTableApiV
#define XTNOUSE_CPtr_CpVSysCpEthTableApiV
#define XTNOUSE_CPtr_CpCpVSysCpEthTableApiV
#define XTNOUSE_CPtr_CpVSysFramerTrunkTableApiV
#define XTNOUSE_CPtr_CpCpVSysFramerTrunkTableApiV
#define XTNOUSE_CPtr_CpVSysOsCpTableApiV
#define XTNOUSE_CPtr_CpCpVSysOsCpTableApiV
#define XTNOUSE_CPtr_CpVSysOsPpTableApiV
#define XTNOUSE_CPtr_CpCpVSysOsPpTableApiV
#define XTNOUSE_CPtr_CpVSysApplProcTableApiV
#define XTNOUSE_CPtr_CpCpVSysApplProcTableApiV
#define XTNOUSE_CPtr_CpVSysProtoProcTableApiV
#define XTNOUSE_CPtr_CpCpVSysProtoProcTableApiV
#define XTNOUSE_CPtr_CpVDspTrauResourcePreconfiguredTableApiV
#define XTNOUSE_CPtr_CpCpVDspTrauResourcePreconfiguredTableApiV
#define XTNOUSE_CPtr_CpVTrauConfigTableApiV
#define XTNOUSE_CPtr_CpCpVTrauConfigTableApiV
#define XTNOUSE_CPtr_CpVE1StreamMapTableApiV
#define XTNOUSE_CPtr_CpCpVE1StreamMapTableApiV
#define XTNOUSE_CPtr_CpVSiPreconfigTableApiV
#define XTNOUSE_CPtr_CpCpVSiPreconfigTableApiV
#define XTNOUSE_CPtr_CpVSccpTimerTableApiV
#define XTNOUSE_CPtr_CpCpVSccpTimerTableApiV
#define XTNOUSE_CPtr_CpVMtp3TimerTableApiV
#define XTNOUSE_CPtr_CpCpVMtp3TimerTableApiV
#define XTNOUSE_CPtr_CpVBssgpTimerTableApiV
#define XTNOUSE_CPtr_CpCpVBssgpTimerTableApiV
#define XTNOUSE_CPtr_CpVNsTimerTableApiV
#define XTNOUSE_CPtr_CpCpVNsTimerTableApiV
#define XTNOUSE_CPtr_CpVRlcMacPreConfigTableApiV
#define XTNOUSE_CPtr_CpCpVRlcMacPreConfigTableApiV
#define XTNOUSE_CPtr_CpVLapdTimerTableApiV
#define XTNOUSE_CPtr_CpCpVLapdTimerTableApiV
#define XTNOUSE_CPtr_CpVLapdSAPIConfigTableApiV
#define XTNOUSE_CPtr_CpCpVLapdSAPIConfigTableApiV
#define XTNOUSE_CPtr_CpVLapdTSConfigTableApiV
#define XTNOUSE_CPtr_CpCpVLapdTSConfigTableApiV
#define XTNOUSE_CPtr_CpVLapdTEIConfigTableApiV
#define XTNOUSE_CPtr_CpCpVLapdTEIConfigTableApiV
#define XTNOUSE_CPtr_CpVSccpBehaviorConfigTableApiV
#define XTNOUSE_CPtr_CpCpVSccpBehaviorConfigTableApiV
#define XTNOUSE_CPtr_CpVBssapTimerTableApiV
#define XTNOUSE_CPtr_CpCpVBssapTimerTableApiV
#define XTNOUSE_CPtr_CpVStaticalarmconfigurationTableApiV
#define XTNOUSE_CPtr_CpCpVStaticalarmconfigurationTableApiV
#define XTNOUSE_CPtr_CpVFrConfigurationTableApiV
#define XTNOUSE_CPtr_CpCpVFrConfigurationTableApiV
#define XTNOUSE_CPtr_CpVPsMaximumConfigurationTableApiV
#define XTNOUSE_CPtr_CpCpVPsMaximumConfigurationTableApiV
#define XTNOUSE_CPtr_CpVBssCsPreConfigTableApiV
#define XTNOUSE_CPtr_CpCpVBssCsPreConfigTableApiV
#define XTNOUSE_CPtr_CpVBssPsPreConfigTableApiV
#define XTNOUSE_CPtr_CpCpVBssPsPreConfigTableApiV
#define XTNOUSE_CPtr_CpVCsPwrCtrlPreconfigTableApiV
#define XTNOUSE_CPtr_CpCpVCsPwrCtrlPreconfigTableApiV
#define XTNOUSE_CPtr_CpVHoCtrlPreconfigTableApiV
#define XTNOUSE_CPtr_CpCpVHoCtrlPreconfigTableApiV
#define XTNOUSE_CPtr_CpVBicTrxTsTableApiV
#define XTNOUSE_CPtr_CpCpVBicTrxTsTableApiV
#define XTNOUSE_CPtr_CpVInFrameTrxE1TsTableApiV
#define XTNOUSE_CPtr_CpCpVInFrameTrxE1TsTableApiV
#define XTNOUSE_CPtr_CpVAbisE1TsMccE1TsMapTableApiV
#define XTNOUSE_CPtr_CpCpVAbisE1TsMccE1TsMapTableApiV
#define XTNOUSE_CPtr_CpVSwMPreconfigTableApiV
#define XTNOUSE_CPtr_CpCpVSwMPreconfigTableApiV
#define XTNOUSE_CPtr_CpVMsContextTableApiV
#define XTNOUSE_CPtr_CpCpVMsContextTableApiV
#define XTNOUSE_CPtr_CpVRmContextTableApiV
#define XTNOUSE_CPtr_CpCpVRmContextTableApiV
#define XTNOUSE_CPtr_CpVBscPerformanceCounterTableApiV
#define XTNOUSE_CPtr_CpCpVBscPerformanceCounterTableApiV
#define XTNOUSE_CPtr_CpVTimerValueTableApiV
#define XTNOUSE_CPtr_CpCpVTimerValueTableApiV
#define XTNOUSE_CPtr_CpVMessageQTableApiV
#define XTNOUSE_CPtr_CpCpVMessageQTableApiV
#define XTNOUSE_CPtr_CpVCellPerfCounterTableApiV
#define XTNOUSE_CPtr_CpCpVCellPerfCounterTableApiV
#define XTNOUSE_CPtr_CpVChannelParamsTableApiV
#define XTNOUSE_CPtr_CpCpVChannelParamsTableApiV
#define XTNOUSE_CPtr_CpVChannelUsageTableApiV
#define XTNOUSE_CPtr_CpCpVChannelUsageTableApiV
#define XTNOUSE_CPtr_CpVAllocationAllowedTableApiV
#define XTNOUSE_CPtr_CpCpVAllocationAllowedTableApiV
#define XTNOUSE_CPtr_CpVObjectStateTableApiV
#define XTNOUSE_CPtr_CpCpVObjectStateTableApiV
#define XTNOUSE_CPtr_CpVTrauChannelUsageTableApiV
#define XTNOUSE_CPtr_CpCpVTrauChannelUsageTableApiV
#define XTNOUSE_CPtr_CpVMccTsUsageTableApiV
#define XTNOUSE_CPtr_CpCpVMccTsUsageTableApiV
#define XTNOUSE_CPtr_CpVTrxHCreatedChnTableApiV
#define XTNOUSE_CPtr_CpCpVTrxHCreatedChnTableApiV
#define XTNOUSE_CPtr_CpVCerContextTableApiV
#define XTNOUSE_CPtr_CpCpVCerContextTableApiV
#define XTNOUSE_CPtr_CpVBcchFreqNCellTableApiV
#define XTNOUSE_CPtr_CpCpVBcchFreqNCellTableApiV
#define XTNOUSE_CPtr_CpVBaIndCellTableApiV
#define XTNOUSE_CPtr_CpCpVBaIndCellTableApiV
#define XTNOUSE_CPtr_CpVE1StatusTableApiV
#define XTNOUSE_CPtr_CpCpVE1StatusTableApiV
#define XTNOUSE_CPtr_CpVSs7RouteStatusTableApiV
#define XTNOUSE_CPtr_CpCpVSs7RouteStatusTableApiV
#define XTNOUSE_CPtr_CpVSs7StackConfigTableApiV
#define XTNOUSE_CPtr_CpCpVSs7StackConfigTableApiV
#define XTNOUSE_CPtr_CpVMccLinkResourceTableApiV
#define XTNOUSE_CPtr_CpCpVMccLinkResourceTableApiV
#define XTNOUSE_CPtr_CpVAifInterfaceTableApiV
#define XTNOUSE_CPtr_CpCpVAifInterfaceTableApiV
#define XTNOUSE_CPtr_CpVTrunkTableApiV
#define XTNOUSE_CPtr_CpCpVTrunkTableApiV
#define XTNOUSE_CPtr_CpVTrunkGroupTableApiV
#define XTNOUSE_CPtr_CpCpVTrunkGroupTableApiV
#define XTNOUSE_CPtr_CpVCicTableApiV
#define XTNOUSE_CPtr_CpCpVCicTableApiV
#define XTNOUSE_CPtr_CpVBicCcInfoTableApiV
#define XTNOUSE_CPtr_CpCpVBicCcInfoTableApiV
#define XTNOUSE_CPtr_CpVCcConfigTableApiV
#define XTNOUSE_CPtr_CpCpVCcConfigTableApiV
#define XTNOUSE_CPtr_CpVCcDataReqTableApiV
#define XTNOUSE_CPtr_CpCpVCcDataReqTableApiV
#define XTNOUSE_CPtr_CpVBicPowerOrderTableApiV
#define XTNOUSE_CPtr_CpCpVBicPowerOrderTableApiV
#define XTNOUSE_CPtr_CpVCcPowerOrderTableApiV
#define XTNOUSE_CPtr_CpCpVCcPowerOrderTableApiV
#define XTNOUSE_CPtr_CpVBicCcChargingDataTableApiV
#define XTNOUSE_CPtr_CpCpVBicCcChargingDataTableApiV
#define XTNOUSE_CPtr_CpVMccPeerLinkSwitchTableApiV
#define XTNOUSE_CPtr_CpCpVMccPeerLinkSwitchTableApiV
#define XTNOUSE_CPtr_CpVSetNeIpAddressTableApiV
#define XTNOUSE_CPtr_CpCpVSetNeIpAddressTableApiV
#define XTNOUSE_CPtr_CpVSetOmcIpAddressTableApiV
#define XTNOUSE_CPtr_CpCpVSetOmcIpAddressTableApiV
#define XTNOUSE_CPtr_CpVEventListTableApiV
#define XTNOUSE_CPtr_CpCpVEventListTableApiV
#define XTNOUSE_CPtr_CpVAbisTimeSlotTableApiV
#define XTNOUSE_CPtr_CpCpVAbisTimeSlotTableApiV
#define XTNOUSE_CPtr_CpVCellTableApiV
#define XTNOUSE_CPtr_CpCpVCellTableApiV
#define XTNOUSE_CPtr_CpVE1TableApiV
#define XTNOUSE_CPtr_CpCpVE1TableApiV
#define XTNOUSE_CPtr_CpVIU32V
#define XTNOUSE_CPtr_CpCpVIU32V
#define XTNOUSE_CPtr_CpVIU8V
#define XTNOUSE_CPtr_CpCpVIU8V
#define XTNOUSE_CPtr_CpIS8V_DBInclude
#define XTNOUSE_CPtr_CpVCellPerTableIndicesV
#define XTNOUSE_CPtr_CpCpVCellPerTableIndicesV
#define XTNOUSE_CPtr_CpIU8V_DBInclude
/* NOT #define XTNOUSE_CmApplHdr*/
/* NOT #define XTNOUSE_sCmMsg*/
/* NOT #define XTNOUSE_sRegCmdHdr*/
/* NOT #define XTNOUSE_sCmRegMsg*/
/* NOT #define XTNOUSE_sApiInfo*/
/* NOT #define XTNOUSE_sTableInfo*/
/* NOT #define XTNOUSE_sElemInfo*/
/* NOT #define XTNOUSE_OamPdcMgsPerfReq*/
/* NOT #define XTNOUSE_OamMgsPdcPerfResp*/
/* NOT #define XTNOUSE_OamPdcCerReq*/
/* NOT #define XTNOUSE_OamPdcPsscmPerfReq*/
/* NOT #define XTNOUSE_OamPsscmPdcPerfResp*/
/* NOT #define XTNOUSE_OamPdcMrhmPerfReq*/
/* NOT #define XTNOUSE_CsappMrhmPdcPerfResp*/
/* NOT #define XTNOUSE_OamPdcPerfGenMsg*/
/* NOT #define XTNOUSE_SnmpPdcMsg*/
/* NOT #define XTNOUSE_SysAlarm*/
/* NOT #define XTNOUSE_OamAfhAlarmInd*/
/* NOT #define XTNOUSE_CardInfoStruct*/
/* NOT #define XTNOUSE_TrunkPortStruct*/
/* NOT #define XTNOUSE_Ny1*/
/* NOT #define XTNOUSE_ObjInstance*/
/* NOT #define XTNOUSE_AbisChannel*/
/* NOT #define XTNOUSE_AddInfo*/
/* NOT #define XTNOUSE_AddText*/
/* NOT #define XTNOUSE_AvailStatus*/
/* NOT #define XTNOUSE_BtsAirTimer*/
/* NOT #define XTNOUSE_ConFailCriterion*/
/* NOT #define XTNOUSE_FileData*/
/* NOT #define XTNOUSE_HwDes*/
/* NOT #define XTNOUSE_IfLevelBoundaries*/
/* NOT #define XTNOUSE_SiteIp*/
/* NOT #define XTNOUSE_ProbableCause*/
/* NOT #define XTNOUSE_SwDes*/
/* NOT #define XTNOUSE_CcPowerInfo*/
/* NOT #define XTNOUSE_CcData*/
/* NOT #define XTNOUSE_BicCcProtoVersion*/
/* NOT #define XTNOUSE_BicCcSerialNumber*/
/* NOT #define XTNOUSE_HwCap*/
/* NOT #define XTNOUSE_T200*/
/* NOT #define XTNOUSE_OnmProtocolVersion*/
/* NOT #define XTNOUSE_OverloadPeriod*/
/* NOT #define XTNOUSE_AlarmSeq*/
/* NOT #define XTNOUSE_StartTime*/
/* NOT #define XTNOUSE_PagingAgParams*/
/* NOT #define XTNOUSE_SysInfoList*/
/* NOT #define XTNOUSE_TrxOnmProtocolVersion*/
/* NOT #define XTNOUSE_TrxHwDes*/
/* NOT #define XTNOUSE_ProductNumber*/
/* NOT #define XTNOUSE_Location*/
/* NOT #define XTNOUSE_SerialNumber*/
/* NOT #define XTNOUSE_TrxSwCap*/
/* NOT #define XTNOUSE_BicObjInst*/
/* NOT #define XTNOUSE_BicProtoVersion*/
/* NOT #define XTNOUSE_BicHwCapability*/
/* NOT #define XTNOUSE_BicHwDescription*/
/* NOT #define XTNOUSE_BicSwCapability*/
/* NOT #define XTNOUSE_ClkSrcPortPriorityResult*/
/* NOT #define XTNOUSE_ClkSrcPortPriority*/
/* NOT #define XTNOUSE_PortVarResult*/
/* NOT #define XTNOUSE_PortVars*/
/* NOT #define XTNOUSE_Hfs*/
/* NOT #define XTNOUSE_Port*/
/* NOT #define XTNOUSE_MobileAllocation*/
/* NOT #define XTNOUSE_ChannelNeeded*/
/* NOT #define XTNOUSE_EmlppPriority*/
/* NOT #define XTNOUSE_ChannelNum*/
/* NOT #define XTNOUSE_BsPower*/
/* NOT #define XTNOUSE_AbisEncryptionInfo*/
/* NOT #define XTNOUSE_MsIdentity*/
/* NOT #define XTNOUSE_MsPower*/
/* NOT #define XTNOUSE_RequestReference*/
/* NOT #define XTNOUSE_MsPowerParam*/
/* NOT #define XTNOUSE_BsPowerParam*/
/* NOT #define XTNOUSE_CellIdForDescCGIGsm*/
/* NOT #define XTNOUSE_CellIdForDescCGIPcs*/
/* NOT #define XTNOUSE_CellIdForDescCGI*/
/* NOT #define XTNOUSE_CellIdForDescLacCI*/
/* NOT #define XTNOUSE_CellIdForDescCI*/
/* NOT #define XTNOUSE_CellIdForDescLac*/
/* NOT #define XTNOUSE_CellIdForDescLai*/
/* NOT #define XTNOUSE_CellIdForDescPlmnLacRnc*/
/* NOT #define XTNOUSE_CellIdForDescRnc*/
/* NOT #define XTNOUSE_CellIdForDescSai*/
/* NOT #define XTNOUSE_CellIdForDescLacRnc*/
/* NOT #define XTNOUSE_CellIdForDescLacRncCI*/
/* NOT #define XTNOUSE_CellIdType*/
/* NOT #define XTNOUSE_CellIdentifier*/
/* NOT #define XTNOUSE_CellIdentifierList*/
/* NOT #define XTNOUSE_Imsi*/
/* NOT #define XTNOUSE_Tmsi*/
/* NOT #define XTNOUSE_ArfcnList*/
/* NOT #define XTNOUSE_Cic*/
/* NOT #define XTNOUSE_CodecList*/
/* NOT #define XTNOUSE_TimeT*/
/* NOT #define XTNOUSE_RrResource*/
/* NOT #define XTNOUSE_FrequencyList*/
/* NOT #define XTNOUSE_AbisPort*/
/* NOT #define XTNOUSE_OamsCellhAbihmBcchInfo*/
/* NOT #define XTNOUSE_OamsCellhAbihmSacchFill*/
/* NOT #define XTNOUSE_OamsCellhMrhmCsNeighCellsChange*/
/* NOT #define XTNOUSE_OamsTrxhAbihmSetBtsAttrReq*/
/* NOT #define XTNOUSE_CsappAbihmTrxhSetBtsAttrNack*/
/* NOT #define XTNOUSE_OamsTrxhAbihmSetChanAttrReq*/
/* NOT #define XTNOUSE_CsappAbihmTrxhSetChanAttrNack*/
/* NOT #define XTNOUSE_CsappAbihmTrxhStateChangeEventReport*/
/* NOT #define XTNOUSE_CsappAbihmTrxhFailureEventReport*/
/* NOT #define XTNOUSE_OamsSwmhAbihmLoadDataInit*/
/* NOT #define XTNOUSE_CsappAbihmSwmhLoadDataInitAck*/
/* NOT #define XTNOUSE_CsappAbihmSwmhLoadDataInitNack*/
/* NOT #define XTNOUSE_OamsSwmhAbihmLoadDataSeg*/
/* NOT #define XTNOUSE_CsappAbihmSwmhLoadDataSegAck*/
/* NOT #define XTNOUSE_OamsSwmhAbihmLoadDataAbort*/
/* NOT #define XTNOUSE_CsappAbihmSwmhLoadDataAbort*/
/* NOT #define XTNOUSE_OamsSwmhAbihmLoadDataEnd*/
/* NOT #define XTNOUSE_CsappAbihmSwmhLoadDataEndAck*/
/* NOT #define XTNOUSE_CsappAbihmSwmhLoadDataEndNack*/
/* NOT #define XTNOUSE_OamsSwmhAbihmActSw*/
/* NOT #define XTNOUSE_CsappAbihmSwmhActSwNack*/
/* NOT #define XTNOUSE_CsappAbihmSwmhSwActivatedReport*/
/* NOT #define XTNOUSE_OamsCfgSwmhSwDnldReq*/
/* NOT #define XTNOUSE_OamsSwmhCfgSwDnldAck*/
/* NOT #define XTNOUSE_OamsSwmhCfgSwDnldNack*/
/* NOT #define XTNOUSE_OamsCfgSwmhSwActReq*/
/* NOT #define XTNOUSE_OamsSwmhCfgSwActAck*/
/* NOT #define XTNOUSE_OamsSwmhCfgSwActNack*/
/* NOT #define XTNOUSE_OamsTrxhSwmhTrxHello*/
/* NOT #define XTNOUSE_OamsBichSwmhBicHello*/
/* NOT #define XTNOUSE_OamsTrxhSwmhLapdLinkUp*/
/* NOT #define XTNOUSE_OamsTrxhAbihmOpStartReq*/
/* NOT #define XTNOUSE_CsappAbihmTrxhOpStartNack*/
/* NOT #define XTNOUSE_OamsTrxhAbihmOpStopReq*/
/* NOT #define XTNOUSE_CsappAbihmTrxhOpStopNack*/
/* NOT #define XTNOUSE_CsappAbihmTrxhTrxHello*/
/* NOT #define XTNOUSE_CsappAbihmTrxhLapdLinkUp*/
/* NOT #define XTNOUSE_OamsTrxhAbihmLinkEstabReq*/
/* NOT #define XTNOUSE_OamsTrxhGrhmCreChanReq*/
/* NOT #define XTNOUSE_CsappGrhmTrxhCreChanAck*/
/* NOT #define XTNOUSE_CsappGrhmTrxhCreChanNack*/
/* NOT #define XTNOUSE_OamsTrxhGrhmDelChanReq*/
/* NOT #define XTNOUSE_CsappGrhmTrxhDelChanAck*/
/* NOT #define XTNOUSE_OamsTrxhPcuPdchAvail*/
/* NOT #define XTNOUSE_OamsTrxhPsscmTrxAvail*/
/* NOT #define XTNOUSE_OamsCfgGrhmLockReq*/
/* NOT #define XTNOUSE_OamsCfgGrhmUnlockReq*/
/* NOT #define XTNOUSE_OamsCfgGrhmStartChanAlloc*/
/* NOT #define XTNOUSE_OamsCfgGrhmStopChanAlloc*/
/* NOT #define XTNOUSE_CsappGrhmCfgLockResp*/
/* NOT #define XTNOUSE_CsappGrhmCfgUnlockResp*/
/* NOT #define XTNOUSE_CsappGrhmCfgUnlockFail*/
/* NOT #define XTNOUSE_CsappGrhmCfgAlarmInd*/
/* NOT #define XTNOUSE_CsappMrhmCfgAlarmInd*/
/* NOT #define XTNOUSE_OamsCfgMrhmCellDelete*/
/* NOT #define XTNOUSE_OamsCfgPcuUnlockReq*/
/* NOT #define XTNOUSE_PsappPcuCfgUnlockResp*/
/* NOT #define XTNOUSE_OamsCfgPcuLockReq*/
/* NOT #define XTNOUSE_PsappPcuCfgLockResp*/
/* NOT #define XTNOUSE_PsappPcuCfgAlarmInd*/
/* NOT #define XTNOUSE_OamsCfgPcuCellShutdownInd*/
/* NOT #define XTNOUSE_OamsCfgPcuCellEnabledReq*/
/* NOT #define XTNOUSE_OamsCfgPcuCellEnabledResp*/
/* NOT #define XTNOUSE_OamsCfgPcuFirstNsvcEnabledReq*/
/* NOT #define XTNOUSE_OamsCfgPcuFirstNsvcEnabledResp*/
/* NOT #define XTNOUSE_OamsCfgPcuAllNsvcDisabledReq*/
/* NOT #define XTNOUSE_OamsCfgPcuAllNsvcDisabledReqResp*/
/* NOT #define XTNOUSE_OamsCfgPcuBvcResetReq*/
/* NOT #define XTNOUSE_PsappPcuCfgBvcResetResp*/
/* NOT #define XTNOUSE_OamsCfgScmLockReq*/
/* NOT #define XTNOUSE_OamsCfgScmUnlockReq*/
/* NOT #define XTNOUSE_OamsScmCfgLockResp*/
/* NOT #define XTNOUSE_OamsScmCfgUnlockResp*/
/* NOT #define XTNOUSE_OamsCfgScmCfgAlarmInd*/
/* NOT #define XTNOUSE_OamsCfgPsscmUnlockReq*/
/* NOT #define XTNOUSE_OamsCfgPsscmLockReq*/
/* NOT #define XTNOUSE_OamsCfgPsscmNsvcResetReq*/
/* NOT #define XTNOUSE_PsappPsscmCfgUnlockResp*/
/* NOT #define XTNOUSE_PsappPsscmCfgLockResp*/
/* NOT #define XTNOUSE_OamsCfgPsscmNsvcResetResp*/
/* NOT #define XTNOUSE_PsappPsscmCfgAlarmInd*/
/* NOT #define XTNOUSE_OamsCfgPsscmReviveIpLinkReq*/
/* NOT #define XTNOUSE_OamsCfgPsscmReviveIpLinkResp*/
/* NOT #define XTNOUSE_PsappPsscmCfgLepEnabled*/
/* NOT #define XTNOUSE_BscApiSetGbInterfaceTable*/
/* NOT #define XTNOUSE_BscApiDelGbInterfaceTable*/
/* NOT #define XTNOUSE_BscApiSetNsvcTable*/
/* NOT #define XTNOUSE_BscApiDelNsvcTable*/
/* NOT #define XTNOUSE_BscApiSetFrLinkTable*/
/* NOT #define XTNOUSE_BscApiDelFrLinkTable*/
/* NOT #define XTNOUSE_BscApiSetLepInfoTable*/
/* NOT #define XTNOUSE_BscApiDelLepInfoTable*/
/* NOT #define XTNOUSE_BscApiSetRepInfoTable*/
/* NOT #define XTNOUSE_BscApiDelRepInfoTable*/
/* NOT #define XTNOUSE_OilCfgTrauStatusInd*/
/* NOT #define XTNOUSE_OamsCfgOilSwOfferReq*/
/* NOT #define XTNOUSE_OamsCfgOilSwActReq*/
/* NOT #define XTNOUSE_OamsCfgOilSwDelReq*/
/* NOT #define XTNOUSE_OamsCfgOilAvailableReleasesReq*/
/* NOT #define XTNOUSE_OamOilCfgSwOfferResp*/
/* NOT #define XTNOUSE_OamOilCfgSwActResp*/
/* NOT #define XTNOUSE_OamOilCfgSwDelResp*/
/* NOT #define XTNOUSE_OamOilCfgAvailableReleasesResp*/
/* NOT #define XTNOUSE_OamsCfgTrxhAddTrxReq*/
/* NOT #define XTNOUSE_OamsTrxhCfgAddTrxResp*/
/* NOT #define XTNOUSE_OamsCfgBichAddBicReq*/
/* NOT #define XTNOUSE_OamsBichCfgAddBicResp*/
/* NOT #define XTNOUSE_OamsCfgBichDelBicReq*/
/* NOT #define XTNOUSE_OamsBichCfgDelBicResp*/
/* NOT #define XTNOUSE_OamsCfgTrxhDelTrxReq*/
/* NOT #define XTNOUSE_OamsTrxhCfgDelTrxResp*/
/* NOT #define XTNOUSE_OamsCfgBichInitAbisE1*/
/* NOT #define XTNOUSE_OamsCfgBichUpdateAbisE1*/
/* NOT #define XTNOUSE_CsappAbihmBichBicHello*/
/* NOT #define XTNOUSE_CsappAbihmBichDsLinkEst*/
/* NOT #define XTNOUSE_CsappAbihmBichDsLinkFail*/
/* NOT #define XTNOUSE_BicSlotConnectMap*/
/* NOT #define XTNOUSE_OamsBichAbihmSlotConnect*/
/* NOT #define XTNOUSE_OamsBichAbihmSlotDisConnect*/
/* NOT #define XTNOUSE_CsappAbihmBichLapdLinkUp*/
/* NOT #define XTNOUSE_OamsCfgGrhmSwitchConnect*/
/* NOT #define XTNOUSE_CsappGrhmCfgSwitchConnectAck*/
/* NOT #define XTNOUSE_CsappGrhmCfgSwitchConnectNack*/
/* NOT #define XTNOUSE_OamsCfgGrhmSwitchDisconnect*/
/* NOT #define XTNOUSE_CfgPdcTrauUlFrameStatus*/
/* NOT #define XTNOUSE_OamsCfgOilE1EnableReq*/
/* NOT #define XTNOUSE_OamOilCfgE1EnableResp*/
/* NOT #define XTNOUSE_OamsCfgOilSetClkSrcReq*/
/* NOT #define XTNOUSE_OamOilCfgSetClkSrcResp*/
/* NOT #define XTNOUSE_OamOilCfgSystemTypeDetails*/
/* NOT #define XTNOUSE_OamOilCfgChasisFrameDetails*/
/* NOT #define XTNOUSE_OamOilCfgSystemClockDetails*/
/* NOT #define XTNOUSE_OamOilCfgTrunkPortDetails*/
/* NOT #define XTNOUSE_OamOilCfgEicCardDetail*/
/* NOT #define XTNOUSE_OamOilCfgDspObjDetails*/
/* NOT #define XTNOUSE_OamsCfgOilCardInfoReq*/
/* NOT #define XTNOUSE_OamsCfgOilSetClkPortIdReq*/
/* NOT #define XTNOUSE_OamOilCfgSetClkPortIdResp*/
/* NOT #define XTNOUSE_OamOilCfgIccCardResp*/
/* NOT #define XTNOUSE_OamOilCfgNodeInfo*/
/* NOT #define XTNOUSE_OamOilCfgInfoAvailableVersion*/
/* NOT #define XTNOUSE_OamOilCfgInfoSwDwnldResult*/
/* NOT #define XTNOUSE_OamOilCfgInfoSwActResult*/
/* NOT #define XTNOUSE_OamOilCfgInfoDelResult*/
/* NOT #define XTNOUSE_OamOilCfgInfoUpgradeOffer*/
/* NOT #define XTNOUSE_OamOilCfgInfoSwAct*/
/* NOT #define XTNOUSE_OamsCfgOilBpmDbInit*/
/* NOT #define XTNOUSE_OamsCfgOilTrunkPortDetailReq*/
/* NOT #define XTNOUSE_OamsCfgOilDspObjDetailReq*/
/* NOT #define XTNOUSE_OamsCfgOilSysClkDetailReq*/
/* NOT #define XTNOUSE_OamsCfgOilSystemTypeDetailReq*/
/* NOT #define XTNOUSE_OamsCfgOilSetCardOperState*/
/* NOT #define XTNOUSE_OamsOilCfgSetCardOperStateResult*/
/* NOT #define XTNOUSE_CsappAbihmCcuhBicBscAlarmInd*/
/* NOT #define XTNOUSE_OamsCcuhAbihmBicCcInfoReq*/
/* NOT #define XTNOUSE_OamPdcCcuhBicCcInfoReq*/
/* NOT #define XTNOUSE_CsappAbihmCcuhBicCcInfoResp*/
/* NOT #define XTNOUSE_OamsCcuhAbihmBicSetCcCfgReq*/
/* NOT #define XTNOUSE_OamsCfgCcuhBicSetCcCfgReq*/
/* NOT #define XTNOUSE_CsappAbihmCcuhBicSetCcCfgResp*/
/* NOT #define XTNOUSE_OamsCcuhAbihmBicGetCcCfgReq*/
/* NOT #define XTNOUSE_CsappAbihmCcuhBicGetCcCfgResp*/
/* NOT #define XTNOUSE_OamsCcuhAbihmBicCcPwrOrderReq*/
/* NOT #define XTNOUSE_OamsCfgCcuhBicCcPwrOrderReq*/
/* NOT #define XTNOUSE_OamsCcuhAbihmBicCcDataReq*/
/* NOT #define XTNOUSE_OamsCfgCcuhBicCcDataReq*/
/* NOT #define XTNOUSE_CsappAbihmCcuhBicCcDataResp*/
/* NOT #define XTNOUSE_CsappAbihmCcuhBicCcDataNack*/
/* NOT #define XTNOUSE_OamsCfgAfhSysAlarm*/
/* NOT #define XTNOUSE_OamsCfgCellhLockReq*/
/* NOT #define XTNOUSE_OamsCfgCellhUnlockReq*/
/* NOT #define XTNOUSE_OamsCfgCellhCellBarAccess*/
/* NOT #define XTNOUSE_OamsCfgCellhShutdownInd*/
/* NOT #define XTNOUSE_OamsCellhCfgUnlockResp*/
/* NOT #define XTNOUSE_OamsCellhCfgLockResp*/
/* NOT #define XTNOUSE_OamsCellhCfgAlarmInd*/
/* NOT #define XTNOUSE_OamsCfgCellhCsNeighCellsChange*/
/* NOT #define XTNOUSE_OamsCfgCellhAbisE1UnlockReq*/
/* NOT #define XTNOUSE_OamsCfgCellhAbisE1LockReq*/
/* NOT #define XTNOUSE_OamsCellhCfgAbisE1LockResp*/
/* NOT #define XTNOUSE_OamsCellhCfgAbisE1UnlockResp*/
/* NOT #define XTNOUSE_OamsCfgTrxhLockReq*/
/* NOT #define XTNOUSE_OamsTrxhCfgLockResp*/
/* NOT #define XTNOUSE_OamsCfgTrxhUnlockReq*/
/* NOT #define XTNOUSE_OamsTrxhCfgUnlockResp*/
/* NOT #define XTNOUSE_OamsTrxhCfgAlarmInd*/
/* NOT #define XTNOUSE_OamsTrxhMapentInitiateMap*/
/* NOT #define XTNOUSE_OamsMapentTrxhCreLtrxPtrxMappingReq*/
/* NOT #define XTNOUSE_OamsTrxhMapentCreLtrxPtrxMappingResp*/
/* NOT #define XTNOUSE_OamsTrxhMapentCreLtrxPtrxMappingFailed*/
/* NOT #define XTNOUSE_OamsTrxhMapentDelLtrxPtrxMappingResp*/
/* NOT #define XTNOUSE_OamsMapentTrxhDelLtrxPtrxMappingReq*/
/* NOT #define XTNOUSE_OamsTrxhCellhBcchAvail*/
/* NOT #define XTNOUSE_OamsTrxhCellhBcchUnAvail*/
/* NOT #define XTNOUSE_OamsCellhMapentCreMapReq*/
/* NOT #define XTNOUSE_OamsCellhMapentDelMapReq*/
/* NOT #define XTNOUSE_OamsMapentCellhDelMapResp*/
/* NOT #define XTNOUSE_OamsTrxhCellhSendSacchInfo*/
/* NOT #define XTNOUSE_OamsSwmhCfgAlarmInd*/
/* NOT #define XTNOUSE_TmplInst_CArr0IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr100IU8V_OamInclude*/
/* NOT #define XTNOUSE_TmplInst_CArr256IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr240IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr10IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr10IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr40IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr25IU8V_OamInclude*/
/* NOT #define XTNOUSE_TmplInst_CArr15IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr4IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr18IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr16CellIdTypeV*/
/* NOT #define XTNOUSE_TmplInst_CArr18IU16V*/
/* NOT #define XTNOUSE_TmplInst_CArr50IU8V*/
/* NOT #define XTNOUSE_TmplInst_CArr32IU32V*/
/* NOT #define XTNOUSE_TmplInst_CArr32IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr5CArrV25IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr5CArrV128IS8V*/
/* NOT #define XTNOUSE_TmplInst_CArr10BicIdentifierV*/
/* NOT #define XTNOUSE_TmplInst_CArr0BicSlotConnectMapR*/
/* NOT #define XTNOUSE_TmplInst_CArr40PortVarsR*/
/* NOT #define XTNOUSE_TmplInst_CArr40PortVarResultR*/
/* NOT #define XTNOUSE_TmplInst_CArr5ClkSrcPortPriorityR*/
/* NOT #define XTNOUSE_TmplInst_CArr5ClkSrcPortPriorityResultR*/
/* NOT #define XTNOUSE_TmplInst_CArr8IU32V*/
#define XTNOUSE_ptr_CmApplHdr
#define XTNOUSE_ptr_sCmMsg
#define XTNOUSE_ptr_sRegCmdHdr
#define XTNOUSE_ptr_sCmRegMsg
#define XTNOUSE_ptr_sApiInfo
#define XTNOUSE_ptr_sTableInfo
#define XTNOUSE_ptr_sElemInfo
#define XTNOUSE_ptr_OamPdcMgsPerfReq
#define XTNOUSE_ptr_OamMgsPdcPerfResp
#define XTNOUSE_ptr_OamPdcCerReq
#define XTNOUSE_ptr_OamPdcPsscmPerfReq
#define XTNOUSE_ptr_OamPsscmPdcPerfResp
#define XTNOUSE_ptr_OamPdcMrhmPerfReq
#define XTNOUSE_ptr_CsappMrhmPdcPerfResp
#define XTNOUSE_ptr_OamPdcPerfGenMsg
#define XTNOUSE_ptr_SnmpPdcMsg
#define XTNOUSE_ptr_SysAlarm
#define XTNOUSE_ptr_OamAfhAlarmInd
#define XTNOUSE_ptr_CardInfoStruct
#define XTNOUSE_ptr_TrunkPortStruct
#define XTNOUSE_ptr_ObjInstance
#define XTNOUSE_ptr_AbisChannel
#define XTNOUSE_ptr_AddInfo
#define XTNOUSE_ptr_AddText
#define XTNOUSE_ptr_AvailStatus
#define XTNOUSE_ptr_BtsAirTimer
#define XTNOUSE_ptr_ConFailCriterion
#define XTNOUSE_ptr_FileData
#define XTNOUSE_ptr_HwDes
#define XTNOUSE_ptr_IfLevelBoundaries
#define XTNOUSE_ptr_SiteIp
#define XTNOUSE_ptr_ProbableCause
/* NOT #define XTNOUSE_ptr_SwDes*/
/* NOT #define XTNOUSE_ptr_CcPowerInfo*/
#define XTNOUSE_ptr_CcData
/* NOT #define XTNOUSE_ptr_BicCcProtoVersion*/
/* NOT #define XTNOUSE_ptr_BicCcSerialNumber*/
#define XTNOUSE_ptr_HwCap
#define XTNOUSE_ptr_T200
#define XTNOUSE_ptr_OnmProtocolVersion
#define XTNOUSE_ptr_OverloadPeriod
#define XTNOUSE_ptr_AlarmSeq
#define XTNOUSE_ptr_StartTime
#define XTNOUSE_ptr_PagingAgParams
#define XTNOUSE_ptr_SysInfoList
#define XTNOUSE_ptr_TrxOnmProtocolVersion
#define XTNOUSE_ptr_TrxHwDes
#define XTNOUSE_ptr_ProductNumber
#define XTNOUSE_ptr_Location
#define XTNOUSE_ptr_SerialNumber
#define XTNOUSE_ptr_TrxSwCap
#define XTNOUSE_ptr_BicObjInst
#define XTNOUSE_ptr_BicProtoVersion
#define XTNOUSE_ptr_BicHwCapability
#define XTNOUSE_ptr_BicHwDescription
#define XTNOUSE_ptr_BicSwCapability
#define XTNOUSE_ptr_ClkSrcPortPriorityResult
#define XTNOUSE_ptr_ClkSrcPortPriority
#define XTNOUSE_ptr_PortVarResult
#define XTNOUSE_ptr_PortVars
#define XTNOUSE_ptr_Hfs
#define XTNOUSE_ptr_Port
#define XTNOUSE_ptr_MobileAllocation
#define XTNOUSE_ptr_ChannelNeeded
#define XTNOUSE_ptr_EmlppPriority
#define XTNOUSE_ptr_ChannelNum
#define XTNOUSE_ptr_BsPower
#define XTNOUSE_ptr_AbisEncryptionInfo
#define XTNOUSE_ptr_MsIdentity
#define XTNOUSE_ptr_MsPower
#define XTNOUSE_ptr_RequestReference
#define XTNOUSE_ptr_MsPowerParam
#define XTNOUSE_ptr_BsPowerParam
#define XTNOUSE_ptr_CellIdForDescCGIGsm
#define XTNOUSE_ptr_CellIdForDescCGIPcs
#define XTNOUSE_ptr_CellIdForDescCGI
#define XTNOUSE_ptr_CellIdForDescLacCI
#define XTNOUSE_ptr_CellIdForDescCI
#define XTNOUSE_ptr_CellIdForDescLac
#define XTNOUSE_ptr_CellIdForDescLai
#define XTNOUSE_ptr_CellIdForDescPlmnLacRnc
#define XTNOUSE_ptr_CellIdForDescRnc
#define XTNOUSE_ptr_CellIdForDescSai
#define XTNOUSE_ptr_CellIdForDescLacRnc
#define XTNOUSE_ptr_CellIdForDescLacRncCI
#define XTNOUSE_ptr_CellIdentifier
#define XTNOUSE_ptr_CellIdentifierList
#define XTNOUSE_ptr_Imsi
#define XTNOUSE_ptr_Tmsi
#define XTNOUSE_ptr_ArfcnList
#define XTNOUSE_ptr_Cic
#define XTNOUSE_ptr_CodecList
#define XTNOUSE_ptr_TimeT
#define XTNOUSE_ptr_RrResource
#define XTNOUSE_ptr_FrequencyList
#define XTNOUSE_ptr_AbisPort
#define XTNOUSE_ptr_OamsCellhAbihmBcchInfo
#define XTNOUSE_ptr_OamsCellhAbihmSacchFill
#define XTNOUSE_ptr_OamsCellhMrhmCsNeighCellsChange
#define XTNOUSE_ptr_OamsTrxhAbihmSetBtsAttrReq
#define XTNOUSE_ptr_CsappAbihmTrxhSetBtsAttrNack
#define XTNOUSE_ptr_OamsTrxhAbihmSetChanAttrReq
#define XTNOUSE_ptr_CsappAbihmTrxhSetChanAttrNack
#define XTNOUSE_ptr_CsappAbihmTrxhStateChangeEventReport
#define XTNOUSE_ptr_CsappAbihmTrxhFailureEventReport
#define XTNOUSE_ptr_OamsSwmhAbihmLoadDataInit
#define XTNOUSE_ptr_CsappAbihmSwmhLoadDataInitAck
#define XTNOUSE_ptr_CsappAbihmSwmhLoadDataInitNack
#define XTNOUSE_ptr_OamsSwmhAbihmLoadDataSeg
#define XTNOUSE_ptr_CsappAbihmSwmhLoadDataSegAck
#define XTNOUSE_ptr_OamsSwmhAbihmLoadDataAbort
#define XTNOUSE_ptr_CsappAbihmSwmhLoadDataAbort
#define XTNOUSE_ptr_OamsSwmhAbihmLoadDataEnd
#define XTNOUSE_ptr_CsappAbihmSwmhLoadDataEndAck
#define XTNOUSE_ptr_CsappAbihmSwmhLoadDataEndNack
#define XTNOUSE_ptr_OamsSwmhAbihmActSw
#define XTNOUSE_ptr_CsappAbihmSwmhActSwNack
#define XTNOUSE_ptr_CsappAbihmSwmhSwActivatedReport
#define XTNOUSE_ptr_OamsCfgSwmhSwDnldReq
#define XTNOUSE_ptr_OamsSwmhCfgSwDnldAck
#define XTNOUSE_ptr_OamsSwmhCfgSwDnldNack
#define XTNOUSE_ptr_OamsCfgSwmhSwActReq
#define XTNOUSE_ptr_OamsSwmhCfgSwActAck
#define XTNOUSE_ptr_OamsSwmhCfgSwActNack
#define XTNOUSE_ptr_OamsTrxhSwmhTrxHello
#define XTNOUSE_ptr_OamsBichSwmhBicHello
#define XTNOUSE_ptr_OamsTrxhSwmhLapdLinkUp
#define XTNOUSE_ptr_OamsTrxhAbihmOpStartReq
#define XTNOUSE_ptr_CsappAbihmTrxhOpStartNack
#define XTNOUSE_ptr_OamsTrxhAbihmOpStopReq
#define XTNOUSE_ptr_CsappAbihmTrxhOpStopNack
#define XTNOUSE_ptr_CsappAbihmTrxhTrxHello
#define XTNOUSE_ptr_CsappAbihmTrxhLapdLinkUp
#define XTNOUSE_ptr_OamsTrxhAbihmLinkEstabReq
#define XTNOUSE_ptr_OamsTrxhGrhmCreChanReq
#define XTNOUSE_ptr_CsappGrhmTrxhCreChanAck
#define XTNOUSE_ptr_CsappGrhmTrxhCreChanNack
#define XTNOUSE_ptr_OamsTrxhGrhmDelChanReq
#define XTNOUSE_ptr_CsappGrhmTrxhDelChanAck
#define XTNOUSE_ptr_OamsTrxhPcuPdchAvail
#define XTNOUSE_ptr_OamsTrxhPsscmTrxAvail
#define XTNOUSE_ptr_OamsCfgGrhmLockReq
#define XTNOUSE_ptr_OamsCfgGrhmUnlockReq
#define XTNOUSE_ptr_OamsCfgGrhmStartChanAlloc
#define XTNOUSE_ptr_OamsCfgGrhmStopChanAlloc
#define XTNOUSE_ptr_CsappGrhmCfgLockResp
#define XTNOUSE_ptr_CsappGrhmCfgUnlockResp
#define XTNOUSE_ptr_CsappGrhmCfgUnlockFail
#define XTNOUSE_ptr_CsappGrhmCfgAlarmInd
#define XTNOUSE_ptr_CsappMrhmCfgAlarmInd
#define XTNOUSE_ptr_OamsCfgMrhmCellDelete
#define XTNOUSE_ptr_OamsCfgPcuUnlockReq
#define XTNOUSE_ptr_PsappPcuCfgUnlockResp
#define XTNOUSE_ptr_OamsCfgPcuLockReq
#define XTNOUSE_ptr_PsappPcuCfgLockResp
#define XTNOUSE_ptr_PsappPcuCfgAlarmInd
#define XTNOUSE_ptr_OamsCfgPcuCellShutdownInd
#define XTNOUSE_ptr_OamsCfgPcuCellEnabledReq
#define XTNOUSE_ptr_OamsCfgPcuCellEnabledResp
#define XTNOUSE_ptr_OamsCfgPcuFirstNsvcEnabledReq
#define XTNOUSE_ptr_OamsCfgPcuFirstNsvcEnabledResp
#define XTNOUSE_ptr_OamsCfgPcuAllNsvcDisabledReq
#define XTNOUSE_ptr_OamsCfgPcuAllNsvcDisabledReqResp
#define XTNOUSE_ptr_OamsCfgPcuBvcResetReq
#define XTNOUSE_ptr_PsappPcuCfgBvcResetResp
#define XTNOUSE_ptr_OamsCfgScmLockReq
#define XTNOUSE_ptr_OamsCfgScmUnlockReq
#define XTNOUSE_ptr_OamsScmCfgLockResp
#define XTNOUSE_ptr_OamsScmCfgUnlockResp
#define XTNOUSE_ptr_OamsCfgScmCfgAlarmInd
#define XTNOUSE_ptr_OamsCfgPsscmUnlockReq
#define XTNOUSE_ptr_OamsCfgPsscmLockReq
#define XTNOUSE_ptr_OamsCfgPsscmNsvcResetReq
#define XTNOUSE_ptr_PsappPsscmCfgUnlockResp
#define XTNOUSE_ptr_PsappPsscmCfgLockResp
#define XTNOUSE_ptr_OamsCfgPsscmNsvcResetResp
#define XTNOUSE_ptr_PsappPsscmCfgAlarmInd
#define XTNOUSE_ptr_OamsCfgPsscmReviveIpLinkReq
#define XTNOUSE_ptr_OamsCfgPsscmReviveIpLinkResp
#define XTNOUSE_ptr_PsappPsscmCfgLepEnabled
#define XTNOUSE_ptr_BscApiSetGbInterfaceTable
#define XTNOUSE_ptr_BscApiDelGbInterfaceTable
#define XTNOUSE_ptr_BscApiSetNsvcTable
#define XTNOUSE_ptr_BscApiDelNsvcTable
#define XTNOUSE_ptr_BscApiSetFrLinkTable
#define XTNOUSE_ptr_BscApiDelFrLinkTable
#define XTNOUSE_ptr_BscApiSetLepInfoTable
#define XTNOUSE_ptr_BscApiDelLepInfoTable
#define XTNOUSE_ptr_BscApiSetRepInfoTable
#define XTNOUSE_ptr_BscApiDelRepInfoTable
#define XTNOUSE_ptr_OilCfgTrauStatusInd
#define XTNOUSE_ptr_OamsCfgOilSwOfferReq
#define XTNOUSE_ptr_OamsCfgOilSwActReq
#define XTNOUSE_ptr_OamsCfgOilSwDelReq
#define XTNOUSE_ptr_OamsCfgOilAvailableReleasesReq
#define XTNOUSE_ptr_OamOilCfgSwOfferResp
#define XTNOUSE_ptr_OamOilCfgSwActResp
#define XTNOUSE_ptr_OamOilCfgSwDelResp
#define XTNOUSE_ptr_OamOilCfgAvailableReleasesResp
#define XTNOUSE_ptr_OamsCfgTrxhAddTrxReq
#define XTNOUSE_ptr_OamsTrxhCfgAddTrxResp
#define XTNOUSE_ptr_OamsCfgBichAddBicReq
#define XTNOUSE_ptr_OamsBichCfgAddBicResp
#define XTNOUSE_ptr_OamsCfgBichDelBicReq
#define XTNOUSE_ptr_OamsBichCfgDelBicResp
#define XTNOUSE_ptr_OamsCfgTrxhDelTrxReq
#define XTNOUSE_ptr_OamsTrxhCfgDelTrxResp
#define XTNOUSE_ptr_OamsCfgBichInitAbisE1
#define XTNOUSE_ptr_OamsCfgBichUpdateAbisE1
#define XTNOUSE_ptr_CsappAbihmBichBicHello
#define XTNOUSE_ptr_CsappAbihmBichDsLinkEst
#define XTNOUSE_ptr_CsappAbihmBichDsLinkFail
#define XTNOUSE_ptr_BicSlotConnectMap
#define XTNOUSE_ptr_OamsBichAbihmSlotConnect
#define XTNOUSE_ptr_OamsBichAbihmSlotDisConnect
#define XTNOUSE_ptr_CsappAbihmBichLapdLinkUp
#define XTNOUSE_ptr_OamsCfgGrhmSwitchConnect
#define XTNOUSE_ptr_CsappGrhmCfgSwitchConnectAck
#define XTNOUSE_ptr_CsappGrhmCfgSwitchConnectNack
#define XTNOUSE_ptr_OamsCfgGrhmSwitchDisconnect
#define XTNOUSE_ptr_CfgPdcTrauUlFrameStatus
#define XTNOUSE_ptr_OamsCfgOilE1EnableReq
#define XTNOUSE_ptr_OamOilCfgE1EnableResp
#define XTNOUSE_ptr_OamsCfgOilSetClkSrcReq
#define XTNOUSE_ptr_OamOilCfgSetClkSrcResp
#define XTNOUSE_ptr_OamOilCfgSystemTypeDetails
#define XTNOUSE_ptr_OamOilCfgChasisFrameDetails
#define XTNOUSE_ptr_OamOilCfgSystemClockDetails
#define XTNOUSE_ptr_OamOilCfgTrunkPortDetails
#define XTNOUSE_ptr_OamOilCfgEicCardDetail
#define XTNOUSE_ptr_OamOilCfgDspObjDetails
#define XTNOUSE_ptr_OamsCfgOilCardInfoReq
#define XTNOUSE_ptr_OamsCfgOilSetClkPortIdReq
#define XTNOUSE_ptr_OamOilCfgSetClkPortIdResp
#define XTNOUSE_ptr_OamOilCfgIccCardResp
#define XTNOUSE_ptr_OamOilCfgNodeInfo
#define XTNOUSE_ptr_OamOilCfgInfoAvailableVersion
#define XTNOUSE_ptr_OamOilCfgInfoSwDwnldResult
#define XTNOUSE_ptr_OamOilCfgInfoSwActResult
#define XTNOUSE_ptr_OamOilCfgInfoDelResult
#define XTNOUSE_ptr_OamOilCfgInfoUpgradeOffer
#define XTNOUSE_ptr_OamOilCfgInfoSwAct
#define XTNOUSE_ptr_OamsCfgOilBpmDbInit
#define XTNOUSE_ptr_OamsCfgOilTrunkPortDetailReq
#define XTNOUSE_ptr_OamsCfgOilDspObjDetailReq
#define XTNOUSE_ptr_OamsCfgOilSysClkDetailReq
#define XTNOUSE_ptr_OamsCfgOilSystemTypeDetailReq
#define XTNOUSE_ptr_OamsCfgOilSetCardOperState
#define XTNOUSE_ptr_OamsOilCfgSetCardOperStateResult
#define XTNOUSE_ptr_CsappAbihmCcuhBicBscAlarmInd
#define XTNOUSE_ptr_OamsCcuhAbihmBicCcInfoReq
#define XTNOUSE_ptr_OamPdcCcuhBicCcInfoReq
#define XTNOUSE_ptr_CsappAbihmCcuhBicCcInfoResp
#define XTNOUSE_ptr_OamsCcuhAbihmBicSetCcCfgReq
#define XTNOUSE_ptr_OamsCfgCcuhBicSetCcCfgReq
#define XTNOUSE_ptr_CsappAbihmCcuhBicSetCcCfgResp
#define XTNOUSE_ptr_OamsCcuhAbihmBicGetCcCfgReq
#define XTNOUSE_ptr_CsappAbihmCcuhBicGetCcCfgResp
#define XTNOUSE_ptr_OamsCcuhAbihmBicCcPwrOrderReq
#define XTNOUSE_ptr_OamsCfgCcuhBicCcPwrOrderReq
#define XTNOUSE_ptr_OamsCcuhAbihmBicCcDataReq
#define XTNOUSE_ptr_OamsCfgCcuhBicCcDataReq
#define XTNOUSE_ptr_CsappAbihmCcuhBicCcDataResp
#define XTNOUSE_ptr_CsappAbihmCcuhBicCcDataNack
#define XTNOUSE_ptr_OamsCfgAfhSysAlarm
#define XTNOUSE_ptr_OamsCfgCellhLockReq
#define XTNOUSE_ptr_OamsCfgCellhUnlockReq
#define XTNOUSE_ptr_OamsCfgCellhCellBarAccess
#define XTNOUSE_ptr_OamsCfgCellhShutdownInd
#define XTNOUSE_ptr_OamsCellhCfgUnlockResp
#define XTNOUSE_ptr_OamsCellhCfgLockResp
#define XTNOUSE_ptr_OamsCellhCfgAlarmInd
#define XTNOUSE_ptr_OamsCfgCellhCsNeighCellsChange
#define XTNOUSE_ptr_OamsCfgCellhAbisE1UnlockReq
#define XTNOUSE_ptr_OamsCfgCellhAbisE1LockReq
#define XTNOUSE_ptr_OamsCellhCfgAbisE1LockResp
#define XTNOUSE_ptr_OamsCellhCfgAbisE1UnlockResp
#define XTNOUSE_ptr_OamsCfgTrxhLockReq
#define XTNOUSE_ptr_OamsTrxhCfgLockResp
#define XTNOUSE_ptr_OamsCfgTrxhUnlockReq
#define XTNOUSE_ptr_OamsTrxhCfgUnlockResp
#define XTNOUSE_ptr_OamsTrxhCfgAlarmInd
#define XTNOUSE_ptr_OamsTrxhMapentInitiateMap
#define XTNOUSE_ptr_OamsMapentTrxhCreLtrxPtrxMappingReq
#define XTNOUSE_ptr_OamsTrxhMapentCreLtrxPtrxMappingResp
#define XTNOUSE_ptr_OamsTrxhMapentCreLtrxPtrxMappingFailed
#define XTNOUSE_ptr_OamsTrxhMapentDelLtrxPtrxMappingResp
#define XTNOUSE_ptr_OamsMapentTrxhDelLtrxPtrxMappingReq
#define XTNOUSE_ptr_OamsTrxhCellhBcchAvail
#define XTNOUSE_ptr_OamsTrxhCellhBcchUnAvail
#define XTNOUSE_ptr_OamsCellhMapentCreMapReq
#define XTNOUSE_ptr_OamsCellhMapentDelMapReq
#define XTNOUSE_ptr_OamsMapentCellhDelMapResp
#define XTNOUSE_ptr_OamsTrxhCellhSendSacchInfo
#define XTNOUSE_ptr_OamsSwmhCfgAlarmInd
/* NOT #define XTNOUSE_PlacementInd*/
/* NOT #define XTNOUSE_SeqNum*/
/* NOT #define XTNOUSE_ObjClass*/
/* NOT #define XTNOUSE_BcchArfcn*/
/* NOT #define XTNOUSE_Bsic*/
/* NOT #define XTNOUSE_CcchLoadIndPeriod*/
/* NOT #define XTNOUSE_CcchLoadThreshold*/
/* NOT #define XTNOUSE_ChanCombination*/
/* NOT #define XTNOUSE_EventType*/
/* NOT #define XTNOUSE_NackCause*/
/* NOT #define XTNOUSE_IntaveParam*/
/* NOT #define XTNOUSE_OprState*/
/* NOT #define XTNOUSE_ManState*/
/* NOT #define XTNOUSE_SpecificProbs*/
/* NOT #define XTNOUSE_SeverityValue*/
/* NOT #define XTNOUSE_WindowSize*/
/* NOT #define XTNOUSE_RachLoadAvgSlots*/
/* NOT #define XTNOUSE_MaxTimingAdv*/
/* NOT #define XTNOUSE_RachBusyThreshold*/
/* NOT #define XTNOUSE_FnOffset*/
/* NOT #define XTNOUSE_RfMaxPowerReduction*/
#define XTNOUSE_ChannelID
#define XTNOUSE_TimingAdvance
#define XTNOUSE_MobileAlloc
#define XTNOUSE_Mcc
#define XTNOUSE_Mnc
#define XTNOUSE_CellBarred
/* NOT #define XTNOUSE_OamsObjectType*/
/* NOT #define XTNOUSE_OamsReason*/
/* NOT #define XTNOUSE_OamsResult*/
/* NOT #define XTNOUSE_OamsCause*/
/* NOT #define XTNOUSE_AccessBurstType*/
/* NOT #define XTNOUSE_GprsMode*/
/* NOT #define XTNOUSE_BicIdentifier*/
/* NOT #define XTNOUSE_AlarmCause*/
/* NOT #define XTNOUSE_CcuIdentifier*/
/* NOT #define XTNOUSE_CcNackCause*/
/* NOT #define XTNOUSE_Result*/
/* NOT #define XTNOUSE_CcSocAlarmThresh*/
/* NOT #define XTNOUSE_CcBatteryAgingAlarmLevel*/
/* NOT #define XTNOUSE_CcAgingBatNewBat*/
/* NOT #define XTNOUSE_CcHighTempLevel*/
/* NOT #define XTNOUSE_CcNightModeLevel*/
/* NOT #define XTNOUSE_CcSampleInterv*/
/* NOT #define XTNOUSE_CcReportInterv*/
/* NOT #define XTNOUSE_PwrActionType*/
/* NOT #define XTNOUSE_PwrEntity*/
/* NOT #define XTNOUSE_PwrRestartTime*/
/* NOT #define XTNOUSE_CcDataSetId*/
/* NOT #define XTNOUSE_CcDataSetExtent*/
/* NOT #define XTNOUSE_CcTime*/
/* NOT #define XTNOUSE_BicTei*/
/* NOT #define XTNOUSE_NodeType*/
/* NOT #define XTNOUSE_NodeIdentity*/
/* NOT #define XTNOUSE_ApplTei*/
/* NOT #define XTNOUSE_SwmhNackCause*/
#define XTNOUSE_SysInfoType
/* NOT #define XTNOUSE_Tei*/
#define XTNOUSE_TrxTei
#define XTNOUSE_TimingAdv
/* NOT #define XTNOUSE_TimeSlot*/
/* NOT #define XTNOUSE_Pcm*/
#define XTNOUSE_ConnectionId
#define XTNOUSE_SccpConnRefId
/* NOT #define XTNOUSE_OptFlag*/
#define XTNOUSE_TransactionId
/* NOT #define XTNOUSE_IsBcchTrx*/
#define XTNOUSE_PresenceFlag
#define XTNOUSE_ResourceId
#define XTNOUSE_AbisSignallingReleaseReqd
#define XTNOUSE_AifSignallingReleaseReqd
/* NOT #define XTNOUSE_CellId*/
#define XTNOUSE_Codec
#define XTNOUSE_InstanceId
/* NOT #define XTNOUSE_PtrxId*/
/* NOT #define XTNOUSE_LtrxId*/
/* NOT #define XTNOUSE_ChgrId*/
/* NOT #define XTNOUSE_Lac*/
/* NOT #define XTNOUSE_AbisE1Id*/
/* NOT #define XTNOUSE_Cause*/
#define XTNOUSE_SccpCause
/* NOT #define XTNOUSE_ChannelName*/
/* NOT #define XTNOUSE_ChannelId*/
#define XTNOUSE_MsgGrpId
/* NOT #define XTNOUSE_Sapi*/
/* NOT #define XTNOUSE_Hsn*/
/* NOT #define XTNOUSE_Maio*/
/* NOT #define XTNOUSE_Tsc*/
/* NOT #define XTNOUSE_CPtr_CpIU32V_OamInclude*/
/* NOT #define XTNOUSE_OamsCcuhContext*/
/* NOT #define XTNOUSE_abc*/
#define XTNOUSE_ptr_OamsCcuhContext
#define XTNOUSE_ptr_abc
#define XTNOUSE_cast_operators
#define XTNOUSE_cast_operators_0
#define XTNOUSE_CPtr_CpCcConfigTableApiV
#define XTNOUSE_CPtr_CpCcDataReqTableApiV
#define XTNOUSE_CPtr_CpBicCcInfoTableApiV
#define XTNOUSE_CPtr_CpSwMNodeTableApiV
#define XTNOUSE_CPtr_CpCsappAbihmCcuhBicBscAlarmIndV
#define XTNOUSE_CPtr_CpCsappAbihmCcuhBicCcInfoRespV
#define XTNOUSE_CPtr_CpCsappAbihmCcuhBicGetCcCfgRespV
#define XTNOUSE_CPtr_CpCsappAbihmCcuhBicSetCcCfgRespV
#define XTNOUSE_CPtr_CpOamsCfgCcuhBicCcDataReqV
#define XTNOUSE_CPtr_CpCsappAbihmCcuhBicCcDataRespV
#define XTNOUSE_CPtr_CpCsappAbihmCcuhBicCcDataNackV
#define XTNOUSE_CPtr_CpOamPdcCcuhBicCcInfoReqV
#define XTNOUSE_CPtr_CpOamsCfgCcuhBicSetCcCfgReqV
#define XTNOUSE_CPtr_CpOamsTrxhCfgAlarmIndV
#define XTNOUSE_CPtr_CpOamsCcuhAbihmBicCcInfoReqV
#define XTNOUSE_CPtr_CpOamsCcuhAbihmBicGetCcCfgReqV
#define XTNOUSE_CPtr_CpOamsCcuhAbihmBicSetCcCfgReqV
#define XTNOUSE_CPtr_CpBssCsPreConfigTableApiV
#define XTNOUSE_CPtr_CpOamsCfgCcuhBicCcPwrOrderReqV
#define XTNOUSE_CPtr_CpIU8V_CCUH
/* NOT #define XTNOUSE_TmplInst_CArr100IU8V_CCUHandler*/
#define XTNOUSE_TmplInst_CArr25IU8V_CCUHandler
#define XTNOUSE_TmplInst_CArr30IU8V
#endif

