
/* Program generated by Cadvanced 3.0.0.0.2032 */
#define XSCT_CADVANCED

#define C_TRANSLATOR_2_6
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#include "U2ExtraOps.h"
#include "U2ctypes.h"
#include "SYSInclude.h"
#include "DBInclude.h"
#include "OamInclude.h"
#include "CCUInclude.h"
#ifdef XUSE_SIGNAL_NUMBERS
#include "System_CCUH.hs"
#endif
#ifdef XCTRACE
static char  xFileName[] = "CCUInclude.c";
#endif


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PACKAGE CCUInclude
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#Yw5EEEPaSEEEUzbV5LESm2EE|pos(1,9)")
******/
XCONST struct xPackageIdStruct yPacR_z_CCUInclude__CCUInclude = {xPackageEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&xSymbolTableIdRec
  xIdNames("CCUInclude") xIdNumber(0) XCOMMON_EXTRAS xIdNames(0) XPAC_EXTRAS};

/*****
* NEWTYPE OamsCcuhContext  (BODY section)
* <<PACKAGE CCUInclude>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#3Z8HEExqEEEE5ZZi5LLOEm9V|pos(1,13)")
******/
#ifndef XTNOUSE_OamsCcuhContext
static tSDLFieldInfo fSDL_z_CCUInclude_H0_OamsCcuhContext[] = {
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y1S_OptFlag
    T_SDL_Names("isCcuIdPresent"), xOffsetOf(OamsCcuhContext, isCcuIdPresent),
    0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y1S_OptFlag
    T_SDL_Names("isCcuBackupSwVersionPresent"),
    xOffsetOf(OamsCcuhContext, isCcuBackupSwVersionPresent), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y1S_OptFlag
    T_SDL_Names("isCcuNackPresent"),
    xOffsetOf(OamsCcuhContext, isCcuNackPresent), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y1F_BicTei  T_SDL_Names("bicTei"),
    xOffsetOf(OamsCcuhContext, bicTei), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y0X_BicIdentifier  T_SDL_Names("bicId"),
    xOffsetOf(OamsCcuhContext, bicId), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y0Z_CcuIdentifier  T_SDL_Names("ccuId"),
    xOffsetOf(OamsCcuhContext, ccuId), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y11_Result
    T_SDL_Names("infoAvailStatus"),
    xOffsetOf(OamsCcuhContext, infoAvailStatus), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_H9X_ptr_BicCcProtoVersion
    T_SDL_Names("ccProtoVersion"), xOffsetOf(OamsCcuhContext, ccProtoVersion),
    0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_H9Y_ptr_BicCcSerialNumber
    T_SDL_Names("ccSerialNumber"), xOffsetOf(OamsCcuhContext, ccSerialNumber),
    0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_H9U_ptr_SwDes
    T_SDL_Names("ccActiveSwVersion"),
    xOffsetOf(OamsCcuhContext, ccActiveSwVersion), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_H9U_ptr_SwDes
    T_SDL_Names("ccBackupSwVersion"),
    xOffsetOf(OamsCcuhContext, ccBackupSwVersion), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_Y10_CcNackCause
    T_SDL_Names("nackCause"), xOffsetOf(OamsCcuhContext, nackCause), 0},
  {(tSDLTypeInfo *)&ySDL_z_OamInclude_H9V_ptr_CcPowerInfo
    T_SDL_Names("ccPwrInfo"), xOffsetOf(OamsCcuhContext, ccPwrInfo), 0}
};
tSDLStructInfo ySDL_z_CCUInclude_H0_OamsCcuhContext = {type_SDL_Struct, 1,
  (xptrint)sizeof(OamsCcuhContext) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("OamsCcuhContext")
  xRaWF((xIdNode)&yPacR_z_CCUInclude__CCUInclude)
  xRaWF(&ySrtR_z_CCUInclude_H0_OamsCcuhContext),
  fSDL_z_CCUInclude_H0_OamsCcuhContext, 13};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_CCUInclude_H0_OamsCcuhContext = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&yPacR_z_CCUInclude__CCUInclude
  xIdNames("OamsCcuhContext") xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(yEq_z_CCUInclude_H0_OamsCcuhContext) xTestF(0),
  (xptrint)sizeof(OamsCcuhContext), xStruct, (xSortIdNode)0, (xSortIdNode)0, 0,
  0, 0, 0 xRaWF((tSDLTypeInfo *)&ySDL_z_CCUInclude_H0_OamsCcuhContext)
  XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X0_isCcuIdPresent =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("isCcuIdPresent") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y1S_OptFlag,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y1S_OptFlag, xOffsetOf(OamsCcuhContext,
  isCcuIdPresent), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X1_isCcuBackupSwVersionPresent =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("isCcuBackupSwVersionPresent") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y1S_OptFlag,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y1S_OptFlag, xOffsetOf(OamsCcuhContext,
  isCcuBackupSwVersionPresent), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X2_isCcuNackPresent =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("isCcuNackPresent") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y1S_OptFlag,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y1S_OptFlag, xOffsetOf(OamsCcuhContext,
  isCcuNackPresent), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X3_bicTei = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("bicTei") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y1F_BicTei,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y1F_BicTei, xOffsetOf(OamsCcuhContext,
  bicTei), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X4_bicId = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("bicId") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y0X_BicIdentifier,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y0X_BicIdentifier,
  xOffsetOf(OamsCcuhContext, bicId), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X5_ccuId = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("ccuId") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y0Z_CcuIdentifier,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y0Z_CcuIdentifier,
  xOffsetOf(OamsCcuhContext, ccuId), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X6_infoAvailStatus =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("infoAvailStatus") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y11_Result,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y11_Result, xOffsetOf(OamsCcuhContext,
  infoAvailStatus), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X7_ccProtoVersion =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("ccProtoVersion") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_H9X_ptr_BicCcProtoVersion,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_H9X_ptr_BicCcProtoVersion,
  xOffsetOf(OamsCcuhContext, ccProtoVersion), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X8_ccSerialNumber =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("ccSerialNumber") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_H9Y_ptr_BicCcSerialNumber,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_H9Y_ptr_BicCcSerialNumber,
  xOffsetOf(OamsCcuhContext, ccSerialNumber), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0X9_ccActiveSwVersion =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("ccActiveSwVersion") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_H9U_ptr_SwDes,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_H9U_ptr_SwDes, xOffsetOf(OamsCcuhContext,
  ccActiveSwVersion), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0XA_ccBackupSwVersion =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("ccBackupSwVersion") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_H9U_ptr_SwDes,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_H9U_ptr_SwDes, xOffsetOf(OamsCcuhContext,
  ccBackupSwVersion), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0XB_nackCause =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("nackCause") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_Y10_CcNackCause,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_Y10_CcNackCause,
  xOffsetOf(OamsCcuhContext, nackCause), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H0XC_ccPwrInfo =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext
  xIdNames("ccPwrInfo") xIdNumber(0) XCOMMON_EXTRAS,
  &ySrtR_z_OamInclude_H9V_ptr_CcPowerInfo,
  (tSDLTypeInfo *)&ySDL_z_OamInclude_H9V_ptr_CcPowerInfo,
  xOffsetOf(OamsCcuhContext, ccPwrInfo), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE abc  (BODY section)
* <<PACKAGE CCUInclude>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#eZ8HEExqEEEE5ZZi5LLOEm9V|pos(1,13)")
******/
#ifndef XTNOUSE_abc
static tSDLFieldInfo fSDL_z_CCUInclude_H1_abc[] = {
  {(tSDLTypeInfo *)&ySDL_z_SYSInclude_Y1_I_U8  T_SDL_Names("ab"),
    xOffsetOf(abc, ab), 0}
};
tSDLStructInfo ySDL_z_CCUInclude_H1_abc = {type_SDL_Struct, 1,
  (xptrint)sizeof(abc) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("abc")
  xRaWF((xIdNode)&yPacR_z_CCUInclude__CCUInclude)
  xRaWF(&ySrtR_z_CCUInclude_H1_abc), fSDL_z_CCUInclude_H1_abc, 1};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_CCUInclude_H1_abc = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&yPacR_z_CCUInclude__CCUInclude
  xIdNames("abc") xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(yEq_z_CCUInclude_H1_abc) xTestF(0), (xptrint)sizeof(abc), xStruct,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_CCUInclude_H1_abc) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_CCUInclude_H1X0_ab = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_CCUInclude_H1_abc
  xIdNames("ab") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y1_I_U8,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y1_I_U8, xOffsetOf(abc, ab), (xptrint)0, 0
  XVAR_EXTRAS};
#endif

/*****
* NEWTYPE @ptr_OamsCcuhContext  (BODY section)
* <<PACKAGE CCUInclude>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#@NO@GUID|pos(1,13)")
******/
#ifndef XTNOUSE_ptr_OamsCcuhContext
tSDLGenInfo ySDL_z_CCUInclude_H2_ptr_OamsCcuhContext = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_CCUInclude_H2_ptr_OamsCcuhContext) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("@ptr_OamsCcuhContext")
  xRaWF((xIdNode)&yPacR_z_CCUInclude__CCUInclude)
  xRaWF(&ySrtR_z_CCUInclude_H2_ptr_OamsCcuhContext),
  (tSDLTypeInfo *)&ySDL_z_CCUInclude_H0_OamsCcuhContext};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_CCUInclude_H2_ptr_OamsCcuhContext =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_CCUInclude__CCUInclude
  xIdNames("@ptr_OamsCcuhContext") xIdNumber(0) XCOMMON_EXTRAS xFreF(0)
  xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_CCUInclude_H2_ptr_OamsCcuhContext), xRef,
  &ySrtR_z_CCUInclude_H0_OamsCcuhContext, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_CCUInclude_H2_ptr_OamsCcuhContext) XSRT_EXTRAS};
#endif

/*****
* NEWTYPE @ptr_abc  (BODY section)
* <<PACKAGE CCUInclude>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#@NO@GUID|pos(1,13)")
******/
#ifndef XTNOUSE_ptr_abc
tSDLGenInfo ySDL_z_CCUInclude_H3_ptr_abc = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_CCUInclude_H3_ptr_abc) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("@ptr_abc") xRaWF((xIdNode)&yPacR_z_CCUInclude__CCUInclude)
  xRaWF(&ySrtR_z_CCUInclude_H3_ptr_abc),
  (tSDLTypeInfo *)&ySDL_z_CCUInclude_H1_abc};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_CCUInclude_H3_ptr_abc = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&yPacR_z_CCUInclude__CCUInclude
  xIdNames("@ptr_abc") xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_CCUInclude_H3_ptr_abc), xRef,
  &ySrtR_z_CCUInclude_H1_abc, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_CCUInclude_H3_ptr_abc) XSRT_EXTRAS};
#endif

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
void yInit_CCUInclude (void)
{
  static int IsCalled = 0;
  int  Temp;
  YINIT_TEMP_VARS
  if (IsCalled) {
    return;
  }
  IsCalled = 1;
  xInsertIdNode((xIdNode)&yPacR_z_CCUInclude__CCUInclude);
  yInit_U2ExtraOps();
  yInit_U2ctypes();
  yInit_DBInclude();
  yInit_SYSInclude();
  yInit_OamInclude();
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_CCUInclude_H0_OamsCcuhContext);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X0_isCcuIdPresent);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X1_isCcuBackupSwVersionPresent);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X2_isCcuNackPresent);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X3_bicTei);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X4_bicId);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X5_ccuId);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X6_infoAvailStatus);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X7_ccProtoVersion);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X8_ccSerialNumber);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0X9_ccActiveSwVersion);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0XA_ccBackupSwVersion);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0XB_nackCause);
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H0XC_ccPwrInfo);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_CCUInclude_H1_abc);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_CCUInclude_H1X0_ab);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_CCUInclude_H2_ptr_OamsCcuhContext);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_CCUInclude_H3_ptr_abc);
#endif
}
