
/* Program generated by Cadvanced 3.0.0.0.2032 */
#define XSCT_CADVANCED

#define C_TRANSLATOR_2_6
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#include "U2ExtraOps.h"
#include "U2ctypes.h"
#include "SYSInclude.h"
#include "Interface.h"
#ifdef XUSE_SIGNAL_NUMBERS
#include "System_CCUH.hs"
#endif
#ifdef XCTRACE
static char  xFileName[] = "Interface.c";
#endif


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PACKAGE Interface
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#g9CEEEPaSEEEO-bV5LESm2EE|pos(1,9)")
******/
XCONST struct xPackageIdStruct yPacR_z_Interface__Interface = {xPackageEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&xSymbolTableIdRec
  xIdNames("Interface") xIdNumber(0) XCOMMON_EXTRAS xIdNames(0) XPAC_EXTRAS};

/*****
* SIGNAL OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#gK6EEELuLEEEg1yV5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ),
  &ySigA_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#gK6EEELuLEEEg1yV5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y5_I_U32,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y5_I_U32,
  xOffsetOf(ySignalPar_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ, Param2),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#4KdEEEhtEEEEP7YS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ),
  &ySigA_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#4KdEEEhtEEEEP7YS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y5_I_U32,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y5_I_U32,
  xOffsetOf(ySignalPar_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ, Param2),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#trUEEEVWLEEEGCcS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ),
  &ySigA_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#trUEEEVWLEEEGCcS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y5_I_U32,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y5_I_U32,
  xOffsetOf(ySignalPar_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ, Param2),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#s8XLEEuWIEEEEWyS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ),
  &ySigA_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#s8XLEEuWIEEEEWyS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y5_I_U32,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y5_I_U32,
  xOffsetOf(ySignalPar_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ, Param2),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#1DIVEEuWIEEE5gyS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ),
  &ySigA_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#1DIVEEuWIEEE5gyS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y5_I_U32,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y5_I_U32,
  xOffsetOf(ySignalPar_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ, Param2),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#hN9EEELuLEEEu3yV5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP),
  &ySigA_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP, 0 xFreS(0)
  SIGCODE(SN_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#hN9EEELuLEEEu3yV5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#wG-LEE*gLEEEqN9S5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP),
  &ySigA_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP, 0 xFreS(0)
  SIGCODE(SN_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#wG-LEE*gLEEEqN9S5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#3N-LEE*gLEEELO9S5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP),
  &ySigA_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP, 0 xFreS(0)
  SIGCODE(SN_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#3N-LEE*gLEEELO9S5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#9vXSEEuWIEEEaPzS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP),
  &ySigA_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP, 0 xFreS(0)
  SIGCODE(SN_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#9vXSEEuWIEEEaPzS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#ebXSEEuWIEEEuPzS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK),
  &ySigA_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK, 0 xFreS(0)
  SIGCODE(SN_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#ebXSEEuWIEEEuPzS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#Msk0EE6xEEEEtDZA5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND),
  &ySigA_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND, 0 xFreS(0)
  SIGCODE(SN_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#Msk0EE6xEEEEtDZA5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CCUH_CFG_ALARM_IND
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#csrEEELuLEEEANyV5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CCUH_CFG_ALARM_IND") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND),
  &ySigA_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND, 0 xFreS(0)
  SIGCODE(SN_OAMS_CCUH_CFG_ALARM_IND)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#csrEEELuLEEEANyV5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y5_I_U32,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y5_I_U32,
  xOffsetOf(ySignalPar_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND, Param2),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CFG_CCUH_BIC_CC_INFO_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#jQyEEELuLEEEZOyV5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CFG_CCUH_BIC_CC_INFO_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ),
  &ySigA_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CFG_CCUH_BIC_CC_INFO_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#jQyEEELuLEEEZOyV5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CFG_CCUH_BIC_CC_DATA_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#cSrEEEdaLEEE4MwS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CFG_CCUH_BIC_CC_DATA_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ),
  &ySigA_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CFG_CCUH_BIC_CC_DATA_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#cSrEEEdaLEEE4MwS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#PmoLEEdaLEEESnwS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ),
  &ySigA_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#PmoLEEdaLEEESnwS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#XGjeEEmalEEE9owl5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ),
  &ySigA_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ, 0 xFreS(0)
  SIGCODE(SN_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#XGjeEEmalEEE9owl5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_BICH_CCUH_LAPD_LINK_DOWN
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#WwkEEELuLEEES1yV5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_BICH_CCUH_LAPD_LINK_DOWN") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN),
  &ySigA_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN, 0 xFreS(0)
  SIGCODE(SN_OAMS_BICH_CCUH_LAPD_LINK_DOWN)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#WwkEEELuLEEES1yV5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAMS_BICH_CCUH_LAPD_LINK_UP
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#281lEEh*AEEEWrGS5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAMS_BICH_CCUH_LAPD_LINK_UP") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP),
  &ySigA_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP, 0 xFreS(0)
  SIGCODE(SN_OAMS_BICH_CCUH_LAPD_LINK_UP)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#281lEEh*AEEEWrGS5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL ATTACH_INST
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#XkyEEELuLEEEePyV5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
XCONST struct xSignalIdStruct ySigR_z_Interface_SI_ATTACH_INST = {xSignalEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("ATTACH_INST") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(SN_ATTACH_INST)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#XkyEEELuLEEEePyV5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif

/*****
* SIGNAL CCUH_INT_ADD_TAU_INST_IN_INSTMAP
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#2xyEEELuLEEEjPyV5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("CCUH_INT_ADD_TAU_INST_IN_INSTMAP") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP),
  &ySigA_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP, 0 xFreS(0)
  SIGCODE(SN_CCUH_INT_ADD_TAU_INST_IN_INSTMAP)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#2xyEEELuLEEEjPyV5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_Y1_I_U8,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_Y1_I_U8,
  xOffsetOf(ySignalPar_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL OAM_PDC_CCUH_BIC_CC_INFO_REQ
* <<PACKAGE Interface>>
* #SDTREF(U2,"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#JwV5EE6xEEEEs9KA5LESm2EE|pos(1,12)")
******/
#ifndef XNOSIGNALIDNODE
static xSignalNode ySigA_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ =
  {xSignalEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_Interface__Interface
  xIdNames("OAM_PDC_CCUH_BIC_CC_INFO_REQ") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ),
  &ySigA_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ, 0 xFreS(0)
  SIGCODE(SN_OAM_PDC_CCUH_BIC_CC_INFO_REQ)
  xBreakB("#SDTREF(U2,\"u2:/misc/home1/priyagupta/BSCCS4.0_orig/BSCCS2-Development/Source/Oams/Src/CCUH/Model/CCUH.u2#JwV5EE6xEEEEs9KA5LESm2EE|pos(1,12)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#endif
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ =
  {xSignalParEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySigR_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ
  xIdNames(" ") xIdNumber(0) XCOMMON_EXTRAS, &ySrtR_z_SYSInclude_YB_I_PVoid,
  (tSDLTypeInfo *)&ySDL_z_SYSInclude_YB_I_PVoid,
  xOffsetOf(ySignalPar_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ, Param1),
  (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
void yInit_Interface (void)
{
  static int IsCalled = 0;
  int  Temp;
  YINIT_TEMP_VARS
  if (IsCalled) {
    return;
  }
  IsCalled = 1;
  xInsertIdNode((xIdNode)&yPacR_z_Interface__Interface);
  yInit_U2ExtraOps();
  yInit_U2ctypes();
  yInit_SYSInclude();
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ);
  xInsertIdNode((xIdNode)&ySPaR2_z_Interface_S0_OAMS_CCUH_ABIHM_BIC_CC_INFO_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ);
  xInsertIdNode((xIdNode)&ySPaR2_z_Interface_S1_OAMS_CCUH_ABIHM_BIC_GET_CC_CFG_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ);
  xInsertIdNode((xIdNode)&ySPaR2_z_Interface_S2_OAMS_CCUH_ABIHM_BIC_SET_CC_CFG_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ);
  xInsertIdNode((xIdNode)&ySPaR2_z_Interface_S3_OAMS_CCUH_ABIHM_BIC_CC_PWR_ORDER_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ);
  xInsertIdNode((xIdNode)&ySPaR2_z_Interface_S4_OAMS_CCUH_ABIHM_BIC_CC_DATA_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S5_CSAPP_ABIHM_CCUH_BIC_CC_INFO_RESP);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S6_CSAPP_ABIHM_CCUH_BIC_GET_CC_CFG_RESP);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S7_CSAPP_ABIHM_CCUH_BIC_SET_CC_CFG_RESP);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S8_CSAPP_ABIHM_CCUH_BIC_CC_DATA_RESP);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_S9_CSAPP_ABIHM_CCUH_BIC_CC_DATA_NACK);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SA_CSAPP_ABIHM_CCUH_BIC_BSC_ALARM_IND);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND);
  xInsertIdNode((xIdNode)&ySPaR2_z_Interface_SB_OAMS_CCUH_CFG_ALARM_IND);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SC_OAMS_CFG_CCUH_BIC_CC_INFO_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SD_OAMS_CFG_CCUH_BIC_CC_DATA_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SE_OAMS_CFG_CCUH_BIC_CC_PWR_ORDER_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SF_OAMS_CFG_CCUH_BIC_SET_CC_CFG_REQ);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SG_OAMS_BICH_CCUH_LAPD_LINK_DOWN);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SH_OAMS_BICH_CCUH_LAPD_LINK_UP);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SI_ATTACH_INST);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SJ_CCUH_INT_ADD_TAU_INST_IN_INSTMAP);
#endif
#ifndef XNOSIGNALIDNODE
  xInsertIdNode((xIdNode)&ySigR_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ);
#endif
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_Interface_SK_OAM_PDC_CCUH_BIC_CC_INFO_REQ);
#endif
}
