#include "bpmDiaglib.h"
#include "bpmInclude.h"
extern FILE *filePtr; 
extern sLibGlobalParam libGlobalParam;
extern sParamKeySet paramKeySet[MAX_TCT_ID][MAX_TEST_ID];

void initTestResultString()
{
  strcpy((char *)libGlobalParam.testResultString[TEST_COMPLETE], "Completed");
  strcpy((char *)libGlobalParam.testResultString[TEST_ABORT], "Aborted");
  strcpy((char *)libGlobalParam.testResultString[TEST_CANCEL], "Cancelled");
}

void initTestCaseString()
{
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_GEN], "ICCGEN");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_RAM_CP], "ICCRAMCP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_ETHERNET_CP], "ICCETHERNETCP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_FLASHDISK_CP], "ICCFLASHDISKCP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_CPLD], "ICCCPLD");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_FRAMER], "ICCFRAMER");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_ETHERNET_PP], "ICCETHERNETPP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_RAM_PP], "ICCRAMPP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_FLASHDISK_PP], "ICCFLASHDISKPP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_I2C_BUS], "ICCI2CBUS");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_DSP], "ICCDSP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_MCC], "ICCMCC");
  
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_ICC_TSI], "ICCTSI");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_EIC_FRAMER], "EICFRAMER");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_EIC_ETHERNET_CP], "EICETHERNETCP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_EIC_ETHERNET_SWITCH], "EICETHERNETSWITCH");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_EIC_DSP], "EICDSP");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_EIC_CPLD], "EICCPLD");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_PSU], "PSU");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_FAN_TRAY], "FANTRAY");

  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_OBM_GEN], "OBMGEN");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_OBM_RAM], "OBMRAM");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_OBM_ETHERNET], "OBMETHERNET");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_OBM_FLASHDISK], "OBMFLASHDISK");
  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_OBM_FAN], "OBMFAN");

  strcpy((char *)libGlobalParam.TCT_String[DIAGNOS_TCT_OBF], "OBF");
}

void initTestCaseIdString()
{
  strcpy((char *)libGlobalParam.TCID_String[1], "TestId_All");
  strcpy((char *)libGlobalParam.TCID_String[2], "TestId_1");
  strcpy((char *)libGlobalParam.TCID_String[3], "TestId_2");
  strcpy((char *)libGlobalParam.TCID_String[4], "TestId_3");
  strcpy((char *)libGlobalParam.TCID_String[5], "TestId_4");
  strcpy((char *)libGlobalParam.TCID_String[6], "TestId_5");
  strcpy((char *)libGlobalParam.TCID_String[7], "TestId_6");
  strcpy((char *)libGlobalParam.TCID_String[8], "TestId_7");
  strcpy((char *)libGlobalParam.TCID_String[9], "TestId_8");
  strcpy((char *)libGlobalParam.TCID_String[10], "TestId_9");
  strcpy((char *)libGlobalParam.TCID_String[11], "TestId_10");
}

void initParamData()
{
  memset(paramKeySet, 0, sizeof(paramKeySet));  
  paramKeySet[DIAGNOS_TCT_ICC_GEN][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_GEN][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][4].paramBits = 0x04;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][5].paramBits = 0x04;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_CP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][2].paramBits = 0x02;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_CP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][3].paramBits = 0x10;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_CP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_CPLD][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][2].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][3].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][4].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][5].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][6].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][7].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FRAMER][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][2].paramBits = 0x02;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][3].paramBits = 0x02;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_ETHERNET_PP][10].paramBits = 0x02;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][4].paramBits = 0x04;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][5].paramBits = 0x04;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_RAM_PP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][3].paramBits = 0x10;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_FLASHDISK_PP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][4].paramBits = 0x20;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_I2C_BUS][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_DSP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][3].paramBits = 0x40;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][4].paramBits = 0xc0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_MCC][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][3].paramBits = 0x08;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][4].paramBits = 0x08;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][5].paramBits = 0x08;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][6].paramBits = 0x08;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_ICC_TSI][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][2].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][3].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][4].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][5].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][6].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][7].paramBits = 0x01;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_FRAMER][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_CP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_ETHERNET_SWITCH][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][2].paramBits = 0x10;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][3].paramBits = 0x10;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][4].paramBits = 0x10;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][5].paramBits = 0x10;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_DSP][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_EIC_CPLD][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_PSU][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_FAN_TRAY][10].paramBits = 0;

  paramKeySet[DIAGNOS_TCT_OBM_GEN][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_GEN][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][4].paramBits = 0x04;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][5].paramBits = 0x04;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_RAM][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][2].paramBits = 0x02;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_ETHERNET][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][3].paramBits = 0x10;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FLASHDISK][10].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBM_FAN][10].paramBits = 0;

  paramKeySet[DIAGNOS_TCT_OBF][1].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][2].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][3].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][4].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][5].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][6].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][7].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][8].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][9].paramBits = 0;
  paramKeySet[DIAGNOS_TCT_OBF][10].paramBits = 0;
} 

void  initGlobalStructData()
{
  const char *temp =NULL;
  libGlobalParam.fileAction = DIAG_FILE_APPEND;
  libGlobalParam.errCode = 0;
  strcpy((char *)libGlobalParam.TestResp[0], "Fail");
  strcpy((char *)libGlobalParam.TestResp[1], "Pass");
  strcpy((char *)libGlobalParam.fileName, "NULL");
  temp = getenv("DIAG_FILES_DIR");
  if(temp != NULL)
  {
    strcpy((char *)libGlobalParam.filePath, temp);
    LOG_PRINT(DEBUG,"DIAG Library Initialization success");
  }     
  else
  {
    LOG_PRINT(CRITICAL,"DIAG_LIB: SYSTEM ERROR !! 'file path not defined' default path /home/");
    strcpy((char *)libGlobalParam.filePath, "/home/");
  }
  LOG_PRINT(INFO,"DIAG Library Initialization success");
  printf("\n");
}

void initErrCodeString()
{
  /* Framer error Code String */
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PEER_CARD_NOT_CONNECTED - ERR_CODE_DIAG_BASE], "Peer Card not Connected");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_CARDSTATE_INVALID - ERR_CODE_DIAG_BASE], "Card State Invalid");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_CARDSTATE_SET_FAIL - ERR_CODE_DIAG_BASE], "Set Card State Operation Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_EIC_ACTIVATION_INVALID_STATE - ERR_CODE_DIAG_BASE], "EIC Activation in Invalid State");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PM_PM_CONNECTION_CLOSED - ERR_CODE_DIAG_BASE], "PM to PM Connection is Closed");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_APPID - ERR_CODE_DIAG_BASE], "Invalid ApplID");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_INVALID_PARAM - ERR_CODE_DIAG_BASE], "Invalid Paramter");
  strcpy((char *)libGlobalParam.errCodeString[ERR_SLOTID_MISMATCH - ERR_CODE_DIAG_BASE], "SlotID Mismatch");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_BPM_INTERNAL - ERR_CODE_DIAG_BASE], "BPM Internal Error");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_CONFIGURATION_IN_PROGRESS - ERR_CODE_DIAG_BASE], "Configuration in Progress");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_INVALID_NUM_CONFIGURATION - ERR_CODE_DIAG_BASE], "Invalid parameter maxclkconfig");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_INVALID_PORTID - ERR_CODE_DIAG_BASE], "Invalid PortID");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PEER_INVALID_CARD_STATE - ERR_CODE_DIAG_BASE], "Invalid Peer Card State");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PEER_UPGRADE_IN_PROGRESS - ERR_CODE_DIAG_BASE], "Peer Card Upgrade in Progress");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DSP_RESET_IN_PROGRESS - ERR_CODE_DIAG_BASE], "DSP Reset in Progress");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_EIC_NOT_CONNECTED - ERR_CODE_DIAG_BASE], "EIC not Connected");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PEER_CARDSTATE_INVALID - ERR_CODE_DIAG_BASE], "Peer Card State Invalid");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DIAG_TEST_IN_PROGRESS - ERR_CODE_DIAG_BASE], "Diagnostic Test in Progress");
  strcpy((char *)libGlobalParam.errCodeString[FAN_WORKING - ERR_CODE_DIAG_BASE], "Fan is Working");
  strcpy((char *)libGlobalParam.errCodeString[FAN_NOT_WORKING - ERR_CODE_DIAG_BASE], "Fan is Not Working");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_TEST_TYPE - ERR_CODE_DIAG_BASE], "Invalid TestType");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_TEST_ID - ERR_CODE_DIAG_BASE], "Invalid TestID");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_INTR_VALUE - ERR_CODE_DIAG_BASE], "Invalid intr value");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_SUP_VALUE - ERR_CODE_DIAG_BASE], "Invalid Suppress value");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_ACTION_VALUE - ERR_CODE_DIAG_BASE], "Invalid Action value");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_NUMARGS_VALUE - ERR_CODE_DIAG_BASE], "Invalid Num of args passed");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_REP_VALUE - ERR_CODE_DIAG_BASE], "Invalid Repitition value");
  strcpy((char *)libGlobalParam.errCodeString[TEST_PASS - ERR_CODE_DIAG_BASE], "Test Pass");
  strcpy((char *)libGlobalParam.errCodeString[TEST_FAIL - ERR_CODE_DIAG_BASE], "Test Fail");
  strcpy((char *)libGlobalParam.errCodeString[TEST_ABORTED - ERR_CODE_DIAG_BASE], "Test Aborted");
  strcpy((char *)libGlobalParam.errCodeString[TEST_CANCELED - ERR_CODE_DIAG_BASE], "Test Canceled");
  strcpy((char *)libGlobalParam.errCodeString[TEST_IN_PROGRESS - ERR_CODE_DIAG_BASE], "Test in Progress");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_BPM_TIMEOUT_EXPIRY - ERR_CODE_DIAG_BASE], "BPM Timeout Expired");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_FOPEN_FAIL - ERR_CODE_DIAG_BASE], "Fopen Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_IFCONFIG_FAILED - ERR_CODE_DIAG_BASE], "Failure in ifconfig : File fileEthStatus could not be created");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_STATFS_FAILED - ERR_CODE_DIAG_BASE], "Failure in statfs");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_MMAP_FAILED - ERR_CODE_DIAG_BASE], "Failure in mmap");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_FILE_ERASE_FAILED - ERR_CODE_DIAG_BASE], "Failure in File Erase");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_CPLD_DUMP_FAILED - ERR_CODE_DIAG_BASE], "Failure in CPLD Dump");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PATTERN_NOT_MATCHED - ERR_CODE_DIAG_BASE], "Pattern not matched");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_INVALID_BLOCK_SIZE - ERR_CODE_DIAG_BASE], "Invalid Block Size");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_ADDRESS_BUS_TEST_FAILED - ERR_CODE_DIAG_BASE], "Failure in Address Bus Test");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DATA_BUS_TEST_FAILED - ERR_CODE_DIAG_BASE], "Failure in Data Bus Test");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_MEMORY_ALLOCATION_FAILED - ERR_CODE_DIAG_BASE], "Failure in Memory Allocation");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_NAND_BLOCK_ALLOC_FAILED - ERR_CODE_DIAG_BASE], "Failure in NAND Block Allocation");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_BPM_DISPATCH_FAILED - ERR_CODE_DIAG_BASE], "BPM Dispatch Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_THREAD_ATTR_FAILED - ERR_CODE_DIAG_BASE], "Thread Attribute Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_THREAD_CREATE_FAILED - ERR_CODE_DIAG_BASE], "Thread Creation Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_INVALID_PORT_NUM - ERR_CODE_DIAG_BASE], "Invalid Port Number");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_AUTO_NEG_FAIL - ERR_CODE_DIAG_BASE], "Auto Negotiation Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_FIXED_CONFIG_FAIL - ERR_CODE_DIAG_BASE], "Fixed Configuration Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_INVALID_DSP_ID - ERR_CODE_DIAG_BASE], "Invalid DspId");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DSP_DSI_SETUP_FAIL - ERR_CODE_DIAG_BASE], "DSP DSI Setup Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DSP_SDRAM_TEST_FAIL - ERR_CODE_DIAG_BASE], "DSP SDRAM Test Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DSP_TDM_LOOP_SET_FAIL - ERR_CODE_DIAG_BASE], "DSP TDM Loopback Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_IOCTL_COPY_FRM_USER - ERR_CODE_DIAG_BASE], "Ioctl copy_from_user Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_IOCTL_COPY_TO_USER - ERR_CODE_DIAG_BASE], "Ioctl copy_to_user Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERR_INVALID_FRAMER_PORT_NUM - ERR_CODE_DIAG_BASE], "Invalid Number of Framer Port");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_PORT_NOT_ACTIVE - ERR_CODE_DIAG_BASE], "Framer Port Not Active");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_INVALID_LOOP_TYPE - ERR_CODE_DIAG_BASE], "Invalid LoopType for Framer Port");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_BER_TX_FAIL - ERR_CODE_DIAG_BASE], "Error in BER Transmission");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_BER_RX_FAIL - ERR_CODE_DIAG_BASE], "Error in BER Receiving");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_BER_PATTERN_RECEIVE_INVALID - ERR_CODE_DIAG_BASE], "Invalid BER Pattern Received");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_BER_COUNT_MAX - ERR_CODE_DIAG_BASE], "Ioctl Error in BER count max");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_STREAM_CONFIG_INVALID - ERR_CODE_DIAG_BASE], "Invalid Stream Configuration");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_I2C_MEM_ALLOC - ERR_CODE_DIAG_BASE], "Error in I2C Memory allocation");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_I2C_MC_REG_READ_FAIL - ERR_CODE_DIAG_BASE], "I2C MC Register Read Failure");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_I2C_MC_REG_WRITE_FAIL - ERR_CODE_DIAG_BASE], "I2C MC Register Write Failure");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_I2C_READ_DEVICE_FAIL - ERR_CODE_DIAG_BASE], "I2C Read Device Failure");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_I2C_WRITE_DEVICE_FAIL - ERR_CODE_DIAG_BASE], "I2C Write Device Failure");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_TEST_NOT_SUPPORTED - ERR_CODE_DIAG_BASE], "TestCase Not Supported");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PING_FAILED - ERR_CODE_DIAG_BASE], "System Command Ping Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DIAG_TEST_NOT_IN_PROGRESS - ERR_CODE_DIAG_BASE], "Diagnostic Test Not in Progress");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PORTIDALL_NOT_SUPPORTED - ERR_CODE_DIAG_BASE], "PortId All Not Supported");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_TSI_STREAM_RATE_INVALID - ERR_CODE_DIAG_BASE], "Invalid TSI Stream Rate");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_TSI_STREAM_ID_INVALID - ERR_CODE_DIAG_BASE], "Invalid TSI StreamId");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_CPLD_READ_REG_FAILED - ERR_CODE_DIAG_BASE], "CPLD Read Register Failed");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DSP_UNREACH - ERR_CODE_DIAG_BASE], "DSP Unreachable");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_DSP_RDWR_TIMEOUT_EXPIRY - ERR_CODE_DIAG_BASE], "DSP Read/Write Timeout Expired");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_SYS_FAILED - ERR_CODE_DIAG_BASE], "System Failure");
  strcpy((char *)libGlobalParam.errCodeString[ERROR_PIPE_CREATE_FAILED - ERR_CODE_DIAG_BASE], "Pipe Creation Failed");

  /* Framer error Code String */
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_CANNOT_OPEN_PORTID - ERR_CODE_FRAMER_BASE], "Cannot open Framer PortId");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_PORT_ALREADY_ENABLED - ERR_CODE_FRAMER_BASE], "Framer Port Already Enabled");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_PORT_ALREADY_DISABLED - ERR_CODE_FRAMER_BASE], "Framer Port Already Disabled");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_LOOPBACK_ALREADY_ENABLED - ERR_CODE_FRAMER_BASE], "Framer Loopback Already Enabled");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_LOOPBACK_ALREADY_DISABLED - ERR_CODE_FRAMER_BASE], "Framer Loopback Already Disabled");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_PORTID_INVALID - ERR_CODE_FRAMER_BASE], "Invalid Framer PortId");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_LOOPBBACK_TYPE_INVALID - ERR_CODE_FRAMER_BASE], "Framer Invalid Loopback Type");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_ENCODE_TYPE_INVALID - ERR_CODE_FRAMER_BASE], "Framer Invalid Encode Type");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_FRAMING_OPTION_INVALID - ERR_CODE_FRAMER_BASE], "Framer Invalid Framing option");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_SIG_STRENGTH_INVALID - ERR_CODE_FRAMER_BASE], "Framer Invalid Signal Strength");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_CLOCK_PORT_IN_CONFIG_LIST - ERR_CODE_FRAMER_BASE], "Framer Clock Port in Config List");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_OTHER - ERR_CODE_FRAMER_BASE], "Any Other Framer Error");
  strcpy((char *)libGlobalParam.errCodeString[ERR_ALREADY_ACTIVE - ERR_CODE_FRAMER_BASE], "Card already Active");
  strcpy((char *)libGlobalParam.errCodeString[ERR_PORTID_NOT_IN_CONFIGURED_LIST - ERR_CODE_FRAMER_BASE], "Framer Port not in Config List");
  strcpy((char *)libGlobalParam.errCodeString[ERR_SLOTID_INVALID - ERR_CODE_FRAMER_BASE], "Invalid SlotId");
  strcpy((char *)libGlobalParam.errCodeString[ERR_LOS_RAISED - ERR_CODE_FRAMER_BASE], "LOS Raised");
  strcpy((char *)libGlobalParam.errCodeString[ERR_FRAMER_PORT_NOT_ACTIVATED - ERR_CODE_FRAMER_BASE], "Framer Port not activated");
  strcpy((char *)libGlobalParam.errCodeString[ERR_CARDTYPE_INVALID - ERR_CODE_FRAMER_BASE], "Invalid CardType");
  strcpy((char *)libGlobalParam.errCodeString[ERR_CARDSTATE_INVALID - ERR_CODE_FRAMER_BASE], "Invalid CardState");
  strcpy((char *)libGlobalParam.errCodeString[ERR_SYSTEMTYPE_INVALID - ERR_CODE_FRAMER_BASE], "Invalid SystemState");
}

I_U32 initDiagLibrary()
{
  initParamData();
  initGlobalStructData();
  initTestCaseString();
  initTestCaseIdString();
  initTestResultString();
  initErrCodeString();
  LOG_PRINT(CRITICAL,"initDiagLibrary called");
  return DIAG_LIBINIT_SUCCESS;
}
