
#  Add PSCH Instance

MAINOPTION=0
SETCNTOPTION=21
ENTITY=166       #PSCH Entity Id
PSCHCLSID=1     #PSCH Class Id
INSTCNTPSCH=20  #PSCH Instance Count
INSTEXIT=27

$TESTSTUBS_PATH/INSTLIB_DB_STUB << %%
$MAINOPTION
$ENTITY
$PSCHCLSID
$SETCNTOPTION
$INSTCNTPSCH
$INSTEXIT
%%
