/******************************************************************************
**      FUNCTION:
**         Contains error definitions for SCCP.
**
*******************************************************************************
**
**      FILE NAME:
**           sc_error.h
**
**      DESCRIPTION:
**         This file contains definitions for SCCP related errors
**
**       DATE          NAME           REFERENCE            REASON
**       ----          ----           ---------            ------
**
**      29Nov'02   Suyash Tripathi                 GTT related err codes
**      04Aug'98   Praneet Khare                   Adding Conn Oriented
**                                                        error codes
**      20Jan98    GAURAV.TANEJA     HSS:????????         ORIGINAL
**
**
**      Copyright 1998, Hughes Software Systems, Inc.
**
******************************************************************************/

#ifndef _SC_ERROR_H_
#define _SC_ERROR_H_

#include "sc_s7gl.h"

#define ESCCP_BASE_ERROR_CODE    SS7_SCCP_ERR_START

#define ESCCP_INVALID_AFFECTED_SUBSYSTEM  (ESCCP_BASE_ERROR_CODE+1)
#define ESCCP_INVALID_CALLED_ADDR         (ESCCP_BASE_ERROR_CODE+2)
#define ESCCP_INVALID_CALLING_ADDR        (ESCCP_BASE_ERROR_CODE+3)
#define ESCCP_INVALID_IMPORTANCE          (ESCCP_BASE_ERROR_CODE+4)
#define ESCCP_INVALID_LOG_USER_ID         (ESCCP_BASE_ERROR_CODE+5)
#define ESCCP_INVALID_RETURN_OPTION       (ESCCP_BASE_ERROR_CODE+6)
#define ESCCP_INVALID_SEQUENCE_CONTROL    (ESCCP_BASE_ERROR_CODE+7)
#define ESCCP_INVALID_USER_STATUS         (ESCCP_BASE_ERROR_CODE+8)
#define ESCCP_EXCEED_MAX_GT_LEN           (ESCCP_BASE_ERROR_CODE+9)
#define ESCCP_UNSUPPORTED_PROTOCOL_CLASS  (ESCCP_BASE_ERROR_CODE+10)
#define ESCCP_SS_ALREADY_EXISTS           (ESCCP_BASE_ERROR_CODE+11)
#define ESCCP_SP_ALREADY_EXISTS           (ESCCP_BASE_ERROR_CODE+12)

#define ESCCP_INVALID_TIMER_ID            (ESCCP_BASE_ERROR_CODE+13)
#define ESCCP_INVALID_POINT_CODE          (ESCCP_BASE_ERROR_CODE+14)
#define ESCCP_INVALID_AFFECTED_SIGNALLING_POINT  (ESCCP_BASE_ERROR_CODE+16)

#define ESCCP_SCMG_MSG_TOO_SHORT          (ESCCP_BASE_ERROR_CODE+17)
#define ESCCP_USER_ALREADY_REGISTERED     (ESCCP_BASE_ERROR_CODE+18)
#define ESCCP_USER_UNEQUIPPED             (ESCCP_BASE_ERROR_CODE+19)
#define ESCCP_STATUS_REQ_FOR_UNKNOWN_SUBSYSTEM  (ESCCP_BASE_ERROR_CODE+20)
#define ESCCP_UDT_MSG_TOO_SHORT           (ESCCP_BASE_ERROR_CODE+21)
#define ESCCP_INVALID_SCCP_PARAM          (ESCCP_BASE_ERROR_CODE+22)
#define ESCCP_XUDT_MSG_TOO_SHORT          (ESCCP_BASE_ERROR_CODE+23)


#define ESCCP_SP_ALREADY_CONFIGURED             (ESCCP_BASE_ERROR_CODE + 24)
#define ESCCP_INVALID_SP_ID                     (ESCCP_BASE_ERROR_CODE + 25)
#define ESCCP_INVALID_SS_ID                     (ESCCP_BASE_ERROR_CODE + 26)
#define ESCCP_SS_ALREADY_CONFIGURED             (ESCCP_BASE_ERROR_CODE + 27)
#define ESCCP_INVALID_SSN                       (ESCCP_BASE_ERROR_CODE + 28)
#define ESCCP_INVALID_CSP_ID                    (ESCCP_BASE_ERROR_CODE + 29)
#define ESCCP_INVALID_CSS_ID                    (ESCCP_BASE_ERROR_CODE + 30)
#define ESCCP_SS_DEFINED_FOR_SP                 (ESCCP_BASE_ERROR_CODE + 31)
#define ESCCP_SP_IS_CSP                         (ESCCP_BASE_ERROR_CODE + 32)
#define ESCCP_SS_IS_CSS                         (ESCCP_BASE_ERROR_CODE + 33)
#define ESCCP_DB_CSP_NO_SPACE                   (ESCCP_BASE_ERROR_CODE + 34)
#define ESCCP_DB_CSS_NO_SPACE                   (ESCCP_BASE_ERROR_CODE + 35)
#define ESCCP_INVALID_PC_VALUE                  (ESCCP_BASE_ERROR_CODE + 36)
#define ESCCP_INVALID_PROV_CMD                  (ESCCP_BASE_ERROR_CODE + 37)
#define ESCCP_INVALID_STAT_CMD                  (ESCCP_BASE_ERROR_CODE + 38)
#define ESCCP_INVALID_TIMER_CONFIG_ID           (ESCCP_BASE_ERROR_CODE + 39)
#define ESCCP_INVALID_TIMER_VAL                 (ESCCP_BASE_ERROR_CODE + 40)
#define ESCCP_ALREADY_INIT                      (ESCCP_BASE_ERROR_CODE + 41)
#define ESCCP_UNREGISTERED_USER                 (ESCCP_BASE_ERROR_CODE + 42)
#define ESCCP_UNEQUIPPED_USER                   (ESCCP_BASE_ERROR_CODE + 43)
#define ESCCP_CL_MSG_SYNTAX_ERR                 (ESCCP_BASE_ERROR_CODE + 44)
#define ESCCP_UNEQUIPPED_USER_DESIRES_SERVICE   (ESCCP_BASE_ERROR_CODE + 45)
#define ESCCP_WRONG_DATA_TYPE                   (ESCCP_BASE_ERROR_CODE + 46)
#define ESCCP_SS_NOT_CONFIGURED                 (ESCCP_BASE_ERROR_CODE + 47)
#define ESCCP_SP_NOT_CONFIGURED                 (ESCCP_BASE_ERROR_CODE + 48)
#define ESCCP_INVALID_SM_COMMAND                (ESCCP_BASE_ERROR_CODE + 49)
#define ESCCP_INVALID_SM_CATEGORY               (ESCCP_BASE_ERROR_CODE + 50)
#define ESCCP_REDN_DISABLED                     (ESCCP_BASE_ERROR_CODE + 51)

/* Added for event alarms */
#define ESCCP_INVALID_OBJECT_ID_FLAG		(ESCCP_BASE_ERROR_CODE + 52)

#define ESCCP_INVALID_ERICSSON_GTI		(ESCCP_BASE_ERROR_CODE + 53)
#define ESCCP_INVALID_NUM_TIMERS		(ESCCP_BASE_ERROR_CODE + 54)

#define ESCCP_INVALID_REG_ENTRY_ID		(ESCCP_BASE_ERROR_CODE + 55)
#define ESCCP_REG_ENTRY_NOT_USED		(ESCCP_BASE_ERROR_CODE + 56)

#define ESCCP_REDN_SEND_UPDATE_FAILED	(ESCCP_BASE_ERROR_CODE + 57)

#ifdef DISTRIBUTED_SCCP
#define ESCCP_INVALID_MATE_COMMAND (ESCCP_BASE_ERROR_CODE + 58)
#define ESCCP_INVALID_MATE_CATEGORY (ESCCP_BASE_ERROR_CODE + 59)
#define ESCCP_UNABLE_TO_NOTIFY_SELF_STATUS (ESCCP_BASE_ERROR_CODE + 60)
#define ESCCP_INVALID_INSTANCE_ID (ESCCP_BASE_ERROR_CODE + 61)
#endif

#define ESCCP_SSN_ALREADY_EXIST         (ESCCP_BASE_ERROR_CODE + 62)
#define ESCCP_LOG_USER_ID_ALREADY_EXIST (ESCCP_BASE_ERROR_CODE + 63)
#define ESCCP_INVALID_LOG_ID_VALUE      (ESCCP_BASE_ERROR_CODE + 65)
#define ESCCP_MAX_SSN_EXCEEDED          (ESCCP_BASE_ERROR_CODE + 66)
#define ESCCP_NOT_IN_INITIALIZED_STATE  (ESCCP_BASE_ERROR_CODE + 67)

#ifdef SCCP_INCLUDE_CO_SERVICE

#define ESCCP_CO_BASE_ECODE                     (ESCCP_BASE_ERROR_CODE + 70)

#define ESCCP_DUPLICATE_CONN_REQ                (ESCCP_CO_BASE_ECODE + 0)
#define ESCCP_INVALID_EXP_DATA_SELECTION        (ESCCP_CO_BASE_ECODE + 1)
#define ESCCP_INVALID_CORR_ID                   (ESCCP_CO_BASE_ECODE + 2)
#define ESCCP_INVALID_LOG_UID                   (ESCCP_CO_BASE_ECODE + 3)
#define ESCCP_INVALID_PROTO_CLASS               (ESCCP_CO_BASE_ECODE + 4)
#define ESCCP_INVALID_CREDIT                    (ESCCP_CO_BASE_ECODE + 5)
#define ESCCP_UNSPECIFIED_API_FOR_ETSI          (ESCCP_CO_BASE_ECODE + 6)

/* Ericsson changes */
#define ESCCP_UNSPECIFIED_API_FOR_ERICSSON      (ESCCP_CO_BASE_ECODE + 7)

/* SPR 1770 */
#define ESCCP_SERVICE_CLASS_MISMATCH 		(ESCCP_CO_BASE_ECODE + 8)	

#define ESCCP_INVALID_CONN_ID				(ESCCP_CO_BASE_ECODE + 9)
#define ESCCP_CONN_INACTIVE					(ESCCP_CO_BASE_ECODE + 10)

#endif


/************ GTT RELATED ERROR CODES *******/

#define ESCCP_GTT_MIN_ERR           	0x0A28

/* error codes */
#define ESCCP_GTT_INVALID_MTPSAP  				ESCCP_GTT_MIN_ERR + 1
#define ESCCP_GTT_INVALID_DPC 					ESCCP_GTT_MIN_ERR + 2
#define ESCCP_GTT_NO_SSNS_FOUND 				ESCCP_GTT_MIN_ERR + 3
#define ESCCP_GTT_INVALID_GTI 					ESCCP_GTT_MIN_ERR + 4
#define ESCCP_GTT_NO_TRANS_RULE_FOUND			ESCCP_GTT_MIN_ERR + 5 
#define ESCCP_GTT_NO_FUNCTION_FOUND 			ESCCP_GTT_MIN_ERR + 6
#define ESCCP_GTT_MTPSAP_EXIST_ALREADY 			ESCCP_GTT_MIN_ERR + 7
#define ESCCP_GTT_MTPSAP_LIST_OVERFLOW 			ESCCP_GTT_MIN_ERR + 8
#define ESCCP_GTT_MTPSAP_DOESNT_EXIST 			ESCCP_GTT_MIN_ERR + 9
#define ESCCP_GTT_DPC_EXISTS_ALREADY 			ESCCP_GTT_MIN_ERR + 10
#define ESCCP_GTT_MTPSAP_HAS_MAX_DPCS_ALREADY 	ESCCP_GTT_MIN_ERR + 11 
#define ESCCP_GTT_DPC_LIST_OVERFLOW 			ESCCP_GTT_MIN_ERR + 12
#define ESCCP_GTT_DPC_DOESNT_EXIST 				ESCCP_GTT_MIN_ERR + 13
#define ESCCP_GTT_SSN_DOESNT_EXIST 				ESCCP_GTT_MIN_ERR + 15 
#define ESCCP_GTT_SSN_EXISTS_ALREADY 			ESCCP_GTT_MIN_ERR + 16
#define ESCCP_GTT_SSN_LIST_OVERFLOW 			ESCCP_GTT_MIN_ERR + 17
#define ESCCP_GTT_DPC_HAS_MAX_SSNS_ALREADY 		ESCCP_GTT_MIN_ERR + 18

#define ESCCP_GTT_GTI_TABLE_OVERFLOW 			ESCCP_GTT_MIN_ERR + 20
#define ESCCP_GTT_GTI_FUNCTION_LIST_OVERFLOW 	ESCCP_GTT_MIN_ERR + 21
#define ESCCP_GTT_TRANS_FUNC_LIST_OVERFLOW 		ESCCP_GTT_MIN_ERR + 22
#define ESCCP_GTT_RULE_LIST_OVERFLOW 			ESCCP_GTT_MIN_ERR + 23
#define ESCCP_GTT_FUNCTION_RULES_LIST_OVERFLOW 	ESCCP_GTT_MIN_ERR + 24
#define ESCCP_GTT_TRANS_FUN_INVALID_FOR_GIVEN_GTI 	ESCCP_GTT_MIN_ERR + 25
#define ESCCP_GTT_TRANS_RULE_ID_INVALID_FOR_GIVEN_TRANS_FUN_AND_GTI ESCCP_GTT_MIN_ERR + 26
#define ESCCP_GTT_NO_MTPSAP_FOUND  				ESCCP_GTT_MIN_ERR + 27

#define ESCCP_GTT_NO_DPCS_FOUND 				ESCCP_GTT_MIN_ERR + 29

#define ESCCP_GTT_INVALID_DPC_COUNT 			ESCCP_GTT_MIN_ERR + 	30

#define ESCCP_GTT_NO_TRANS_FUN_FOUND_WITH_GIVEN_ESCAPE_CODE ESCCP_GTT_MIN_ERR + 31

#define  ESCCP_GTT_SSN_NOT_AVAILABLE 			ESCCP_GTT_MIN_ERR + 32
#define  ESCCP_GTT_SSN_INVALID 					ESCCP_GTT_MIN_ERR + 33
#define  ESCCP_GTT_DPC_NOT_AVAILABLE 			ESCCP_GTT_MIN_ERR + 34
#define  ESCCP_GTT_DPC_INVALID 					ESCCP_GTT_MIN_ERR + 35
#define ESCCP_GTT_MTPSAP_INVALID 				ESCCP_GTT_MIN_ERR + 36
#define ESCCP_GTT_SSN_NOT_REGISTERED 			ESCCP_GTT_MIN_ERR + 37
#define ESCCP_GTT_NO_SSN_FOUND  				ESCCP_GTT_MIN_ERR + 38
#define ESCCP_GTT_NO_DPC_FOUND_FOR_GIVEN_SSN 	ESCCP_GTT_MIN_ERR + 39
#define  ESCCP_GTT_STATUS_INDICATOR_ERROR 		ESCCP_GTT_MIN_ERR + 40

#define I ESCCP_GTT_MIN_ERR + 41

#define     ESCCP_GTT_BUFFER_INSUFF_FOR_ADD_MTPSAP             I+2
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_ADD_DPC                I+3
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_ADD_SSN                I+4


#define     ESCCP_GTT_BUFFER_INSUFF_FOR_DEL_MTPSAP             I+5
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_DEL_DPC                I+6
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_DEL_SSN                I+7
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_GET_TRANS_FUNC_LIST    I+8
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_GET_SSNS_PER_DPC       I+9
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_GET_DPCS_PER_MTPSAP    I+10
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_GET_MTPSAP_LIST        I+11
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_DEL_FROM_DPC_SSN_TABLE_MAX    I+12
#define     ESCCP_GTT_INVALID_GLOBAL_TITLE_INDICATOR                  ESCCP_GTT_INVALID_GTI
#define     ESCCP_GTT_ACTION_ARRAY_OVERFLOW                         I+14
#define     ESCCP_GTT_BUFFER_INSUFF_FOR_ADD_TRANS_RULE               I+15
#define     ESCCP_GTT_INVALID_OPERATION_CODE                         I+16
#define     ESCCP_GTT_INVALID_COMMAND                                I+17
#define     ESCCP_GTT_INVALID_COMMAND_CATEGORY                       I+18
#define     ESCCP_GTT_INVALID_NUMBER_OF_GT_DIGITS                    I+20
#define     ESCCP_GTT_INVALID_TABLE_MASK                             I+21
#define     ESCCP_GTT_MIN_GREATER_THAN_MAX                           I+22
#define     ESCCP_GTT_SSN_NOT_FOUND                                  I+23
#define     ESCCP_GTT_DPC_NOT_FOUND                                  I+24
#define     ESCCP_GTT_DPC_SSN_NOT_FOUND                              I+25


#define     ESCCP_GTT_INVALID_LENGTH			                I+29
#define     ESCCP_GTT_DPC_ARRAY_SIZE_INSUFF_FOR_PROCESSING           I+30

#define     ESCCP_GTT_DIGITS_ALREADY_EXISTS_IN_SSN_TABLE             I+31
#define     ESCCP_GTT_SSN_ARRAY_OVERFLOW                             I+32
#define     ESCCP_GTT_DIGITS_ALREADY_EXISTS_IN_DPC_SSN_TABLE         I+33
#define     ESCCP_GTT_DPC_SSN_ARRAY_OVERFLOW                         I+34
#define     ESCCP_GTT_DIGITS_NOT_FOUND_IN_SSN_TABLE                  I+35
#define     ESCCP_GTT_DIGITS_NOT_FOUND_IN_DPC_TABLE                  I+36
#define     ESCCP_GTT_DIGITS_NOT_FOUND_IN_DPC_SSN_TABLE              I+37
#define     ESCCP_GTT_DIGITS_ALREADY_EXISTS_IN_DPC_TABLE             I+38
#define     ESCCP_GTT_DPC_ARRAY_OVERFLOW                             I+39

#define    ESCCP_GTT_DEL_FROM_DPC_SSN_TABLE_MASK                     I+41
#define    ESCCP_GTT_ACTION_ARRAY_UNDERFLOW			       I+42
#define    ESCCP_GTT_NO_OF_ACTION_ERROR			       I+43
#define    ESCCP_GTT_INVALID_ACTION_ELEM			       I+44
#define    ESCCP_GTT_INVALID_NAI				    	I+45
#define    ESCCP_GTT_INVALID_NP				    	I+46
#define    ESCCP_GTT_INVALID_ES				    	I+47
#define    ESCCP_GTT_INVALID_ESC_CODE			     	I+48

/* Init errors */
#define	   ESCCP_GTT_ALREADY_INIT					I+49
#define    ESCCP_GTT_INVALID_STANDARD				I+50
#define    ESCCP_GTT_INVALID						I+51
#define    ESCCP_GTT_INVALID_API_ID					I+52
#define    ESCCP_GTT_INVALID_VERSION_ID				I+53
#define	   ESCCP_GTT_INVALID_API_LEN					I+54
#define    ESCCP_GTT_MEMORY_ALLOCATION_FAILURE			I+55

/* Operation/Action  errors */
#define	   ESCCP_GTT_GTT_CHECK_FOR_SSN_IN_AI 			I+56
#define	   ESCCP_GTT_GTT_SUBSTITUTE_WITH_VALUE			I+57	
#define	   ESCCP_GTT_GTT_COMPARE_WITH_VALUE				I+58	

/* Invalid number of elements */
#define	   ESCCP_GTT_INVALID_NUM_OF_ELEMS	    	    I+59	
#define	   ESCCP_GTT_INVALID_OUTPUT_GT   	    	    I+60
#define	   ESCCP_GTT_INVALID_LOCAL_REMOTE_FLAG	        I+61
#define	   ESCCP_GTT_INVALID_ESCAPE_USED_FLAG	        I+62
#define	   ESCCP_GTT_INVALID_NUMBER_OF_MIN_MAX_DIGITS    I+63
#define	   ESCCP_GTT_INVALID_NUMBER_OF_SKIP_DIGITS       I+64
#define	   ESCCP_GTT_DPC_SSN_INDICATOR                   I+65
#define	   ESCCP_GTT_INVALID_STATUS_VALUE                I+66
#define	   ESCCP_GTT_BUFFER_LENGTH_OVERSHOOT             I+67
#define	   ESCCP_GTT_EXTRANEOUS_BYTES_PRESENT            I+68
#define	   ESCCP_GTT_SSN_USED_IN_DPC_SSN_TABLE           I+69
#define	   ESCCP_GTT_DPC_USED_IN_DPC_SSN_TABLE           I+70
#define	   ESCCP_GTT_MTPSAP_USED_IN_DPC_SSN_TABLE        I+71
#define	   ESCCP_GTT_SSN_USED_IN_SSN_TABLE               I+72
#define	   ESCCP_GTT_DPC_USED_IN_DPC_TABLE               I+73
#define	   ESCCP_GTT_MTPSAP_USED_IN_DPC_TABLE            I+74


#endif /* _SC_ERROR_H_ */
