
#  Add PSSCM Instance

MAINOPTION=0
SETCNTOPTION=21
ENTITY=169       #PSSCM Entity Id
PSSCMCLSID=2     #PSSCM Class Id
INSTCNTPSSCM=5  #PSSCM Instance Count
INSTEXIT=27

$TESTSTUBS_PATH/INSTLIB_DB_STUB << %%
$MAINOPTION
$ENTITY
$PSSCMCLSID
$SETCNTOPTION
$INSTCNTPSSCM
$INSTEXIT
%%
