/***************************************************************************
**  FILE NAME:
**      dsccp.h
**
****************************************************************************
**
**  FUNCTION:
**
**
**  DESCRIPTION:
**
**
**  DATE     NAME              REF#     REASON
**  -------  ----------------  -----    -------------------------------------
**  21MAY'2001 Salil K Agrawal           Fixed SPR # 8744
**  26Dec'2001 Prateek Bidwalkar ----    Fixed SPR # 7450
**  26aug'2001 Pawanish Kumar Modi ----    Original
**  06mar'2001 Sachin Bhatia 	   ----    Adding Dereg functionality
**
**  Copyright 2001, Hughes Software Systems
***************************************************************************/

#ifndef _DSCCP_H_
#define _DSCCP_H_

#ifdef DISTRIBUTED_SCCP

#define DSCCP_MAX_INSTANCES 16


#define DSCCP_DATA_OFFSET 7
#define DSCCP_CAT_OFFSET 5
#define DSCCP_CMD_OFFSET 6



/** DSCCP states **/
#define DSCCP_INSTANCE_STATUS_DEAD 0
#define DSCCP_INSTANCE_STATUS_UNCONFIG 1
#define DSCCP_INSTANCE_STATUS_CONFIG 2
#define DSCCP_INSTANCE_STATUS_ALIVE 3
/* SPR # 7450 Fix Start */
#define DSCCP_INSTANCE_STATUS_DEACTIVATED 4
#define DSCCP_INSTANCE_STATUS_DEACTIVATED_UNCONFIG 5
#define DSCCP_INSTANCE_STATUS_DEACTIVATED_CONFIG 6
#define DSCCP_INSTANCE_STATUS_REACTIVATED 7
/* SPR # 7450 Fix End */



#define DSCCP_CONF_END_MSG_LEN 7
#define DSCCP_MAX_DATA_LEN 512
#define DSCCP_CONF_REQUEST_MSG_LEN 8
#define DSCCP_CONF_REQUEST_MSG_NELEM 3
#define DSCCP_CONF_END_MSG_LEN 7
#define DSCCP_CONF_END_NELEM 2
#define DSCCP_SP_CONF_RES_MSG_NELEM 4
#define DSCCP_SS_CONF_RES_MSG_NELEM 4
#define DSCCP_REG_CONF_RES_MSG_NELEM 4
#define DSCCP_INSTANCE_STATUS_CONF_RES_MSG_NELEM 4
#define DSCCP_CONF_REQUEST_MSG_LEN 8
#define DSCCP_HM_SELF_STATUS_MSG_LEN 10
#define DSCCP_HM_SELF_STATUS_NELEM 4
#define DSCCP_CONF_TIMER_BUF_LEN 2
#define DSCCP_SP_STATUS_LEN 18
#define DSCCP_SP_STATUS_NELEM 10
#define DSCCP_SS_STATUS_LEN 13
#define DSCCP_SS_STATUS_NELEM 5
#define DSCCP_SCCP_STATUS_LEN 14
#define DSCCP_SCCP_STATUS_NELEM 4
#define DSCCP_REG_USER_MSG_LEN 14
#define DSCCP_REG_USER_MSG_NELEM 5
/* SPR # 7450 Fix Start */
#define DSCCP_DEACTIVATED_MATE_STATUS_NELEM 1
#define DSCCP_UPDATE_DEACTIVATED_MATE_STATUS_NELEM 1
/* SPR # 7450 Fix End */
/* SPR # 8744 Fix Start */
#define DSCCP_CONG_STATUS_LEN (API_HEADER_LEN + 4)
/* SPR # 8744 Fix End */


/** Instance Id 0 is invalid */
#define DSCCP_INVALID_INSTANCE_ID 0


#define MAX_LOCAL_USERS 10

/** DSCCP API categories **/
#define DSCCP_CATEGORY_BASE 1

#define DSCCP_API_CAT_CONFIG (DSCCP_CATEGORY_BASE + 1)
#define DSCCP_API_CAT_SCMG (DSCCP_CATEGORY_BASE + 2)
#define DSCCP_API_CAT_SCOC (DSCCP_CATEGORY_BASE + 3)
#define DSCCP_API_CAT_SCLC (DSCCP_CATEGORY_BASE + 4)
#define DSCCP_API_CAT_HM (DSCCP_CATEGORY_BASE + 5)


/** DSCCP commands  **/


#define DSCCP_COMMAND_BASE 1

#define DSCCP_API_CMD_CONFIG_REQ  (DSCCP_COMMAND_BASE +1)
#define DSCCP_API_CMD_CONFIG_SP_INFO (DSCCP_COMMAND_BASE +2)
#define DSCCP_API_CMD_CONFIG_SS_INFO (DSCCP_COMMAND_BASE +3)
#define DSCCP_API_CMD_CONFIG_REG_INFO (DSCCP_COMMAND_BASE +4)
#define DSCCP_API_CMD_CONFIG_END (DSCCP_COMMAND_BASE +5)
#define DSCCP_API_CMD_COMP_MATE_STATUS_INFO (DSCCP_COMMAND_BASE +6)
#define DSCCP_API_CMD_SCMG_SP_STATUS (DSCCP_COMMAND_BASE +7)
#define DSCCP_API_CMD_SCMG_SS_STATUS (DSCCP_COMMAND_BASE +8)
#define DSCCP_API_CMD_SCMG_REG_STATUS (DSCCP_COMMAND_BASE +9)
#define DSCCP_API_CMD_SCOC_DISC_REQ (DSCCP_COMMAND_BASE + 10)
#define DSCCP_API_CMD_MATE_STATUS_CHANGE (DSCCP_COMMAND_BASE + 11)
#define DSCCP_API_CMD_SELF_STATUS_CHANGE (DSCCP_COMMAND_BASE + 12)
#define DSCCP_API_CMD_SCLC_REASS_INFO_REQ (DSCCP_COMMAND_BASE + 13)
#define DSCCP_API_CMD_SCLC_REASS_INFO_RESP (DSCCP_COMMAND_BASE + 14)
#define DSCCP_API_CMD_SCLC_XUDT (DSCCP_COMMAND_BASE + 15)
#define DSCCP_API_CMD_SCMG_SCCP_STATUS (DSCCP_COMMAND_BASE + 16)
#define DSCCP_API_CMD_SCMG_DEREG_STATUS (DSCCP_COMMAND_BASE + 17)
/* SPR # 7450 Fix Start */
#define DSCCP_API_CMD_DEACTIVATED_MATE_STATUS (DSCCP_COMMAND_BASE + 17)
#define DSCCP_API_CMD_UPDATE_DEACTIVATED_MATE_STATUS (DSCCP_COMMAND_BASE + 18)
/* SPR # 7450 Fix End */

/* SPR # 8744 Fix Start */
#define DSCCP_API_CMD_SCMG_CONG_STATUS (DSCCP_COMMAND_BASE + 19)
/* SPR # 8744 Fix End */

#endif /* DISTRIBUTED_SCCP */

#endif /* _DSCCP_H_ */
