#ifndef _CFG_STUB_RANGE_CHECK_H_
#define _CFG_STUB_RANGE_CHECK_H_

void nsvcTableRangeChkTest();
void frLinkTableRangeChkTest();
void repInfoTableRangeChkTest();
void bssPsTableRangeChkTest();
void lepInfoTableRangeChkTest();
void gbInterfaceTableRangeChkTest();
void psCellTableRangeChkTest();
void cellTableRangeChkTest();
void removeNsvcTable(I_U16 nsvcId);
void removeNsvcStatusTable(I_U16 nsvcId);
void removeNsvcConnIdMapTable(I_U16 nsvcId);
void removeFrLinkTable(I_U16 frChnId);
void   removeFrLinkStatusTable(I_U16 frChnId);
void removeRepInfoTable(I_S8 *rep);
void removeBssPsTable(I_U16 bssPsId);
void removeLepInfoTable(I_S8 *lep);
void removeGbInterfaceTable(I_U16    gbIfIndex);
void removeCellPerTable(I_U32 cellId, I_U32 lac);
void setFrLinkTable();
void setBssPsPreConfigTable();
void setGbInterfaceTable();
void setE1PerTable();
void setArfcnListTable(CellPerTableApi *cellPerTableApiPtr);
void setRaTable();
void setCellPerTable();

void removeAllFromFrLinkTable();
void removeAllFromNsvcTable();
void removeAllFromFrLinkExtE1TsMccE1TsMapTable();
void removeAllFromPsCellTable();
void removeAllFromCellTable();
void removeAllFromGbInterfaceTable();
void removeAllFromRepInfoTable();
void removeAllFromLepInfoTable();
void removeAllFromRaTable();
void removeAllFromLaTable();

void insertIntoFrLinkExtE1TsMccE1TsMapTable(I_U16 frChnId, I_U16 e1Id, I_U16 numRows);
void insertIntoFrLinkTable(I_U16 frChnId, I_U16 e1Id);
void insertIntoNsvcTable(I_U16 nsvcId, I_U16 frChnId, I_U32 adminState);
void insertIntoLepInfoTable(I_S8 *lepInfoIndex);
void insertIntoRepInfoTable(I_S8 *repInfoIndex);
void insertIntoGbInterfaceTable(I_U16 gbIfIndex, I_U32 transportType);
void setMaxNumNsvcsIngbInterfaceTable(I_U16 gbIfIndex, I_U32 transportType, I_U16 maxNum);
void insertIntoPsCellTable(I_U16 cellId, I_U16 lac, I_U8 rac);
void insertIntoCellTable(I_U16 cellId, I_U16 lac, I_U32 adminState, I_U32 psAllowed);
void insertIntoRaTable(I_U16 lac, I_U8 rac);
void insertIntoLaTable(I_U16 lac);
void insertIntoBssTable(I_U16 bssIndex, I_U32 adminState);
void insertIntoRaTableChnGrpTable(I_U16 cellId, I_U16 lac);
void insertIntoArfcnListTable(I_U32 band, I_U32 arfcn);
void updateGprsEnabledInBssTable(I_U16 bssIndex, I_Bool gprsEnabled);
void CfgDelHndlr1();
void CfgDelHndlr2();
void CfgDelHndlr3();
void CfgDelHndlr4();
void CfgDelHndlr5();
void CfgDelHndlr6();
void CfgDelHndlr7();
void CfgDelHndlr8();
void CfgDelHndlr9();
void CfgDelHndlr10();
void CfgDelHndlr11();
void CfgDelHndlr12();
void CfgDelHndlr13();
void CfgDelHndlr14();
void CfgSetHndlr1();
void CfgSetHndlr2();
void CfgSetHndlr3();
void CfgSetHndlr4();
void CfgSetHndlr5();
void CfgSetHndlr6();
void CfgSetHndlr7();
void CfgSetHndlr8();
void CfgSetHndlr9();
void CfgSetHndlr10();
void CfgSetHndlr11();
void CfgSetHndlr12();
void CfgSetHndlr13();
void CfgSetHndlr14();
void CfgSetHndlr15();
void CfgSetHndlr16();
void CfgSetHndlr17();
void CfgSetHndlr18();
void CfgSetHndlr19();
void CfgSetHndlr20();
void CfgSetHndlr21();
void CfgSetHndlr22();
void CfgSetHndlr23();
void CfgSetHndlr24();
void CfgSetHndlr25();
void CfgSetHndlr26();
void CfgSetHndlr27();
void CfgSetHndlr28();
void CfgSetHndlr29();
void CfgSetHndlr30();
void CfgSetHndlr31();
void CfgSetHndlr32();
void CfgSetHndlr33();
void CfgSetHndlr34();
void CfgSetHndlr35();
void CfgSetHndlr36();
void CfgSetHndlr37();
void CfgSetHndlr38();
void CfgSetHndlr39();
void CfgSetHndlr40();
void CfgSetHndlr41();
void CfgSetHndlr42();
void CfgSetHndlr43();
void CfgSetHndlr44();
void CfgSetHndlr45();

#endif
