#ifndef _CFG_STUB_BSS_OBJECT_HANDLER_H_
#define _CFG_STUB_BSS_OBJECT_HANDLER_H_
I_Bool cfgUpdateBssTableToDb();
I_Bool cfgUpdateBssTableToLocalBuffer();
void cfgSendBscApiSetBssTable();
void CfgBssObjHndlr1();
void CfgBssObjHndlr2();
void CfgBssObjHndlr3();
void CfgBssObjHndlr4();
void CfgBssObjHndlr5();
void CfgBssObjHndlr6();
void CfgBssObjHndlr7();
void CfgBssObjHndlr8();
void CfgBssObjHndlr9();
void CfgBssObjHndlr10();
void CfgBssObjHndlr11();
void CfgBssObjHndlr12();
void CfgBssObjHndlr13();
void CfgBssObjHndlr14();
void CfgBssObjHndlr15();
void CfgBssObjHndlr16();
void CfgBssObjHndlr17();
void CfgBssObjHndlr18();
void CfgBssObjHndlr19();
void CfgBssObjHndlr20();
void CfgBssObjHndlr21();
void CfgBssObjHndlr22();
void CfgBssObjHndlr23();
void CfgInitHndlr2();
#endif
