#ifndef _OAMCFG_HASHDEFS_H_
#define _OAMCFG_HASHDEFS_H_
/* hash define used in OAMCFG process */

#define CFG_TERMINATE_CODE -1

#define OAMCFG_Q_PERM  0777
#define LOG_FILE_NAME_SIZE  11
#define MAX_ERR_LOG_FL_SZ  1000

#define OAMCFG_ERR_LOG  "oamcfg.log"

#define MSGTYP0  0
#define MSGFLG0  0

/* cfg response recieved timeout */
#define CFG_OIL_RESP_TIMEOUT  5 /* in seconds */

/* Messages Instance */
#define INSTANCE1  1 /* Ideal stat */
#define INSTANCE2  2 /* Message sent to OIL */
#define INSTANCE3  3 /* SIGALRM recieved for timeout of response message */
#define INSTANCE4  4 /* Response recieved from OIL */

/* daoId of the history table */
#define HIST_DAO_ID  123456789 /* to be associated */
#define HIST_BUFFER_SIZE  12

/* tsi PP-TS stream Id */
#define SELF_PP_STREAM_ID  0x00

/* UNIX error 
#define UNIXERR  -1 */

#define INVALID   0xFF
#define FREE      0
#define BUSY      1

/* DB queries hash defines */
//#define INSERT_ID   1
//#define UPDATE_ID   2
#define UPDATE_ID   1
#define INSERT_ID   2
#define GET_ID 3
#define DELETE_ID 4

#define LSB_BIT 0x00000001
/* Hash define use for a particular tables */
/* Common hash define */
#define MAX_E1_TS    32
#define MAX_DATALINK_E1_LIST   4
#define MAX_DATALINK_TS_LIST   4

/* aifListTable */
#define MAX_AIF_E1_LIST  5
#define MAX_AIF_START_CIC_LIST   5
#define MAX_AIF_LAC_LIST 15
#define MAX_EIF_LAC_LIST 10
#define MAX_VLR_LAC_LIST 10
#define MAX_DEST_TRANSPORT_LIST 4
#define MAX_ZONE_CODE_LIST 5

/* transportListTable */
#define MAX_TRANSPORT_E1_LIST  4
#define MAX_TRANSPORT_START_CIC_LIST   4

/* Fail points or Panic points */
#define CFG_SUCCESS        0
#define CFG_FAILURE        1
#define CFG_ALLOC_FAIL     2
#define CFG_MSGEGT_FAIL    3
#define CFG_REGD_IPC_FAIL  4
#define CFG_DB_INIT_FAIL   5
#define CFG_PUT_FAIL       6
#define CFG_INSERT_FAIL    7
#define CFG_DELETE_FAIL    8
#define CFG_UPDATE_FAIL    9
#define CFG_SELECT_FAIL    10
#define CFG_MALLOC_FAIL    11
#define CFG_HIST_RECOVERY_FAIL  12
#define CFG_FILL_HIST_FAIL       13
#define CFG_MSGRCV_FAIL    14
#define CFG_DUMP_FAIL      15
#define CFG_SEND_ALLOC_FAIL   16
#define CFG_SEND_FAIL   17


#define   FALSE 0
#define   TRUE  1


#define LOCKED 0
#define UNLOCKED 1
#define SHUTDOWN 2

#define BSC_API_LOCK_BSS 2
#define BSC_API_UNLOCK_BSS 3
#define OAMS_CFG_GRHM_START_STATIC_SWITCHING 0
#define AFH_API_ALARM_MSG 1
#define BSC_API_SET_PTRXSLOTPRECONFIGTABLE 2
#define BSC_API_DEL_PTRXSLOTPRECONFIGTABLE 3
#define BSC_API_SET_PTDCCONFIGTABLE 4
#define BSC_API_DEL_PTDCCONFIGTABLE 5



#if 0
#define   BSC_API_SET_BSSTABLE SCM_MET_SET_BSSTABLE
#define   BSC_API_DEL_BSSTABLE SCM_MET_DEL_BSSTABLE  

#define   BSC_API_SET_CELLTABLE SCM_MET_SET_CELLTABLE
#define   BSC_API_DEL_CELLTABLE SCM_MET_DEL_CELLTABLE

#define   BSC_API_SET_PSCELLTABLE SCM_MET_SET_PSCELLTABLE
#define   BSC_API_DEL_PSCELLTABLE SCM_MET_DEL_PSCELLTABLE

#define   BSC_API_SET_CSEXTERNALCELLTABLE SCM_MET_SET_CSEXTERNALCELLTABLE
#define   BSC_API_DEL_CSEXTERNALCELLTABLE SCM_MET_DEL_CSEXTERNALCELLTABLE

#define   BSC_API_SET_PSEXTERNALCELLTABLE SCM_MET_SET_PSEXTERNALCELLTABLE
#define   BSC_API_DEL_PSEXTERNALCELLTABLE SCM_MET_DEL_PSEXTERNALCELLTABLE

#define   BSC_API_SET_LATABLE SCM_MET_SET_LATABLE
#define   BSC_API_DEL_LATABLE SCM_MET_DEL_LATABLE

#define   BSC_API_SET_RATABLE SCM_MET_SET_RATABLE
#define   BSC_API_DEL_RATABLE SCM_MET_DEL_RATABLE

#define   BSC_API_SET_CHNGRPTABLE SCM_MET_SET_CHNGRPTABLE
#define   BSC_API_DEL_CHNGRPTABLE SCM_MET_DEL_CHNGRPTABLE

#define   BSC_API_SET_PTRXTABLE SCM_MET_SET_PTRXTABLE
#define   BSC_API_DEL_PTRXTABLE SCM_MET_DEL_PTRXTABLE

#define   BSC_API_SET_E1TABLE SCM_MET_SET_E1TABLE
#define   BSC_API_DEL_E1TABLE SCM_MET_DEL_E1TABLE

#define   BSC_API_SET_TIMESLOTTABLE SCM_MET_SET_TIMESLOTTABLE
#define   BSC_API_DEL_TIMESLOTTABLE SCM_MET_DEL_TIMESLOTTABLE

#define   BSC_API_SET_CSINEIGHCELLSTABLE SCM_MET_SET_CSNEIGHCELLSTABLE
#define   BSC_API_DEL_CSINEIGHCELLSTABLE SCM_MET_DEL_CSNEIGHCELLSTABLE

#define   BSC_API_SET_PSNEIGHCELLSTABLE SCM_MET_SET_PSNEIGHCELLSTABLE
#define   BSC_API_DEL_PSNEIGHCELLSTABLE SCM_MET_DEL_PSNEIGHCELLSTABLE

#define   BSC_API_SET_ARFCNLISTTABLE SCM_MET_SET_ARFCNLISTTABLE
#define   BSC_API_DEL_ARFCNLISTTABLE SCM_MET_DEL_ARFCNLISTTABLE

#define   BSC_API_SET_TRAUTABLE SCM_MET_SET_TRAUCONFIGTABLE
#define   BSC_API_DEL_TRAUTABLE SCM_MET_DEL_TRAUCONFIGTABLE

#define   BSC_API_SET_AINTERFACETABLE SCM_MET_SET_AINTERFACETABLE
#define   BSC_API_DEL_AINTERFACETABLE SCM_MET_DEL_AINTERFACETABLE

#define   BSC_API_SET_SCCPSSNCONFIGTABLE SCM_MET_SET_SCCPSSNCONFIGTABLE
#define   BSC_API_DEL_SCCPSSNCONFIGTABLE SCM_MET_DEL_SCCPSSNCONFIGTABLE

#define   BSC_API_SET_SCCPCSSNCONFIGTABLE SCM_MET_SET_SCCPCSSNCONFIGTABLE
#define   BSC_API_DEL_SCCPCSSNCONFIGTABLE SCM_MET_DEL_SCCPCSSNCONFIGTABLE

#define   BSC_API_SET_SCCPBEHAVIORCONFIGTABLE SCM_MET_SET_SCCPBEHAVIORCONFIGTABLE
#define   BSC_API_DEL_SCCPBEHAVIORCONFIGTABLE SCM_MET_DEL_SCCPBEHAVIORCONFIGTABLE

#define   BSC_API_SET_SCCPGTTDPCSSNCONFIGTABLE SCM_MET_SET_SCCPGTTDPCSSNCONFIGTABLE
#define   BSC_API_DEL_SCCPGTTDPCSSNCONFIGTABLE SCM_MET_DEL_SCCPGTTDPCSSNCONFIGTABLE

#define   BSC_API_SET_SCCPGTTDPCCONFIGTABLE SCM_MET_SET_SCCPGTTDPCCONFIGTABLE
#define   BSC_API_DEL_SCCPGTTDPCCONFIGTABLE SCM_MET_DEL_SCCPGTTDPCCONFIGTABLE

#define   BSC_API_SET_SCCPGTTSSNCONFIGTABLE SCM_MET_SET_SCCPGTTSSNCONFIGTABLE
#define   BSC_API_DEL_SCCPGTTSSNCONFIGTABLE SCM_MET_DEL_SCCPGTTSSNCONFIGTABLE

#define   BSC_API_SET_SCCPGTTENABLETABLE SCM_MET_SET_SCCPGTTENABLETABLE
#define   BSC_API_DEL_SCCPGTTENABLETABLE  SCM_MET_DEL_SCCPGTTENABLETABLE

#define   BSC_API_SET_MTP3LINKSETTABLE SCM_MET_SET_MTP3LINKSETTABLE
#define   BSC_API_DEL_MTP3LINKSETTABLE SCM_MET_DEL_MTP3LINKSETTABLE

#define   BSC_API_SET_MTP3ROUTETABLE SCM_MET_SET_MTP3ROUTETABLE
#define   BSC_API_DEL_MTP3ROUTETABLE SCM_MET_DEL_MTP3ROUTETABLE

#define   BSC_API_SET_MTP3LINKSETADMINSTATETABLE SCM_MET_SET_MTP3LINKSETADMINSTATETABLE
#define   BSC_API_DEL_MTP3LINKSETADMINSTATETABLE SCM_MET_DEL_MTP3LINKSETADMINSTATETABLE

#define   BSC_API_SET_MTP3LINKTABLE SCM_MET_SET_MTP3LINKTABLE
#define   BSC_API_DEL_MTP3LINKTABLE SCM_MET_DEL_MTP3LINKTABLE

#define   BSC_API_SET_LINKADMINSTATETABLE SCM_MET_SET_LINKADMINSTATETABLE
#define   BSC_API_DEL_LINKADMINSTATETABLE SCM_MET_DEL_LINKADMINSTATETABLE

#define   BSC_API_SET_MTP3REMOTEPOINTCODETABLE SCM_MET_SET_MTP3REMOTEPOINTCODETABLE
#define   BSC_API_DEL_MTP3REMOTEPOINTCODETABLE SCM_MET_DEL_MTP3REMOTEPOINTCODETABLE

#define   BSC_API_SET_BSSAPTIMERTABLE SCM_MET_SET_BSSAPTIMERTABLE
#define   BSC_API_DEL_BSSAPTIMERTABLE SCM_MET_DEL_BSSAPTIMERTABLE

#define   BSC_API_SET_CICTABLE SCM_MET_SET_CICTABLE
#define   BSC_API_DEL_CICTABLE SCM_MET_DEL_CICTABLE

#define   BSC_API_SET_PCUTABLE SCM_MET_SET_PCUTABLE
#define   BSC_API_DEL_PCUTABLE SCM_MET_DEL_PCUTABLE

#define   BSC_API_SET_LEPINFOTABLE SCM_MET_SET_LEPINFOTABLE
#define   BSC_API_DEL_LEPINFOTABLE SCM_MET_DEL_LEPINFOTABLE

#define   BSC_API_SET_REPINFOTABLE SCM_MET_SET_REPINFOTABLE
#define   BSC_API_DEL_REPINFOTABLE SCM_MET_DEL_REPINFOTABLE

#define   BSC_API_SET_RLCMACCONFIGTABLE SCM_MET_SET_RLCMACCONFIGTABLE
#define   BSC_API_DEL_RLCMACCONFIGTABLE SCM_MET_DEL_RLCMACCONFIGTABLE

#define   BSC_API_SET_SKSCOMMONTABLE SCM_MET_SET_SKSCOMMONTABLE
#define   BSC_API_DEL_SKSCOMMONTABLE SCM_MET_DEL_SKSCOMMONTABLE

#define   BSC_API_SET_SKSLINKSTARTTABLE SCM_MET_SET_SKSLINKSTARTTABLE
#define   BSC_API_DEL_SKSLINKSTARTTABLE SCM_MET_DEL_SKSLINKSTARTTABLE

#define   BSC_API_SET_SKSGENCFGTABLE SCM_MET_SET_SKSGENCFGTABLE
#define   BSC_API_DEL_SKSGENCFGTABLE SCM_MET_DEL_SKSGENCFGTABLE
#endif

#endif
